### ISSUE TITLE
Self-contained specification

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#1]
Comment by Martin Disch in 
https://mailarchive.ietf.org/arch/msg/lake/KmAQm0KmDGEBnvQm3ZGwGiLu3LE/

"The draft does a good job of pointing to the right places in RFC 8152, but I still ended up trying to
understand another ~100 page document just to implement the few constructs I actually needed."

Should we provide more details about COSE constructs, e.g. in appendix A.2?

**Comment by martindisch** [comment]
(pasting my response from the mailing list here for completeness)

Thanks for following up on this. Yes, in my opinion expanding on the COSE constructs would be helpful. But I also sympathize with not wanting to duplicate what is already defined in another RFC (and possibly getting it wrong, as Carsten points out). Considering that there are quite a few implementers already and besides mine you have only received one other similar comment, maybe this isn't an issue for a meaningful majority.

In any case, the draft has made great strides already in terms of accessibility and is in a good state now, so I don't see improvements in this area as an absolute necessity.

**Comment by TimothyClaeys** [comment]
The two COSE constructs that are used in EHDOC, `COSE_Encrypt0` and `COSE_Sign1` are fairly simple. They don't use the recursive `COSE_Recipient` structure or embed `COSE_Keys`. I think it is possible to add some additional clarifications on the structure of the COSE messages in the EHDOC draft without having to copy too much text from RFC 8152.
