### ISSUE TITLE
EDHOC and Availability

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#101]
The current draft has the following text in several places:

"If any verification step fails, the Responder MUST send an EDHOC error message back, formatted as defined in {{error}}, and the protocol MUST be discontinued."

I am not sure this is a good idea. This means that the availability of EDHOC will be low. An attacker can e.g. send a single byte as message_4 and it would make EDHOC shut down imidiatly. I think we need to soften this and give the implementation some more choice here.

Are there constrained radio protocols where noice could be mistaken for an actual message and forwarded to EDHOC or do all constrained radio have strong enough CRC to make sure that that more or less never happens?

**Comment by emanjon** [comment]
I just changed the following text

OLD:
If the Initiator previously received from the Responder an error message with error code 1 (see Section 6.3) indicating cipher suites supported by the Responder which also are supported by the Initiator, then the Initiator SHALL select the most preferred cipher suite of those.

NEW:
If the Initiator previously received from the Responder an error message with error code 1 (see Section 6.3) indicating cipher suites supported by the Responder which also are supported by the Initiator, then the Initiator SHOULD select the most preferred cipher suite of those (note that error messages are not authenticated and may be forged).

Made me think about that I don't think the group has discussed if some error messages should be authenticated.

Some error messages to message_2 could include a MAC to prove that the error was sent by the same party that sent message_3. error messages to message_3 and message_4 could be authenticated.

I am uncertain if this is worth specifying. At least not as long as there are easier ways to an attacker to end the protocol. I think what needs to be done is to specify that
- a processing error does not need to discontinue the protocol, the received message can have been an attack.
- receiveing an error does not need to discontinue the protocol, the received error can have been an attack.

**Comment by sftcd** [comment]
from 20210422 interim: CB perhaps wisely said: "Use cases exist for multiplexing over same port/URI, so applications should normally sort/demultiplex traffic before start interpreting as EDHOC, which implies treating invalid messages that get to EDHOC code as an error or attack"

**Comment by emanjon** [comment]
Yes, my understanding is that we only need to be concerned about attacks where an attacker sends a packet crafted so that it will be processed by EDHOC (which is not hard).

**Comment by emanjon** [comment]
I made a pull request #109 addressing this issue
- Added text on demultiplexing.
- Changed procession so implementation are not mandated to shut down the session if an attacker sends a few bytes to the EDHOC resource / port..
- Added more security consideration on Denial of service.

**Comment by emanjon** [comment]
Writing this PR made me think about whether we want to mandate that error messages are always fatal as well as downgrade protection.

- The ""Wrong selected cipher suite" error is fatal because it is sent in repsponse to message_1. You could consider similar types of error sent in response to message_2 and message_3. E.g. ID_CRED format not supported or CRED format not supported or X.509 public key algorithm not supported.

[BBFGKZ16] defines the following theoretical downgrade protection for a session: The cryptographic parameters should be the same on both sides and should be the same as if the peers had been communicating in the absence of an attack. But this definition has very little to do with practical security. In practice it does not matter if an attacker can influence the chosen parameter in the current session or a following session.

I am still confused regarding the purpose of the applicability statement. Is it a informal section describing things the parties need to both support to make the protocol work or is a normative security section relevant for policy and downgrade.

If we want downgrade protection over multiple sessions, the parties need to agree or securely negotiate everything. Downgrade protection for a session does not make much sense to me if an attacker can force the parties to set up a second session with lower security.

**Comment by gselander** [comment]
Do we need to align the terminology, we use both "session" and "instance" in the draft?

**Comment by gselander** [comment]
We can resolve this later, I opened #112.

Unless there are other comments we will soon merge this.

**Comment by emanjon** [comment]
The PR has been discussed and merged. Closing
