### ISSUE TITLE
distinguishing different certificates types/encoding within x5chain

### ISSUE THREAD

**Issue by StefanHri** [lake-wg/edhoc#104]
We can use EDHOC with DER/PEM x509 certificates as well as re-encoded x509 and native CBOR certificates. How certificate type and encoding can be distinguished when x5chain is used?

**Comment by gselander** [comment]
For C509 certificates (working name for what was previously called CBOR certificates) other CBOR labels are requested, see
https://tools.ietf.org/html/draft-mattsson-cose-cbor-cert-compress-08#section-8.8

c5c correspond to x5chain
c5b correspond to x5bag
c5t correspond to x5t
c5u correspond to x5u

The two types of C509 certificates, re-encoded X.509 and natively signed C509, can be distinguished by the first bit.

**Comment by emanjon** [comment]
>  first bit
first byte right now, but formally the first CBOR item

>We can use EDHOC with DER/PEM x509
I do not think you can use COSE/EDHOC with PEM encoding. x5chain/x5bag/x5t is always DER encoding as far as I know. I don't know about how x5u and pplication/pkcs7-mime is encoded.

**Comment by emanjon** [comment]
@StefanHri does this answer you questions? Seems mostly like a COSE question. Do you think any clarifications are needed to the EDHOC document?

**Comment by StefanHri** [comment]
Yes, I think this is now clear for me. However, I noticed now something more in this section namely: 

The section starts with:
"ID_CRED_I and ID_CRED_R are identifiers of the public authentication
   keys of the Initiator and the Responder, respectively.  ID_CRED_I and
   ID_CRED_R do not have any cryptographic purpose in EDHOC."

and then a bit later:
"ID_CRED_x MAY contain the actual credential used for
      authentication, CRED_x.  For example, a certificate chain can be
      transported in ID_CRED_x with COSE header parameter c5c or
      x5chain, defined in [I-D.mattsson-cose-cbor-cert-compress] and
      [I-D.ietf-cose-x509]." 

Both sentences are contradictory. I will suggest changing the first sentence to something like: "ID_CRED_x MAY contain an identifier or a certificate ..."

**Comment by gselander** [comment]
@StefanHri I suppose the use of the term "identifier" is confusing. How about changing the beginning: 

OLD
"ID_CRED_I and ID_CRED_R are identifiers of the public authentication
keys of the Initiator and the Responder, respectively. 

NEW
"ID_CRED_I and ID_CRED_R are used to identify the public authentication
keys of the Initiator and the Responder, respectively.

**Comment by StefanHri** [comment]
I am confused. ID_CRED_I and ID_CRED_R can contain a certificate right? When ID_CRED_I and ID_CRED_R contain a certificate they are not used to identify the public authentication but carry it?

**Comment by gselander** [comment]
@StefanHri I didn't see a contradiction between a piece of data identifying a credential and containing the credential. But if it is confusing it is perhaps better to be explicit. How about this:

OLD
"ID_CRED_I and ID_CRED_R are identifiers of the public authentication
keys of the Initiator and the Responder, respectively.

NEW
"ID_CRED_I and ID_CRED_R are used to identify and optionally transport the public authentication keys of the Initiator and the Responder, respectively.

**Comment by StefanHri** [comment]
This is way more clear for me. Thank you!
