### ISSUE TITLE
Simplifying the correlation

### ISSUE THREAD

**Issue by chrysn** [lake-wg/edhoc#105]
So here's something that may sound a bit intrusive on the whole specification, but from two discussions today it may be worth it:

*What If we take the topic of correlation out of EDHOC completely (like, make corr=3 the only mode it has) and in exchange make it a requirement on the transport to provide method correlation all the time?*

The goal of that exercise would be to reduce over-all complexity. It would take complexity out of EDHOC itself, move it to the EDHOC-over-foo layers -- but it seems to me that all those correlation topics are easier to describe there, reducing over-all complexity.

Concrete changes would be:

* Mentions of the corr parameter would go away from everywhere thy are now; METHOD_CORR would just become METHOD (2 bits rather than 4).
* All the data_x items that now have leading `? C_x` would drop them.
* "Message correlation" would be added to the transport (applicability statement) requirements.
* The CoAP applicability statement would grow by text like this:

> Whenever an EDHOC message is sent from a client to a server in the payload, the EDHOC message is prefixed with the CBOR serialization of the C_x the server picked; in a message_1 (as the server has not picked the C_x), a `null` (encoded as `f6`) is sent there instead. The server uses this first CBOR item to identify the ongoing exchange, and uses the remainder of the payload as an EDHOC message.
>
> As a side note, this means that while responses in an exchange of EDHOC over CoAP are of media type application/edhoc, the requests are not, and there is currently no media type that describes "application/edhoc with an identifier prefixed". This is more of a theoretical concern, as EDHOC exchanges are not typically accompanied by explicit content formats.

These two paragraphs (of which only one is essential) can be much shorter as the stripped-out text, because not only does all the talk about encoding and naming the correlations gets dropped, but also the roles are clearer: We don't have to talk of "C_I in this case, C_R in that case", but (now that we have the terminology of server and client provided by CoAP) can talk of "the C_x picked by the server".

(A side effect of this phrasing "in the payload" is that it'd trivially ensure that the EDHOC option from draft-palombini-core-oscore-edhoc-02 would be sent without the C_i which was considered for manual stripping-out anyway as it'd be redundant with the kid from the OSCORE option).

**Comment by chrysn** [comment]
Note that this would trivially resolve #89.

**Comment by gselander** [comment]
The current spec (-08) essentially incorporated this proposal. 

@chrysn Anything missing?

**Comment by chrysn** [comment]
I've just only had a short glance at -08, and what I've seen resolves this issue; in particlar, I like how appendix turned out.

I'll read (and maybe implement -- no promises) the changed document until the IETF111, but if anything *is* missing I'd open a separate issue; closing this.

Thanks!
