### ISSUE TITLE
Agreement of method

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#11]
Section 3 of -00 says "The Initiator and the Responder need to have agreed on a single method to be used for EDHOC."

Is this enough for expected deployments of EDHOC. If not, is an attacker blocking one method to force the use of a second method acceptable or is negotiation/verification of the selected method needed?

**Comment by gselander** [comment]
In version -01 this is more appropriately described as:

"The Initiator decides on the method parameter, see {{method-types}}. The Responder either accepts or rejects."

This scheme makes sense for the potentially common setting that the Initiator is a constrained device/device behind constrained network, and the Responder is less constrained.

**Comment by marco-tiloca-sics** [comment]
This looks good.

**Comment by emanjon** [comment]
This can be closed now
