### ISSUE TITLE
Make C_1 mandatory

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#124]
Comment from >1 implementer to make the initial byte C_1 of message_1 mandatory rather than optional. This simplifies the disambiguation of messages significantly (relates to #39). The byte budget for message_1 is less severe than message_2 and can afford another byte.

**Comment by gselander** [comment]
If #117 is merged, this issue applies instead to  draft-ietf-core-oscore-edhoc:
https://github.com/core-wg/oscore-edhoc/pull/2

**Comment by emanjon** [comment]
This seems like something that should be discussed in #105. Close?

**Comment by emanjon** [comment]
This is also discuss in #95
