### ISSUE TITLE
Clarify encoding in Appendix B

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#13]
Timothy Claeys suggested changes (on page 47):

OLD
ID_CRED_x = { 34 : COSE_CertHash }, for x = I or R, and since the
SHA-2 256-bit Hash truncated to 64-bits is used (value -15):

NEW
ID_CRED_x = { 34 : COSE_CertHash }, for x = I or R. The digest in 
COSE_CertHash is computed by CBOR decoding CRED_R, hashing the certificate 
bytes with SHA-2 256-bit and truncating the digest to 64-bits (value -15).

---

OLD
CRED_R is the certificate encoded as a byte string:

NEW
CRED_R is the certificate encoded as a CBOR bstr:

**Comment by gselander** [comment]
Hmm . . . need to trim the text in the first change a bit more, taking into account the preceding sentence.

OLD
"And because 'x5t' has value certificate are used, ID_CRED_R is the following:

ID_CRED_x = { 34 : COSE_CertHash }, for x = I or R, and since the SHA-2 256-bit Hash truncated to 64-bits is used (value -15):"

Perhaps 

NEW
"And because 'x5t' is used, ID_CRED_R = { 34 : COSE_CertHash }.

The digest in COSE_CertHash is computed by CBOR decoding CRED_R, hashing the certificate
bytes with SHA-2 256-bit and truncating the digest to 64-bits (value -15)."

**Comment by gselander** [comment]
@fpalombini: Should we update the appendix directly, or the test vector code?

**Comment by fpalombini** [comment]
The test vector code only includes the data, all the text around is added manually, so we can only change that.
