### ISSUE TITLE
How can EAD violate security properties?

### ISSUE THREAD

**Issue by chrysn** [lake-wg/edhoc#141]
Quoting main branch:

> The EAD fields [...] special considerations need to be made such that a) it does not violate security, privacy etc. requirements of the service which uses this data, and b) it does not violate the security properties of EDHOC.

I see how an application developer would take a into account, but I think that for b, it'd help to give concrete pointers on what not to do. (Right now, other than "putting anything in there that's picked out of the EDHOC engine", I don't have any clue as to what could endanger EDHOC here).

**Comment by gselander** [comment]
This needs to be rephrased. The security/privacy requirements of the security application using EAD may be other than EDHOC. The text should make clear that: 
1. the content of EAD may impact the security properties provided by EDHOC
2. the security properties of EDHOC carrying specific EAD types need to be matched against the requirements of the security application

**Comment by chrysn** [comment]
I'm sorry to have missed the questions around here; the [changes](https://github.com/lake-wg/edhoc/commit/d36118c413ffb410e2badcf4556670a398a31530) clarify how it is used but not what is good or bad content for EAD.

Not proposing that for actual addition in this form yet, but just so that I get the meaning of the section, would this be correct?

> The EAD might impact the security properties provided by EDHOC in two ways: a) it might reveal data about the peers that EDHOC does not reveal, and b) it might build on internals of EDHOC (e.g. any secret keys). In case a), the security analysis is typically "just" about whether it is acceptable to reveal said information, and no worse than if the information were passed out-of-band from EDHOC's point of view. In case b), thorough cryptographic analysis is necessary, for any misuse of the EDHOC internals might render properties of the EDHOC exchange void.

**Comment by chrysn** [comment]
With the "make available ... available to the application" terminology of -14, maybe there is a good criterion now: An EAD construction will need to take care of not violating security properties if it uses internals of EDHOC that are *not* made available to the application?
