### ISSUE TITLE
is 101 pages too many words?

### ISSUE THREAD

**Issue by sftcd** [lake-wg/edhoc#142]
At some point we should think about the length of the spec.

**Comment by gselander** [comment]
As was mentioned in IETF 111 jabber, we have thought about moving out the test vectors.  That would remove 30+ pages in -08. Either to a file in the Github or to another draft.

**Comment by emanjon** [comment]
I think breaking out the test vectors into a separate informational draft like RFC 8448 is a good idea.

**Comment by sftcd** [comment]
On 30/07/2021 12:33, John Mattsson wrote:
> I think breaking out the test vectors into a separate informational draft like RFC 8448 is a good idea.
> 

I'd say that's probably correct, but maybe best to wait
until we think the test vectors are baked before doing
the split? Just to avoid two drafts that get out of whack.

S.

**Comment by mcr** [comment]
sftcd ***@***.***> wrote:
    > On 30/07/2021 12:33, John Mattsson wrote:
    >> I think breaking out the test vectors into a separate informational draft like RFC 8448 is a good idea.
    >>

    > I'd say that's probably correct, but maybe best to wait
    > until we think the test vectors are baked before doing
    > the split? Just to avoid two drafts that get out of whack.

+0.5.

Two drafts in the same github would solve that problem.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     ***@***.***  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by emanjon** [comment]
At a later stage I think we can go through the document and try to cut out some duplicate information.

**Comment by gselander** [comment]
Test vectors are now moved from Appendix D to a separate draft:

https://datatracker.ietf.org/doc/html/draft-selander-lake-traces

**Comment by emanjon** [comment]
I assume we upload draft-selander-lake-traces-00.md to GitHub next to draft-ietf-lake-edhoc.md as suggested by mcr

**Comment by emanjon** [comment]
@sftcd Does this close this issue? There might be some trimming possible, but a lot of requests from people implementing have been more example and guidance related to COSE, CBOR and CDDL.

Without change log the document is 70 pages.

**Comment by emanjon** [comment]
Some of the text is explanation of COSE, e.g.

```
   o  by a hash value;

      *  x5t : ID_CRED_x, for x = U or V,

   o  by a URL;

      *  x5u : ID_CRED_x, for x = U or V,

   o  by a certificate chain;

      *  x5chain : ID_CRED_x, for x = U or V,

   o  or by a bag of certificates.

      *  x5bag : ID_CRED_x, for x = U or V.

```


```
      COSE constructs the input to the AEAD [RFC5116] as follows:

      -  Key K = EDHOC-KDF( PRK_3e2m, TH_3, "K_3ae", h'', length )

      -  Nonce N = EDHOC-KDF( PRK_3e2m, TH_3, "IV_3ae", h'', length )

      -  Plaintext P = ( ID_CRED_I / bstr / int, Signature_or_MAC_3, ?
         EAD_3 )

      -  Associated data A = [ "Encrypt0", h'', TH_3 ]

```

But the addition and the integration in the main body of the document has been requested by implementors.

**Comment by emanjon** [comment]
Some of the IANA section is duplicating earlier chapters. Might be possible to shave 1-2 pages there.

**Comment by emanjon** [comment]
Maybe we keep this open as a reminder to try to reduce any duplicaiton at a later point in time

**Comment by gselander** [comment]
Closing this as agreed in the interim.
