### ISSUE TITLE
Simpler and shorter SUITES_I

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#151]
The current definition of SUITES_I is that the Initiator can chose any truncation of the list of supported cipher suites as long as the selected cipher suite is included. This works and allows the Initiator to give the Responder information about the full list. This is however a bit complex and has led to misunderstandings of the test vectors where several people thought the test vectors were wrong.

i.e. the following are all valid

```
SUITES_I = [6, 5, 6]
SUITES_I = [6, 5, 6, 7]
SUITES_I = [6, 5, 6, 7, 8]
```

I think we should simplify SUITES_I by mandating that the last suite in the list is the selected. This makes SUITES_I much easier to understand and lowers message size when an array is used. Giving the Responder info is not so important.

`SUITES_I = [5, 6] `

CDDL

`SUITES_I : [ 2* suite ] / suite`

**Comment by emanjon** [comment]
Maybe a recommendation that SUITES_R SHOULD contain all cipher suites that R supports.

**Comment by gselander** [comment]
Currently
SUITES_R : [ supported : 2* suite ] / suite

We may keep that, or remove "supported"
SUITES_R : [ 2* suite ] / suite

Alternatively, we may define
SUITES_I : [ supported : 2* suite ] / suite

Any preference?

**Comment by emanjon** [comment]
They should be the same:

`suites = [ 2* suite ] / suite`

or 

`suites = [ supported : 2* suite ] / suite`


And then

```
SUITES_I : suites,
SUITES_R : suites,
```

**Comment by emanjon** [comment]
This needs to be defined as a CDDL type.
`
suites = [ 2* suite ] / suite`

See #155
