### ISSUE TITLE
The CWT Confirmation Method 'kid' should also be updated to bstr / int

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#157]
https://www.iana.org/assignments/cwt/cwt.xhtml

**Comment by emanjon** [comment]
The specification updating 'kid' to bstr / int should likely formally update draft-ietf-cose-rfc8152bis-struct and RFC8747

**Comment by gselander** [comment]
In this mail [1] it is considered an option to make the update without formally updating draft-ietf-cose-rfc8152bis-struct.


[1] https://mailarchive.ietf.org/arch/msg/lake/zLWEBG1fV6wI1WT6gaI3TpiYjS4/

**Comment by gselander** [comment]
RFC 8747 defines 'kid' to be of type value "binary string" which is not the name of a CBOR type. Should presumably be "byte string", i.e. CBOR major type 2.
