### ISSUE TITLE
Registration of a CoRE Resource Type

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#158]
A new Resource Type (rt=) Link Target attribute like "core.edhoc" may be registered in the "Resource Type (rt=) Link Target Attribute Values" subregistry under the "Constrained RESTful Environments (CoRE) Parameters" registry.

**Comment by emanjon** [comment]
That seems like a good idea.

**Comment by emanjon** [comment]
Marco, do you want to provide a PR? Then we could merge that for -11

**Comment by marco-tiloca-sics** [comment]
Done, see https://github.com/lake-wg/edhoc/pull/164

Note that the first commit is just about removing trailing whitespace to avoid compiling errors.

The content you need is in the commit https://github.com/lake-wg/edhoc/pull/164/commits/3b0f225aa1f35182126bb96abfd2e8be8c187e9f

**Comment by emanjon** [comment]
Looks good. I tried to align the whole IANA section with RFC 8126. Then I merged.
