### ISSUE TITLE
Make it clear that ID_CRED_x are COSE header maps

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#161]
ID_CRED_x are COSE header maps and everything with them follows from COSE. The only thing EDHOC adds is to define the format of CRED_x.

This is not clear in the current version of the draft. The term "COSE header map" has disappeared and it is not clear that the quite long section on ID_CRED_x are just examples of COSE and not new specification.

CDDL for ID_CRED_x should be added. They are of type header_map defined in the COSE RFC.

**Comment by emanjon** [comment]
We should probably add CDDL for CRED_R as well. CRED_R is in general any as it needs to support any future header parameters COSE defined for header_map.

For the currently defined credentials

```
CRED_x = bstr / map / COSE_Messages / C509Certificate
```

```
x509      bstr
uccs      map
cwt        COSE_Messages
c509     C509Certificate
```

The draft need to say something about tags. Is both tagged and untagged allowed in CRED_X?

COSE_Messages = COSE_Untagged_Message / COSE_Tagged_Message

**Comment by emanjon** [comment]
The mapping from a a COSE header map to a credential or set of credentials is handled by COSE. Note that a COSE header map can contain several header parameters

```
{ x5u, x5t }
{ kid, kid_context }
{ crit [ c5u ] }
{ kid, c5t }
```

EDHOC needs to provide a mapping from the credential or set of credentials (e.g. chain, bag, etc. ) to CRED_R. The mapping needs to be equal on both sides. We would like EDHOC to as automatically as posibly support new header parameters and credential types.

Currently the COSE header parameters can identify the following credentials.

By reference

```
COSE_Key
COSE_Key in an UCCS
COSE_Key in an CWT
x509 single certificate
x509 chain or bag
c509 single certificate
c509 chain or bag
```

By value

```
UCCS
CWT
x509 single certificate
x509 chain or bag
c509 single certificate
c509 chain or bag
```

Most of the mapping to CRED_R is currently soft or not existing. It need to be specified exactly. If the parties to different mapping EDHOC will fail.

- For x509 the solution is to wrap the end-entity DER certificate in a bstr.
- For c509 the solution is to take the end-entity C509Certificate structure
- CWT and UCCS can be tagged and untagged. This might be fine for "by value" but might create problems for "by reference" which is the main focus of EDHOC. Should EDHOC leave this to the application? Or do we need to handle situation where one of the parties have stored a CWT with an added tag.....
- "Raw" COSE_Keys (not inside a CWT or UCSS). Are they supported or not or is UCCS only the way to go? Most if not all COSE implementations have support for raw COSE keys.
- Raw COSE_Keys and UCCS where not really designed to be MACed. Can we expect that one of the parties to add things to the CBOR map?

```
       {                                      /COSE_Key/
         1 : 1,                                   /kty/
         2 : 0,                                   /kid/
        -1 : 4,                                   /crv/
        -2 : h'b1a3e89460e88d3a8d54211dc95f0b90   /x/
               3ff205eb71912d6db8f4af980d2db83a',
        -65537 : "Note to self: Why did the chicken cross the Möbius strip?"
       }

```

**Comment by emanjon** [comment]
While we have working interop for the many of the use cases. I think it is clear that ID_CRED_x and CRED_x need to be specified a bit more in detail.

For ID_CRED_x I think EDHOC should rely on COSE as much as possible. Formatting of CRED_x is outside of COSE and needs to be specified in EDHOC.

My suggestions: 

- I think ID_CRED_x and CRED_x should be defined with CDDL
- I think EDHOC should specify that ID_CRED_x is a COSE header_map but acknoledge that some of the COSE header parameters do not make sense to use in EDHOC. This way EDHOC automatically support new COSE header parameters.
- I think EDHOC should support all COSE header parameters that can be used to identity a cryptographic key.
- In addition there is a need of a map between the object the key is stored in and CRED_x. I think this should maybe be done with a table. An IANA registry might not be wrong.

```
ID_CRED_x = header_map

CRED_x = any    (where any is determined by the key cryptographic key object)

```
```
===========================================
Credential type            CRED_x CDDL type
-------------------------------------------
COSE_Key                   COSE_Key
UCCS                       map
CWT                        COSE_Untagged_Message
X509                       bstr (end-entity)
C509                       C509Certificate (end-entity)
===========================================

```
The table above use untagged CWS and UCSS. This avoids problems if of the parties tag their UCCS or CWT for storage. The three options are:

1. Forcing untagged CRED_x.
2. Forcing tagged CRED_x.
3. Forcing I and R to agree on the format.

3. does not seem optimal as the parties need to remember if the credential was tagged or untagged when they got it. The coice between 1. and 2. depends on what creates the least work for implementations.

Further discussion points are content and order, which the parties need to agree on.

- EDHOC should state that the parties cannot add private headers to COSE_Key and UCCS
- Regarding order, the choices are
   a) force lexiographical order
   b) force the parties to agree on the order.
  I don't really understand why the order is unspecified in the first place, but given that is is and that COSE assumes that entities can and will reorder it seems like forcing lexiographic order might be the best. That should probably be recommended in general.

**Comment by marco-tiloca-sics** [comment]
Some input on some of the points above:

* I think it's good to exclude "Raw" COSE Keys altogether, like it recently seemed to be the plan.
   - As a main limitation, they don't allow to express additional metadata, including peer identity and credential expiration, that might be important to have around as part of an authenticated credential. As another limitation, they can't currently be transported by value, because there is no COSE Header Parameter for that.
   - On the other hand, it's pretty cheap and easy to build a UCCS around a COSE Key. If COSE Keys are already supported in one's implementation, the additional step to take for "dressing-up" a "Raw" COSE Key as a UCCS is really small (trivial?), and might of course be limited to including only the 'cnf' claim, with no further metadata if that's appropriate/desired. Hence I think it's worthwhile and justifiable to have UCCS as a better substitute without the limitations above.

* For the inner COSE Key structure, I believe forcing the lexicographical order of its elements is best and most viable.

* If I understand correctly, there is no need to integrity-protect also the possible CBOR tags. Then, I'd propose to generally admit both tagged and untagged objects. However, possible CBOR tags must be stripped away when building CRED_X --- Relates to https://github.com/lake-wg/edhoc/issues/162

**Comment by emanjon** [comment]
Thanks Marco. My understandanding of the the current suggestion from Marco is:

**COSE:** The COSE header parameters for CWT and ECCS allow bot tagged and untagged and do not enforce any specific order in the map.

**EDHOC:** When CWT and UCCS is used in EDHOC, then CRED_x is the untagged CWT or UCCS sorted
in lexigraphical order as defined by deterministic CBOR.

That works for me.

**Comment by emanjon** [comment]
UCCS are great, they are clearly a more flexible format for RPKs than "raw" COSE_Keys. I think
the important thing is that EHDOC support UCCS as "raw" COSE_Keys has clear limitations. It
would be good to enourage use of UCCS, but from a design perspective it would be
nice to say that EDHOC relies on COSE and support all credentials that can be identified
with COSE.

It is certainly trivial to dress up a COSE_Key as a UCCS.

```
Naked:     COSE_Key 
Dressed:   { 8 : { 1 : COSE_Key } }
```

This is done by prefixing the COSE_Key with 0xA108A101. I like the idea of dressing up
a COSE_Key as a UCCS. This needs to be specified a bit more in the document.

**Comment by emanjon** [comment]
So the current suggestion would be something like:

```
===========================================
Credential type                       CRED_x CDDL type
-------------------------------------------
UCCS / COSE_Key                   map (UCCS map sorted in lexiographical order)
CWT                                       COSE_Untagged_Message (Outer layer in lexiographical order)
X509                                      bstr (end-entity)
C509                                     C509Certificate (end-entity)
===========================================
```

The parties need to agree on the content in the CRED_x UCCS map.

Do we need to specify lexiographical ordering for the CWT as well? If I understand correctly, some parts of the outher layer are formally unordered.
