### ISSUE TITLE
COSE CWT and UCCS header parameters - tagged, untagged, or both

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#162]
The IANA section currectly specified that CWT can be sent tagged or untagged while UCCS can only be sent untagged. That is probably not how it should be.

**Comment by emanjon** [comment]
Only untagged:

```
cwt               COSE_Untagged_Message
uccs             map

```

Untagged or tagged:

```
cwt               COSE_Messages
uccs             #TBD601(map) / map

```

Only tagged

```
cwt               COSE_Tagged_Message
uccs             #TBD601(map)
```

**Comment by emanjon** [comment]
Tagged add bytes that are not required. The COSE header parameter alredady gives this information.

Except that I don't have a strong opinion between allowing both and only allowing untagged.

Note that this is mostly a COSE question, rather than LAKE

**Comment by emanjon** [comment]
The UCCS tag numer has not been assigned yet. 

https://datatracker.ietf.org/doc/html/draft-ietf-rats-uccs

**Comment by marco-tiloca-sics** [comment]
If I understand correctly, there is no need to integrity-protect also the possible CBOR tags. Then, I'd propose to generally admit both tagged and untagged objects. However, possible CBOR tags must be stripped away when building CRED_X --- Relates to https://github.com/lake-wg/edhoc/issues/161

**Comment by emanjon** [comment]
>If I understand correctly, there is no need to integrity-protect also the possible CBOR tags.

There is no need, but if used in the protected header as in EDHOC they will be integrity protected. That however not a problem as the protected header_map is sent on the wire, so both parties will have the same formatting.

**Comment by emanjon** [comment]
Thanks Marco. My understandanding of the the current suggestion from Marco is:

COSE: The COSE header parameters for CWT and ECCS allow bot tagged and untagged and do not enforce any specific order in the map.

EDHOC: When CWT and UCCS is used in EDHOC, then CRED_x is the untagged CWT or UCCS sorted
in lexigraphical order as defined by deterministic CBOR.

That works for me.

**Comment by emanjon** [comment]
Do CWT and UCCS need several header parameter each similar to x5u x5t x5chain x5bag?

**Comment by gselander** [comment]
New name (kcwt/kccs) and description: 4910a42f

**Comment by gselander** [comment]
>  When the authentication credential is a X.509 certificate, CRED_x
>  SHALL be the end-entity DER encoded certificate wrapped in a bstr
>  [I-D.ietf-cose-x509].

@cabo commented in the interim on "wrapped in a bstr" needs to be clarified.
