### ISSUE TITLE
Align exporter labels

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#163]
The 4 labels use different styles. Should probably align them in -11.

```
   Label: EDHOC_message_4_Key
   Label: EDHOC_message_4_Nonce
   Label: OSCORE Master Secret
   Label: OSCORE Master Salt

```

**Comment by emanjon** [comment]
1. Should they be aligned?

2 If yes, how should they be aligned?

```
a)
EDHOC message 4 Key
OSCORE Master Secret

b)
EDHOC_message_4_Key
OSCORE_Master_Secret
```

**Comment by emanjon** [comment]
For information, the labels used directly with the internal EDHOC-KDF (together with TH_2 and TH_3) are

KEYSTREAM_2
MAC_2
K_3ae
IV_3ae
MAC_3

**Comment by emanjon** [comment]
The TLS exporter seems to avoid blank space and most labels use dash instead. Don't know if that is a smart design decision or just random. That might point to b) being a good approach if we want to do alignment.

**Comment by gselander** [comment]
Fixed in dad40e5

**Comment by emanjon** [comment]
Good that you fixed the structure in message_4 so the key is defined for COSE_Encrypt and not only for the underlying AEAD. Good with a name change to IV which is what COSE calls the input.

Based on the new names K_4 and IV_4 we should maybe rename to K_3 and IV_3 as well.

**Comment by emanjon** [comment]
Maybe just
 
   * Key K_4 = EDHOC-Exporter( "EDHOC_K_4", h'', length )
   * IV IV_4 = EDHOC-Exporter( "EDHOC_IV_4", h'', length )

**Comment by emanjon** [comment]
Some ideas from the TLS exporter that could be used.

The label is a string consisting of the printable ASCII characters 0x21 - 0x7e.

Label values beginning with "EXPERIMENTAL" MAY be used for private use without registration. All other label values MUST be registered.

**Comment by emanjon** [comment]
This has been merged to master.
