### ISSUE TITLE
Content of draft-selander-lake-traces

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#169]
We should discuss how many test vectors draft-selander-lake-traces should contain and what the content should be.

This applied to the old appendix as well, but is now even more obvious that we need to use a real X509 certificate. E.g. the example one from https://datatracker.ietf.org/doc/draft-ietf-cose-cbor-encoded-cert/ The cipher suite should probably be one with ECDSA, e.g. cipher suite 2.

   CRED_R (CBOR Data Item) (113 bytes)
   58 6f 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13 14
   15 16 17 18 19 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25 26 27 28 29 2a 2b
   2c 2d 2e 2f 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 40 41 42
   43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 50 51 52 53 54 55 56 57 58 59
   5a 5b 5c 5d 5e 5f 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e

**Comment by emanjon** [comment]
I think the document need to talk about the authentication key algorithms in the credentials.

**Comment by emanjon** [comment]
Mention which version early

**Comment by gselander** [comment]
I believe the points raised here are addressed in the test vectors in the -traces draft, so this issue can be closed.

**Comment by gselander** [comment]
Closing this as there were no comments.
