### ISSUE TITLE
Traces document - New note on connection identifiers

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#170]
In Section 2 of the EDHOC traces document [1], I suggest to add the note below (or something similar):

NOTE 3.  Remember that an EDHOC message never starts with a connection identifier or with an analogous sentinel value like the CBOR simple value "true" (0xf5). These are possibly prepended to an EDHOC message as the transport protocol needs, but are not part of the EDHOC message.

[1] https://datatracker.ietf.org/doc/html/draft-selander-lake-traces-00#section-2

**Comment by gselander** [comment]
I agree it is good to point out in this draft that a real world EDHOC trace would typically contain connection identifiers. Perhaps we can formulate it as follows:

NOTE 3. When the protocol transporting EDHOC messages does not inherently provide correlation across all messages, like CoAP (see 3.4.1 and A.3 of {{EDHOC}}), then some messages typically are prepended with connection identifiers and  message_1 indicator. Those bytes are omitted from the traces in this draft.

**Comment by marco-tiloca-sics** [comment]
It looks good.

**Comment by emanjon** [comment]
This has been merged to master. Let's close
