### ISSUE TITLE
Use of confirmable messages in CoAP

### ISSUE THREAD

**Issue by chrysn** [lake-wg/edhoc#174]
Following a discussion recently had with Carsten and the CoAP-EAP authors, I stumbled upon this sentence:

> According to this specification, EDHOC messages are carried in Confirmable messages, which is beneficial especially if fragmentation is used.

No other part of the spec mentions CONs (apart from the deduplication part where it does fit well), so maybe this is not intended anyway. At most, it could say:

> To avoid that the EDHOC exchange gets stuck (especially when fragmentation is used), the underlying CoAP transport should be used in reliable mode.

**Comment by gselander** [comment]
How about this:

"The underlying CoAP transport should be used in reliable mode, in particular when fragmentation is used, to avoid, e.g.,  situations with hanging endpoints waiting for each other."

**Comment by chrysn** [comment]
I like it, that'd work fine.
