### ISSUE TITLE
Replace UCCS with CCS

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#175]
UCCS refers to a CWT claims set. "Unprotected" is redundant. That change would makes the CBOR header 'kccs' more natural.

**Comment by emanjon** [comment]
It is, but draft-birkholz-rats-uccs defines the tag for an UCCS. Not sure EDHOC and draft-birkholz-rats-uccs having different terminology would be good.

TBD601 | map       | Unprotected CWT Claims Set [RFCthis] 

Maybe discuss with the authors of draft-birkholz-rats-uccs

**Comment by emanjon** [comment]
CWT Claims Set seems like the correct term following RFC 8392.

```
A.1.  Example CWT Claims Set

   The CWT Claims Set used for the different examples displays usage of
   all the defined claims.  For signed and MACed examples, the CWT
   Claims Set is the CBOR encoding as a byte string.
```

**Comment by gselander** [comment]
Perhaps closed this too quick, reopening to allow alignment with draft-birkholz-rats-uccs

**Comment by gselander** [comment]
It is actually no problem if draft-ietf-rats-uccs has a different abbreviation since we both refer to RFC 8392, so the term is well defined. Closing.
