### ISSUE TITLE
Security considerations of TOFU

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#178]
The current text is not really explaining how TOFU works and the security considerations. Would be good with some more text. TOFU might also go agains requirements in other parts of the document that says that "EDHOC is mutually authenticated.

**Comment by gselander** [comment]
This is conflicting with present use of COSE. Requires a separate section in the draft, preferably an appendix. We need to describe the use case, trust model, how to use EDHOC and the security properties. Can we reference some other RFC?

**Comment by emanjon** [comment]
Looking at adding text on TOFU I think there is some more work to do. I don't TOFU should require anything specicial.

The Section "Identities and trust anchors {#identities}" is fluffy. It is not clear that this is just general recommendations that is outside the scope of the EDHOC protocol and the reposability of the application. EDHOC provides proof-of-possesion and transfers a credential that enables authentication. Thats it. An EDHOC implementation might implemend Authentication for a specific use case, but that is still outside the EDHOC protocol.

Any description of the interface between EDHOC and the application when it comes to credential is missing. In general EDHOC provides proof-of-possesion of the private key and then gives CRED_x to the application that says YES/NO. How the application does chain validation and identity validation (or the lack of it like in TOFU) is outside of EDHOC.

**Comment by emanjon** [comment]
Status: This issue is waiting on a restructure, shortening, clarification on the responsibility of the EDHOC protocol and the application.

#212 and #223

**Comment by gselander** [comment]
The restructuring is done and merged with the master. Appendix D.5 is placeholder for TOFU.

**Comment by emanjon** [comment]
I made PR #307 for TOFU. As Marco pointed out this should be more general than TOFU. I changed the heading to "unauthenticated opearation" which is the term used by TLS 1.3
