### ISSUE TITLE
How to handle x5t-sender etc.

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#183]
For a bit unclear reasons. COSE specifies different x5t header parameters for SS-ECDH sender and recipient, e.g., x5t and x5t-sender. When kid is used for SS-ECDH, the same header parameter is used for both sender and recipient...

Unless this is changed in COSE. EDHOC need to add some additional specification or clarification.

1. When used in EDHOC all header parameters always refer to sender.
2. x5t-sender is not used etc.
3. x5t is not used etc.

**Comment by gselander** [comment]
For EDHOC, the header parameter is either transported in ID_CRED_I or ID_CRED_R. So it is clear whether the header parameter refers to I or R, i.e. always to the sender. 

If we want to allow x5t-sender etc, then we need to provide an interpretation of the listing of algorithms associated to x5t-sender (but not x5t) in relation to the EDHOC cipher suite. Does this list limit the EDHOC cipher suite or can it be ignored? In the former case, the list may need to be updated when new EDHOC cipher suites are defined. This seems like an unnecessary complication when the objective of the header parameter in EDHOC is just to identify the credential and for that purpose x5t etc. seems sufficient. 

I propose we state:

* header parameter in ID_CRED_x refers to x (i.e. sender)
* x5*-sender MUST NOT be used

**Comment by emanjon** [comment]
>For EDHOC, the header parameter is either transported in ID_CRED_I or ID_CRED_R. So it is clear whether the header parameter refers to I or R, i.e. always to the sender.

I think the same could be said for COSE where the recipient structure makes the separation clear.

>If we want to allow x5t-sender etc, then we need to provide an interpretation of the listing of algorithms associated to x5t-sender (but not x5t) in relation to the EDHOC cipher suite. Does this list limit the EDHOC cipher suite or can it be ignored? In the former case, the list may need to be updated when new EDHOC cipher suites are defined. This seems like an unnecessary complication when the objective of the header parameter in EDHOC is just to identify the credential and for that purpose x5t etc. seems sufficient.

I don't undestand this part. EDHOC does not use COSE header parameters to detemine algorithms.

>I propose we state:

That sounds great.

**Comment by emanjon** [comment]
The problem is that COSE says the following about x5t, x5u, x5chain, x5bag:

"The header parameters defined in the previous section are used to
identify the recipient certificates for the ECDH key agreement"

EDHOC needs to state that this is not the case when they are used in EDHOC.
