### ISSUE TITLE
Missing SUITES_R in the test vectors 

### ISSUE THREAD

**Issue by StefanHri** [lake-wg/edhoc#188]
Currently, the test vectors do not include SUITES_R. For my tests, I am assuming that SUITES_R contains the selected suite by the initiator. However, it will be better to provide SUITES_R in the test vectors since this will make automated testing easier.

Additionally, it will be nice if SUITES_R and SUITES_I are provided unencoded as well.

**Comment by emanjon** [comment]
Note that SUITES_R only exist as part of a specific error message. SUITES_I also only exist as part of  a specific message_1. There are no general SUITES_I and SUITES_R outside of these messages.

Are you looking for list of the the cipher suites that I and R supports?

**Comment by StefanHri** [comment]
yes exactly.

**Comment by gselander** [comment]
The traces draft now includes an example of the use of SUITES_R. There could be more examples in the test vectors on the github repo. 

Note, however, that the procedure for how I selects and R proposes cipher suites in error messages is out of scope of EDHOC, it only specifies how I and R must act to avoid being tricked into using a cipher suite which is not the most preferred by I which is supported by both.

**Comment by emanjon** [comment]
> The traces draft now includes an example of the use of SUITES_R.

This closes the issue
