### ISSUE TITLE
Support of SHAKE and KMAC

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#19]
The COSE WG is working on adding SHAKE128 and SHAKE256 to COSE and there is ongoing work to define the use of KMAC128 the KMAC256 as KDFs.

https://tools.ietf.org/html/draft-ietf-cose-hash-algs
https://tools.ietf.org/html/draft-schaad-cose-more-algs

There has been interest in the IETF IoT community to use these algorithms. As currently specified, EDHOC supports SHAKE, but would run SHAKE in HMAC mode, which is inefficient. 

Should EDHOC should be updated to use a KMAC KDF together with SHAKE? I.e KMAC128 instead of HMAC-SHAKE128 for Extract and Expand.

**Comment by gselander** [comment]
As I understand this, this is an aspect of future-proofing, where the cipher suite would contain one more item, the extract-and-expand-scheme, with currently two potential values: either HMAC or KMAC.

**Comment by pbtgit** [comment]
No strong opinion but it seems to make sense to go for the more efficient combination with KMAC.

**Comment by TimothyClaeys** [comment]
I seems like the current hardware acceleration for hashing in constrained devices is limited to SHA-2 implementations [1][2]. I also think it is preferable to go for the more efficient KMAC extension, unless a software implementation of KMAC would require substantially more flash than SHAKE.

[[1]](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf52840%2Fkeyfeatures_html5.html)
[[2]](https://www.ti.com/lit/ug/swru319c/swru319c.pdf?ts=1605020127382)

**Comment by emanjon** [comment]
KMAC is basically SHAKE so if an implementation has SHAKE, they more or less have KMAC. KMAC is a thin shim layer.

**Comment by emanjon** [comment]
The agreed KMAC change is now added to Master.

The change to the specification is quite small. EDHOC is now defined in terms of Extract and Expand instead of HKDF-Extract and HKDF-Expand. When SHA-2 is used then HKDF-Extract/HKDF-Expand is used. When SHAKE is used then KMAC is used.

The change does not affect current implementations. 

BTW the title of this issue is misleading. SHAKE is supported like all COSE algorithms. We are not planning to define a cipher suite at this moment but SHAKE can be used with private cipher suites.

**Comment by emanjon** [comment]
When SHAKE is used (currently this can only be done with a private cipher suite) then KMAC is used. This behavior is specified in -03 and has been discussed at the two last interims
