### ISSUE TITLE
Correct the information about non-repudiation.

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#191]
The current text talks about saving the ephemeral key. The text should talk about saving all the input to the signature algorithm. These are not send on the wire, but they are also not as secret at the private key.

**Comment by gselander** [comment]
The repudiation text is fine now, but it is formulated as if both parties have signature keys or both parties have static DH keys. We may want to cover methods 2 and 3 as well.

**Comment by emanjon** [comment]
Göran's comments above was handled and there has not been any further comment. Seems to be agreement regarding the current non-repudiation text. Closing this
