### ISSUE TITLE
Allow COSE HPKE algorithms for method 0?

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#193]
COSE is discussing to register HPKE (KEM) agorithms.

https://datatracker.ietf.org/doc/draft-tschofenig-cose-hpke/
https://mailarchive.ietf.org/arch/msg/cose/KbuVtBk5vcxrTOzi2TWTUZiikmk/

There does not seem to be any current advantages to use these HPKE algorithms in EDHOC. In the future several people have expressed that they would like EDHOC method 0 to support PQC KEMs when they are registered to COSE. If the belief is that COSE will rely on HPKE for PQC KEMs, then EDHOC should consider supporting COSE HPKE KEMs already now. (This would be a quite trivial change).

Note that method 1,2,3 cannot use KEMs without modifications. Building an AKE with KEMs instead of ECDH makes things less efficient as you need more roundtrip. For an example how an SIGMA like AKE with KEMs could look like, see e.g. KEMTLS. https://eprint.iacr.org/2020/534.pdf

**Comment by gselander** [comment]
Considering we don't know how COSE will define PQC KEMs, perhaps it is too early to make the change now? Instead introduce it in an update together with a new cipher suite when available from COSE.

**Comment by mcr** [comment]
If I were going to attempt to do challenged-networks and PQC, then what I'd be doing it figuring out a model where long-term AES256 Kerberos tickets are installed into the devices at manufacturing time.  I'd be setting up federated kerberos with operational networks.

For COSE and EDHOC, what this means is: doing authentication with this long-term key, and some PQC KEM magic instead of ECDH.  I don't really believe in that magic, btw.

**Comment by emanjon** [comment]
>Considering we don't know how COSE will define PQC KEMs, perhaps it is too early to make the change now?

We don't but we might get an idea quite soon. 

>Instead introduce it in an update together with a new cipher suite when available from COSE.

It is definitly to early to introduce any cipher suites. What could potentially be done right now is to define use of COSE HPKE algorithms in EDHOC, allowing people to use them with the private cipher suites.

A future draft with ciphersuites might be preferable, but the PQC train is moving fast right now as the NIST will announce the winners and NSA will update the CNSA suite in just a few months. I would not be suprised at all to see a draft with HPKE PQC algorithms in CFRG in time for IETF 113.

**Comment by emanjon** [comment]
Close this for now. Current plan is to do this in a separate draft at a later stage that can also introduce cipher suites.

For things that are not US CNSA TOP SECRET with data lifetimes of many decades, there might be more urgent things that attacks from quantum computers.

"There is however a huge gap between today’s noisy small quantum computers and the large-scale fault-tolerant quantum computers that could threaten today’s public key cryptography. ASD (Australia) recently told the Australian senate that they believe quantum computing poses no immediate threat to the current cryptographic methods used to encrypt data across the federal government. ASD is not convinced quantum computing is moving fast enough. Currently stored encrypted data holdings will remain secure from decryption for lengths of time appropriate to the sensitivity of the data. ASD does not expect it will be possible within these lengths of time to build a quantum computer that can break the current algorithms and key sizes. NSA has suggested that for things not requiring more than 10 years of protection, malware and supply chain security is likely more pressing issues.”
