### ISSUE TITLE
Compact Representation Apendinx

### ISSUE THREAD

**Issue by stoprocent** [lake-wg/edhoc#195]
Hi Guys

I think there is a mistake in:
Compact Representation - https://github.com/lake-wg/edhoc/blob/master/draft-ietf-lake-edhoc.md#compact-representation-comrep

> The encoding of the point at infinity is not supported. Compact representation does not change any requirements on validation. If a y-coordinate is required for validation or compatibily with APIs the value ~yp SHALL be set to zero. For such use, the compact representation can be transformed into the SECG point compressed format by prepending it with the single byte 0x02 (i.e., M = 0x02 || X).

I think single byte prefix will depend if `y` is odd or even. From above paragraph it looks like it will always be `single byte 0x02`

**Comment by emanjon** [comment]
> "it looks like it will always be single byte 0x02"

That is the intention. Always using 0x03 does also work, as does flipping a coin. The sign of y does not affect the output when the ECDH function only depends on the x value of G_XY, so called "compact output" (basically all modern DH functions work like this). Maybe we should add a sentence describing this.

For some more information see the following drafts:

https://datatracker.ietf.org/doc/draft-harkins-cfrg-dnhpke/
https://datatracker.ietf.org/doc/html/rfc6090

**Comment by stoprocent** [comment]
@emanjon ECDH is not the only operation. If the `METHOD` is set to signature this will not work if the private key is not generated in the way to support compact mode. I did some testing with multiple crypto libraries and if the private key is not generated in a particular way signature validation will not succeed. In my opinion we should either have the correct prefix or have a clear instructions about private key generation which I would not be a huge fan of :P

**Comment by emanjon** [comment]
Appendix B is only intended for the ephermeral ECDH keys sent on the wire. The generation and format of the authentication keys (Signatures or static ECDH) are given by other specifications such as COSE, X509, C509....

I agree that the following sentence is not good and should be updated.

```
3.7. Ephemeral Public Keys
EDHOC always uses compact representation of elliptic curve points, see Appendix B.

```

(FYI, the private keys are not elliptic curve points at all, they are just scalars).

**Comment by stoprocent** [comment]
I'm sorry I had a brain fog :) Of course, we are taking about `G_XY` ECDH process. I've mixed it up with message authentication.

**Comment by gselander** [comment]
This issue is closed but just to keep track, here is the clarification made following the discussion in this issue: a5fde0e9
