### ISSUE TITLE
Ciphersuites requiring multiple SHA 

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#2]
Comment by Rene Struik:
https://mailarchive.ietf.org/arch/msg/lake/KGiw6uY5u5J9ANcwbnsaRvqWh1s/

"why enforcing both SHA512 and SHA256 at the same time"

Ed25519 specifies SHA512. Ciphersuite 0 and 1 additionally requires SHA256.

Proposed solution: Require only SHA512 in ciphersuite 0 and 1.

**Comment by ms-s** [comment]
A couple of references to look at while fixing this issue: 
https://tools.ietf.org/html/draft-ietf-lwig-curve-representations-11
and 
https://tools.ietf.org/html/draft-ietf-6lo-ap-nd-23#section-8.2

**Comment by gselander** [comment]
https://tools.ietf.org/html/draft-ietf-lwig-curve-representations-11 may not solve the issue with SHA-512 but should be mentioned in the security considerations, together with relevant NIST terminology.

**Comment by gselander** [comment]
Discuss at IETF 109. When changed, test vectors needs to be updated.

**Comment by emanjon** [comment]
Cipher suite 0 and 1 when used with Static Diffie Hellman keys does not require SHA-512. So we should not change this to SHA-512

**Comment by gselander** [comment]
So, to have a cipher suite with a single SHA (and avoid implementing multiple), signature and static DH algorithms need to use the same, which requires a new specification of one or the other?

See also #21.

**Comment by gselander** [comment]
More background. Hash functions are used in several places in EDHOC:
- Transcript Hash
- Key-Derivation Function (KDF)
- Signature algorithm
- Credential identifiers (ID_CRED_R and ID_CRED_I)
Additionally, a hash function is used by the application, e.g., in the OSCORE KDF.

A solution involving only SHA-512 in cipher suites with Ed25519 would require more memory to handle larger digests. Note that it also increases the length of x5t identifiers to 256 bit instead of 64.

**Comment by marco-tiloca-sics** [comment]
Based on the points in the comment above, I concur it is good to have (also) SHA-256 involved in the cipher suites.

**Comment by pbtgit** [comment]
I agree on keeping SHA-256

**Comment by TimothyClaeys** [comment]
I also agree on keeping SHA-256. Since I prefer to switch to Ed25519 with SHA-256 (https://github.com/lake-wg/edhoc/issues/22#issuecomment-724843802), this would also solve the issue of using multiple SHA primitives in a single ciphersuite.

**Comment by gselander** [comment]
This issue has been overtaken by events.  SHA-256-only implementations are supported as of 70088cc.
