### ISSUE TITLE
Rekeying of AEAD algorithms

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#20]
The TLS WG have analyzed, discussed, and specified bounds for distinguishing and forgery attacks on various AEAD algorithms in TLS. The distinguishing attack lets an attacker destringing the ciphertext from a random string and the forgery attack lets an attacks forge a single message (typically consisting of a random looking string). CFRG is now planning to publish a document with formulas to calculate AEAD limits. The limits chosen by TLS are stricter that any earlier protocol or specification. This is fine if rekeying is easy.

It would be good if the IETF IoT community discussed which probability is acceptable for the IoT protocols in IETF. 

EDHOC does not use the same key more than once, but the exported session key might be used for a long period in e.g. OSCORE. The most efficient solution may be to rekey in the application security protocol. E.g. if OSCORE would frequently derive a new Sender/Recipient Key from the Master Key, this would effectively mitigate distinguishing attacks. See e.g. "key_derivation_rate" in SRTP (RFC 3711). This is not currently part of OSCORE but could quite easily be added in a backward compatible way.

What is the acceptable probability for IoT? How do we do this rekeying for OSCORE? Do we need to do anything in EDHOC at all?

**Comment by gselander** [comment]
OSCORE sequence numbers allow synchronized rekeying at regular intervals. The "key_derivation_rate" needs to be known, either alg-dependent or set by the application, but there could be a default value, e.g., corresponding to AES_128_CCM_8.

**Comment by chrysn** [comment]
How many usable messages are we talking about?

After skimming DTLS1.3, it sounds to me that it's about 2^23 messages. If that's the order of magnitude we're talking about, I'd practically do nothing at all but flag a security context as exhausted at reaching 2^23 rather than reading 2^40 with a per-algorithm limit, or just the worst-case limit for the supported algorithm. Any mechanism that's added would need to justify how it amortizes the additional code size in firmware updates over running an EDHOC continuation run every 2^23 messages.

If, of course, the sequence number space is limited to something to less than 2^14, something might need to be done.

**Comment by gselander** [comment]
Yes, 2^23 is the number we have seen for DTLS 1.3 and which can serve as a first estimate also for OSCORE. (The setting is slightly different though, related to "what is the acceptable probability for IoT?" which is likely going in one direction, and the use of AAD with the AEAD, which goes in the opposite direction.)

Did I understand the comment right, that another asymmetric EDHOC run after ~ 2^20 messages is not an issue?

About "additional code size in firmware updates": The mechanism we are talking about could be a derivation of a new master secret every  "key_derivation_rate" message. That would probably not have a huge impact in OSCORE code size. But it would be an update to OSCORE.

**Comment by chrysn** [comment]
At least not in terms of energy consumption. Even if an EDHOC exchange has 1000x the energy cost of a regular message, that's still only 0.1% in total change. (Admittedly that number is out of thin air, looking for better ones).

It may be an issue for devices that previously would have gotten away with being sure to never run out of sequence numbers but now can, though :-/

**Comment by marco-tiloca-sics** [comment]
Overall, this sounds like something better to do in OSCORE.

**Comment by gselander** [comment]
Done in CoRE. No comment on the key-update function so far, make a new issue if necessary.
