### ISSUE TITLE
Certificates - Review of Draft v12

### ISSUE THREAD

**Issue by stoprocent** [lake-wg/edhoc#203]
Hi

I have a few comments I would like to raise on `EDHOC` `v12` specification in regards to the certificates handling.
Let me start that we are planning to use `EDHOC` mainly with `x509` Certificates as Authentication Credentials so it's important for us to get this into the best possible state.

From the current version of the spec, we can read that if a single `x509` Certificate will be used for Authentication Credentials we should place it in `DER` format as `CBOR` `bstr` in `CRED_x`. Which makes sense ...
If we do this we should also provide `ID_CRED_x` with `x5t` `COSE` header (`COSE_CertHash`) with the value of certificate hash.

This is where the first problem occurs for me. Actually first two problems.

1. Draft defining `COSE` headers needed for `x509` is already expired. It was valid until June this year.
2. Even if we assume it's still valid I have a few problems with it:

`COSE_CertHash` `x5t` is according to: https://datatracker.ietf.org/doc/draft-ietf-cose-x509/08/

> (...) The second element is a binary string containing the hash value computed over the DER-encoded certificate.

This spec is a draft so the closest there is to RFC covering a similar area are `rfc7515` and `rfc7517`. I guess `COSE` was influenced by `JOSE` so it seems ok to assume some compatibility. 

RFCs I have mentioned are defining `x5t` a little bit different:

> The "x5t" (X.509 certificate SHA-1 thumbprint) Header Parameter is a
> base64url-encoded SHA-1 thumbprint (a.k.a. digest) of the DER
> encoding of the X.509 certificate [RFC5280] corresponding to the key
> used to digitally sign the JWS.  Note that certificate thumbprints
> are also sometimes known as certificate fingerprints.  Use of this
> Header Parameter is OPTIONAL.

In summary `x5t` in draft `COSE` spec is `HASH( DER(...,...,DIGEST) )` and in `JSON` related specs as `DER(...,...,DIGEST)`. 
I think they should be alined. There are many reasons for this one of which is interoperability etc.

If we think from a processing perspective to use a certificate to first validate it and extract the public key for message authentication needs, there is no extra overhead when parsing the certificate to extract its digest.

**I have edited this issue as yesterday I have wrongly interpreted `ID_CRED_x` and `CRED_x` roles in the certificate chain but I think one issue remains in terms of `draft-ietf-cose-x509` being expired.**

So to summarize I think:

1. We should take care of `draft-ietf-cose-x509` so it's valid and aligned with similar specs.
2. We should establish what is a certificate hash in detail.

Hope we can discuss this further.

**Comment by emanjon** [comment]
This seems like a COSE issue. Are there any clarifications needed in the EDHOC draft?

I don't understand what the difference between COSE and JOSE that you find problematic. In JOSE x5t is a base64 encoded SHA-1 hash. In COSE it is a struct with an algorithms and a hash made with that algorithm. The hash is a COSE bstr.

draft-ietf-cose-x509 is submitted for publication so it will be published soon. You don't need to worry that it is expired. There is ongoing discussion on GitHub. If you have any issues with the x509 draft there might still be possible to address them. You should comment on GitHub or mail the COSE WG email list.
https://github.com/cose-wg/X509
cose@ietf.org

> we should also provide ID_CRED_x with x5t
Should is a bit strong. You might use any of the COSE header parameters that identify a X.509 certificate. I.e. you may also use x5chain, x5bag, x5u.

**Comment by stoprocent** [comment]
@emanjon I believe if I understand this correctly that COSE and JOSE x5t is totally different. COSE x5t is the SHA of the entire certificate including a field containing a thumbprint. When JOSE thumbprint is a field value from x509 certificate.

**Comment by stoprocent** [comment]
@emanjon I think you are right on this that it's actually not needed for EDHOC spec clarification. I will close this
