### ISSUE TITLE
Shorten 3.5

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#212]
This issue is extracted from Stephen's review #202:

3.5.1, 3.5.2 and 3.5.3: this might be some text to
   shorten a lot - how much is it really needed? Could it be
cut down to the stuff with 2119 terms and a bit more? (I'd
keep the examples though.)

**Comment by emanjon** [comment]
Agree with Stephen that this is a candidate for shortening.

Related to #142. Do we need a new issue?

**Comment by gselander** [comment]
Section 3.5 is shortened with PR #240. Role of EDHOC clarified and non-EDHOC protocol things moved to new appendix D.
