### ISSUE TITLE
Verification of identities in X.509 and CWT

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#215]
From John's comment to changes following Marco's review:

"identities to verify the 'sub' (subject) claim of the CWT."

 Should use the same text for X509 and CWT.

Moreover,  "sub" claim is just an example. CWT might add e.g. AltSub in the future.

**Comment by emanjon** [comment]
If we change one of them we should change both. I think this issue is strongly related to #212 and could be fixed together.

**Comment by gselander** [comment]
With PR #240, it is now clear that verification of identity is the responsibility of the application. Therefore Appendix D just gives examples, where this text now reads: 

> When a Public Key Infrastructure (PKI) is used with certificates, the identity is the subject whose unique name, e.g., a domain name, a Network Access Identifier (NAI), or an Extended Unique Identifier (EUI), is included in the endpoint's certificate. Similarly, when a PKI is used with CWTs, each endpoint needs a specific identity or set of identities it is allowed to communicate with to match against the relevant claim, such as 'sub' (subject).

Is this good enough?
