### ISSUE TITLE
Ed25519 instead of EdDSA

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#218]
Comment from Loïc: 

https://mailarchive.ietf.org/arch/msg/lake/4ErIcI5oqQT0utmwbpdydQGOUVI/

> It seems that "EdDSA" is not the proper wording to use in the draft (at least in Section 9.2). I quote the original paper by Bernstein, Duif, Lange, Schwabe and Yang [1]: 
> - " This section specifies the signature system used in this paper, and a generalized signature system EdDSA that can be used with other choices of elliptic curves."
> - " Our recommended curve for EdDSA is a twisted Edwards curve birationally equivalent to the curve Curve25519 [...] We use the name Ed25519 for EdDSA with this particular choice of curve."
> Therefore "Ed25519" should be used in place of "EdDSA" (at least in Section 9.2). 
> 
> [1] High-speed high-security signature, Bernstein, Duif, Lange, Schwabe and Yang, 2011. https://protect2.fireeye.com/v1/url?k=31323334-501d5122-fe22d327-454445555731-1b801206d8bfce4f&q=1&e=371d7c78-5c57-49c2-8785-e20bf038bf86&u=https%3A%2F%2Fed25519.cr.yp.to%2Fed25519-20110926.pdf
>

**Comment by malishav** [comment]
let's just be careful that we are aligned with RFC 8152 definitions here.

**Comment by emanjon** [comment]
What [1] says it not particulary important. We only care the standadized versions which often are not equal to the original academic papers.

In this case we want to follow firstly COSE RFC 8152 and secondly RFC 8032. COSE calls the signature algorithm "EdDSA" so I think 9.2 is correct. All uses of "EdDSA" in the EDHOC draft refer to the generalized signature system EdDSA, so also according to [1], I do not see a problem either. 9.2 talks about the generalized signature system EdDSA used with the curves Ed25519 and Ed448 (following RFC 8152).

Do we need some more references to COSE. Some of the other reviewers asked about references to LMS. Should be clear in the EDHOC draft that basicaaly everything concerning algorithms and ID_CRED_x follows from COSE and than any details or futher references can be found there.

**Comment by emanjon** [comment]
I think the EDHOC document needs to be clearer that all terminology follows COSE and that all definitions is found in COSE. JOSE has strange naming that COSE has borrowed. And maybe COSE added some strange names on it own.

- The curve registry list X25519, X448, Ed25519, Ed448, as curves
  (the CFRG names are edwards25519 and Curve25519 etc.,)
- AES-128 is often called A128 
- ECDSA with SHA-256 is called ES256
- RSASSA-PSS with SHA-256 is called PS256
- RSASSA-PKCS1-v1_5 using SHA-256 is called RS256
- RSASSA-PKCS1-v1_5 using SHA-1 is called RS1
- HKDF-AES-128 ............

I genuinly hate a lot of these names. I get _many_ questions from people internally at my company from people asking about these weird names. They cause a lot of confusion and extra work for no apperent benefit.

However, I think EDHOC needs to follow COSE. We should just explain that better.

**Comment by emanjon** [comment]
Note that "EdDSA" in Section 9.2 is not even "Ed25519". The choice between Ed25519 and Ed448 depends on the authentication key as specified by COSE.

**Comment by gselander** [comment]
Closing this since #221 is now merged.
