### ISSUE TITLE
Feedback regarding test vectors

### ISSUE THREAD

**Issue by StefanHri** [lake-wg/edhoc#222]
I like a lot the JSON format for storing the test vectors. I noticed the following:

* In order for the file to be in correct JSON format, the strings `test_vector_x` should be in quotation marks, e.g. `"test_vector_1"` and not `test_vector_1`.

* The primary target platforms for EDHOC are constrained devices, i.e., microcontrollers. It will be very useful to provide the test vectors as a C header file, that can be used on microcontrollers without a file system. This will make automated testing on microcontrollers easier. I am writing myself a small python parser that converts the test vectors from JSON to C header. If there is an interest from other implementors I can contribute this script.

* When using suites 2 and 3 (ecdsa with P256) for every protocol run the signatures are different even if the signed message and signature key are the same (this is due to the nature of ecdsa [link]). This fact reduces the usability of the test vectors for automated testing for these suites. Still, the EDHOC input data (e.g. ID_CRED_x, CRED_x, etc) contained in the test vectors is useful but not all intermediary results and the end results. Probably it makes sense to document that along the test vectors.

[link]: https://crypto.stackexchange.com/questions/851/can-ecdsa-signatures-be-safely-made-deterministic

**Comment by emanjon** [comment]
Thanks Stefan,

That is excellent comments.
- The quotation marks should be fixed.
- Maybe we can also run the script on the final version of the test vectors and distribute the result together with JSON
- ECDSA test vectors should maybe use deterministic ECDSA.

**Comment by gselander** [comment]
Points 1 and 3 in John's comment above fixed. Add one more point from #257 to be able to close that.

* test vectors with prepended C_x

**Comment by StefanHri** [comment]
What is the final state regarding ECDSA test vectors? How EDHOC with ECDSA should be tested?
