### ISSUE TITLE
State diagram

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#224]
From Sean's review:

s5.1 (question): Is a state diagram needed? One thing people clamored for from TLS was a state machine. Maybe a diagram isn’t needed because there are so few states?

**Comment by emanjon** [comment]
Not sure it is needed in EDHOC. TLS has three distict states (early data, handshake, post handshake) and the key to use depend on the state irrespective of message type. EDHOC has none of that. A key derivation figure would maybe make more sense if we are to add anything.

**Comment by emanjon** [comment]
Suggestion by Goran to add a reference to an academic paper that has a figure with the key derivation

**Comment by gselander** [comment]
Perhaps sufficient to refer to figure 2?

**Comment by emanjon** [comment]
I don't have a strong preference, but fig 3 is used for message_4.

**Comment by emanjon** [comment]
But message_4 will likely not be used in most deployments, so maybe Fig 2 is enough.

**Comment by emanjon** [comment]
I think this can be closed after interim today, unless there are any more comments.
