### ISSUE TITLE
Inconsistent test vectors

### ISSUE THREAD

**Issue by malishav** [lake-wg/edhoc#227]
When generating the test vectors from `test-vectors-11/vectors.cpp` on my macOS Monterey, the output differs from the one that is in the Editor's version of `draft-ietf-lake-traces`. I compared the output of "OSCORE Master Secret (Raw Value)". In addition, the output differs from the one in json file ("vectors-json.txt").

I built the program on my Mac using the following command:
`g++ aes.c aes-ccm.c aes-enc.c vectors.cpp -lsodium -o vectors -std=c++17`

Libsodium is version 1.0.18_1, installed with homebrew.

**Comment by emanjon** [comment]
Good input.

Very likely the random number generation. Probably the use of seed only ensures consistant test vectors in the same environment.

We should move to an "PRNG" that does not depend on the environment.

**Comment by emanjon** [comment]
My implementation is now replaced by Marek's.
