### ISSUE TITLE
Not clear which test vectors are in draft-ietf-lake-traces

### ISSUE THREAD

**Issue by malishav** [lake-wg/edhoc#228]
When playing with the `vectors.cpp` application, I found it hard to relate the test vectors in `draft-ietf-lake-traces` and the ones generated by the program. The text in the draft should clearly state how and which test vectors are generated, and this should ideally be parametrized such that it is possible to generate:
* the test vectors present in the draft
* all supported vectors, with different verbosity levels

**Comment by emanjon** [comment]
Agree that the draft shouldl clearly state traces that is is a (small) subset of the JSON testvectors, and clearly point out which of them.

Marek had a related comment that the JSON test vectors should have a table on content explaining what each test vector contains.

**Comment by marco-tiloca-sics** [comment]
For producing the traces, I used my implementation available at:

https://github.com/rikard-sics/californium/tree/edhoc/cf-edhoc

The specific output was produced through the JUnit tests at:

https://github.com/rikard-sics/californium/blob/edhoc/cf-edhoc/src/test/java/org/eclipse/californium/edhoc/MessageProcessorTest.java

**Comment by emanjon** [comment]
Could we maybe a JSON version of the test vectors in the document. E.g. in an appendix?
