### ISSUE TITLE
Vectors.cpp app build is not cross-platform friendly

### ISSUE THREAD

**Issue by malishav** [lake-wg/edhoc#229]
It would be nice to include a README and a generic Unix-friendly Makefile that explains how to build the `vectors.cpp` application. The current build is Windows-only.

**Comment by emanjon** [comment]
I think Marek has already solve this. Have you looked at his code?

https://github.com/lake-wg/edhoc/issues/185

**Comment by gselander** [comment]
Link to the code:

https://github.com/stoprocent/edhoc/tree/feature/mbedtls/test-vectors-11

**Comment by emanjon** [comment]
My code is now considered obsolete. It has been replaced by Marek's test vector code.
