### ISSUE TITLE
Agreement/negotiation of parameters/options

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#23]
EDHOC has parameters/options that are set in different ways. Agreeing beforehand reduces flexibility. Negotiation might increase message sizes and roundtrips. Letting each party chose parameters in the protocol run allows an on-path attacker to block parameters that can be seen from the message size, and may affect availability as the parties may not support the same COSE options. 
 
Parameters agreed beforehand:
- Method (see #11)
- Transport and Correlation
- Use and format of AD_1, AD_2, AD_3
 
(If a parameter not agreed beforehand is received the protocol can be discontinued, see #11 )

Parameters negotiated/verified:
- Cipher suite
 
Chosen by each party (no current requirement and agreement beforehand):
- Raw public key OR certificate: CRED_R and CRED_I
- Type of credential identifier: ID_CRED_R and ID_CRED_I

Should agreement/negotiation of any of the parameters be changed?

**Comment by marco-tiloca-sics** [comment]
This current way looks good.

**Comment by mcr** [comment]
My suggestion is to add an appendix with some explanatory/example applicability text that collects all the things that need to be agreed beforehand.

**Comment by emanjon** [comment]
There seems to be WG consensus for the high level approach. An appendix has been added that summarized the informaiton. Any further comments on the specific content of the appendix should be filed as a new issue or PR.
