### ISSUE TITLE
Decision to use SHA-256/64 for I_CRED_R in draft-selander-lake-traces-02

### ISSUE THREAD

**Issue by mrdeep1** [lake-wg/edhoc#235]
[lake-traces 2.  Setup](https://www.ietf.org/archive/id/draft-selander-lake-traces-02.html#section-2) states
````
Both I and R are assumed to support cipher suite 0, which determines the algorithms:

EDHOC AEAD algorithm = AES-CCM-16-64-128
EDHOC hash algorithm = SHA-256
EDHOC MAC length in bytes (Static DH) = 8
EDHOC key exchange algorithm (ECDH curve) = X25519
EDHOC signature algorithm = EdDSA
Application AEAD algorithm = AES-CCM-16-64-128
Application hash algorithm = SHA-256
````
Then [lake-traces 4.2.  message_2](https://www.ietf.org/archive/id/draft-selander-lake-traces-02.html#section-4.2) has
````
CRED_R is identified by a 64-bit hash:

ID_CRED_R =
{
  34 : [-15, h'60780E9451BDC43C']
}
where the COSE header value 34 ('x5t') indicates a hash of an X.509 certficate, and the COSE algorithm -15 indicates
the hash algorithm SHA-256 truncated to 64 bits.
````
which is using -15 (SHA-256/64), not -16 (SHA-256) for the hash.

How was this decision arrived at?

**Comment by emanjon** [comment]
Thanks for the comment.

- The hash algorithm used in x5t is independent of the EDHOC cipher suite, that should probably be mentioned in the draft. I will make a PR with some text on this.

- I don't there was any discussion on this, but SHA-256/64 feels like a natural choice. As EDHOC integrity protects the whole certificate the length of the hash does not have any security relevance, the hash is just used to find the certificate, not to prove it is the correct one. Using SHA-256 would increase overhead with 24 bytes per message without any benefits. An implementation supporting SHA-256 can easily support SHA-256/64 (as it is just a truncated SHA-256).

**Comment by stoprocent** [comment]
@emanjon Than I need to run an update on test vectors for p256 as I have switched to SHA_256. I will make an update to use SHA_256/64 and pull request

**Comment by emanjon** [comment]
Yes, please do. Using SHA-256 in x5t is just a waste of 24 bytes in message_2 and message_3.

We should maybe give some recommendations in the draft regarding this, but I think it is hard to give normative requirements as x5t is just one example and future COSE header parameters and EAD might use cryptographic algorithms. The algortithms in X.509 in another example on algorithms not controlled by the cipher suite, Somebody might use a cert with a P-521 authentication key where the CA used RSA-PSS to sign the certificate together with cipher suite 2/3.

Maybe the draft should recommend the use of algorithms from the ciphersuite also in cose headers, EAD, X.509, CWT, etc. In the case of x5t the recommendation could be to use the same hash function but with as much truncation as possible.

**Comment by gselander** [comment]
Can we close this now?

**Comment by mrdeep1** [comment]
Works for me - thanks.
