### ISSUE TITLE
Forward and backward secrecy

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#24]
The currently best practice for IPsec is to do a new ECDHE every few hours or after a certain amount of data has been sent. Constrained IoT are not expected to run ECDHE every few hours, but can probably do better that today when many IoT deployments today use the same session key for 10 years. Perhaps every month or every year?

Frequent ECDHE achieves:
* An attacker having compromised R or I needs to be active to get the session key.
* An attacker gaining a session key can only use it for a limited period of time forward and backward in time.

Is rerunning EDHOC efficient enough?

Suggestion by Karthik on the list to PSK-FS by exchanging nonces without DHE and then hash with sequence numbers / previous state. This can likely be done much more efficient with an update to OSCORE, and should be considered in the context of #20.

Is there a need for an "intermediate" protocol component that provides both forward and backward secrecy but is more lightweight than the 3-pass PSK-ECDHE which was removed?

**Comment by chrysn** [comment]
In light of #20 we discussed running OSCORE B.2 during the hackathon. If it were to be used, it'd be good to have it more formalized, and include analysis of when it can run tacked on existing exchanges (possibly like B.1.2 can run without added roundtrips when the requested resource is safe).

The points there about amortization may be less applicable here as we're talking about time limits and not message limits. Still, it'd be good to get a sense for the orders of magnitude we're aiming for here. If this is done every other month and needs a single round-trip of 200 byte each in EDHOC, and firmware is updated once a year, then any mechanism added needs to fit within 2*200*6~=2KB to be worth it.

**Comment by chrysn** [comment]
It may help what kind of intermediate protocol component we're talking about here. My impression is that protocols that are static only come to LAKE to do the asymmetrical work, which is what gets them PFS. What would an intermediate protocol be other than LAKE with some preshared stuff?

**Comment by pbtgit** [comment]
I am also very interested in the balance of Appendix B.2 vs re-running EDHOC.

**Comment by gselander** [comment]
@chrysn @pbtgit 
As I see it the main question is how often it is needed to rekey for obtaining backward secrecy, i.e. secrecy of future sessions in the event of a temporary compromise enabling the use long term secrets. 

(The currently defined EDHOC methods or an addition to OSCORE (#20) can provide forward secrecy -- Appendix B.2 does not. The currently defined EDHOC methods or an additional CoAP Echo provides freshness.)

For backward secrecy a DH exchange is necessary, and appropriate use of the shared secret. This could potentially be a symmetric key authenticated two pass DH exchange with message sizes comparable to static DH, but computationally more lightweight.

**Comment by gselander** [comment]
* Discussed at LAKE interim Dec. 2020.
* Minutes: "Working assumption is either do full EDHOC exchange, or hash-based forward secrecy which requires no asymmetric operations. No formal ratcheting." 
* https://datatracker.ietf.org/doc/minutes-interim-2020-lake-04-202012181600/
* Version -03 and later defines an EDHOC-Rekey-...-FS() interface.

**Comment by gselander** [comment]
Working assumption seems to hold. No additional issues has been raised.
