### ISSUE TITLE
Update test vectors with new Exporter label

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#244]
PR #205, which is merged with master, changed Exporter labels for OSCORE:

https://github.com/lake-wg/edhoc/pull/205/commits/febb2bab

The test vectors need to be updated accordingly, to be able to submit a new version of -traces matching the next version of -edhoc.

(Att: @stoprocent @emanjon)

**Comment by stoprocent** [comment]
PR done.

**Comment by gselander** [comment]
Thanks, merged.
