### ISSUE TITLE
Need for resumption procedure?

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#25]
Resumption lets endpoints close connections and only store a small amount of state. Resumption can then be performed more efficiently than a full initial handshake, which is very useful on the web. IoT devices typically have a few long connections and the work of doing a resumption may be heavier that keeping the connection open. 

Resumption provides other benefits like re-keying and a new authentication which guarantees that messages are fresh. However, those things can be achieved much more efficiently with re-keying inside OSCORE (see #20) and the use of the CoAP Echo option (draft-ietf-core-echo-request-tag).

Is there any need for a resumption mechanism in EDHOC?

**Comment by pbtgit** [comment]
For EDHOC/OSCORE the case for re-keying seems stronger than the case for resumption. 
Or at least, the re-keying is a problem for OSCORE to solve rather than EDHOC.

**Comment by emanjon** [comment]
This has been borught up at the LAKE interim meetings without anybody expressing the wish for resumption.
