### ISSUE TITLE
Usage of Content-Format in CoAP when transferring EDHOC over CoAP

### ISSUE THREAD

**Issue by dnav** [lake-wg/edhoc#262]
As specified in section [A.3 Transferring EDHOC over CoAP](https://lake-wg.github.io/edhoc/draft-ietf-lake-edhoc.html#name-transferring-edhoc-over-coa), the payload in some CoAP messages can be an EDHOC message prepended by either a C_x identifier or "true". The draft states:

> The application/edhoc media type does not apply to these messages; their media type is unnamed.

However, the payload is actually a CBOR Sequence as defined by [RFC 8742](https://datatracker.ietf.org/doc/html/rfc8742). Thus, we could define and use a new media type "application/edhoc+cbor-seq".

Note that the usage of the Content-Format option is optional.

**Comment by gselander** [comment]
Makes sense to me. 

@cabo, @chrysn, others: Comments?

Good that you bring up the optionality of Content-Format, we should stress that in this text.

The discussion in Hackathon also reminded me about the common-option-compression which @chrysn presented in the May 12 interim 2021 - how to replace the Uri-Path: "/.well-known/edhoc" with a, say,  integer valued CoAP option.

**Comment by cabo** [comment]
Makes a lot of sense to me, too.
