### ISSUE TITLE
Strengthen the TEE implementation

### ISSUE THREAD

**Issue by charlie-j** [lake-wg/edhoc#270]
In method 0, the attacker must be able to compromise the long term authentication key to break the authentication of the protocol. In other terms, leaking the ephemeral share and the session key is not enough to break authentication, and does only break secrecy. This leads to a situation where it makes sense to protect the long term authentication key inside a TEE, as it strengthens authentication.

The issue is that in other methods, where an agent authenticates with a long term DH key, the attacker only needs access to ephemeral and session keys to impersonate an agent. In turn, this implies that using a TEE for the long term DH share does not currently have any meaningful impact on the security of the protocol.

In more detail, for instance in Method 2, the MAC key used to authenticate the initiator is actually the final session key. An attacker can thus by learning the ephemeral key and the session key of an initiator complete a Machine-In-The-Middle attack where the initiator believes to be talking to A while the attacker impersonated I to some Responder R.  We provide a the bottom of this issue a picture describing the attack on a simplified, abstracted LAKE-EDHOC execution for clarity.

Possible actions:
 * mention that method 0 is better suited for TEE implementations, and that other methods offer weaker authentication guarantees
 * update the protocol to allow DH authentication with a TEE, where the session key would not allow to recompute a MAC. The TEE interface would then contain both an export function to compute PRK_4x3m as well as a function that would return the full MAC. Two similar options could be considered:
     - Option 1) Add to the MAC payload the value G^IY. This option does not update the key derivation.
	 - Option 2) Distinguish the session key and the MAC key, with an additional inclusion of the G^IY value for the MAC key. 

## Impersonation attack without compromise of long term authentication key
On an abstracted edhoc protocol:
 ![image](https://user-images.githubusercontent.com/7815574/161232673-19b4aa2a-f478-40e9-8e01-cb60bc2d1312.png)

**Comment by gselander** [comment]
@charlie-j Thanks for presenting both problem and solution! 

Just for clarity (just reiterating text in #276): With PR #276  and by computing both the MAC and PRK_out inside a TEE, an attacker  with a leaked PRK_out would not be able to forge the MAC - thus strengthening the role of a TEE also for other methods than 0, right?

**Comment by gselander** [comment]
Just a note about this:

> using a TEE for the long-term DH share does not currently have any meaningful impact on the security of the protocol


We found this statement quite strong :-) 

If the session key leaks, then authentication in the application is broken. This is the same regardless of signature vs. static DH key protected in TEE. The long-term key in TEE continues to provide security in other instances of the protocol in which the session key does not leak. This is also the same regardless of signature vs static DH key protected in TEE. So there seems to be some cases where the use of a TEE has some impact on the security even for static DH methods, no? :-)

**Comment by gselander** [comment]
Another comment which may be beyond the protocol analysis is that the application of the Initiator in general may know what Responder public key it intends to authenticate. This may be a specific public key or public keys certified with a particular trust anchor. If pkA is not in the in the trusted set the Initiator is supposed to discontinue the protocol.

**Comment by charlie-j** [comment]
> Just for clarity (just reiterating text in https://github.com/lake-wg/edhoc/pull/276): With PR https://github.com/lake-wg/edhoc/pull/276 and by computing both the MAC and PRK_out inside a TEE, an attacker with a leaked PRK_out would not be able to forge the MAC - thus strengthening the role of a TEE also for other methods than 0, right?

Yes!

> We found this statement quite strong :-)

Sorry about that, it is indeed, we are always looking through the lens of our theoretical models, so it does distort a bit things^^ And as outlined by your point on the security of other instances of the protocol, it is actually a false statement. Coming up with a better sentence here would have been:
"In turn, this implies that using a TEE for the long term DH share does not currently have as strong as an impact as it could on the security of the protocol."

Just a side remark on your final point:
> If the session key leaks, then authentication in the application is broken. This is the same regardless of signature vs. static DH key protected in TEE. 

It kind of depends on what we call authentication in the application. For an application for which authentication is equal to "I have completed successfully an EDHOC exchange", and if such authentication should trigger a concrete action, then we have a difference.
Indeed, the core difference is that in method 0, both agents will be aware that they established an EDHOC session together, even though the authentication at the application level is broken. In other methods, this may not be the case, and there may be successful EDHOC sessions between agents that are not however of having communicated together.,

**Comment by charlie-j** [comment]
#276
