### ISSUE TITLE
Summarizing the the key derivation after the current suggested changes

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#278]
There has been a lot of suggestions and discussion regarding the key derivation latelely. Below is an attempt to summarize all the current suggstions that currently seems relatively likely to be done. This is not an issue in itself but I think it is good to have somewhere to discucess the complete changes to the key derivation. 

-----------------------------------

- Suggested to permute the order of element in the TH_2 sequence to be more resistant to any future collision attacks in hash functions. Exact order unclear but suggested to put the random and unpredictable G_Y first.
- Suggested to use PLAINTEXT instead of CIPHERTEXT in transcript hashes to simplify formal verification. Endpoints agree on that they received the same plaintext rather then the same cipertext.

```
TH_2 = H( G_Y, C_R, H(message_1) )
TH_3 = H( TH_2, PLAINTEXT_2 ) 
TH_4 = H( TH_3, PLAINTEXT_3 )
```

- Suggested to use a salt derived from PRK in Extract to avoid usign the PRK keys directly in both Extract and Expand

```
PRK_3e2m = Extract( SALT_2e,   G_RX )
PRK_3m   = Extract( SALT_3e2m, G_IY )
```

- Suggested to use unsigned integer instead of text string for label to save memory.

```
OKM = EDHOC-KDF( PRK, transcript_hash, label, context, length )
    = Expand( PRK, info, length )

   info = (
     transcript_hash : bstr,
     label : uint,
     context : bstr,
     length : uint,
   )
```

- Suggestion to add a final key derivation PRK_out and use that in the exporter. Note that the exporter would also have uint labels

```
EDHOC-Exporter( label, context, length ) = EDHOC-KDF( PRK_out, h'', label, context, length )
```

- Suggestion to base Key-Update on Expand instead of extract. The label would need IANA registration. hash_length is a new variable that the implementation needs to keep track of. Should considered whether using Exporter for KeyUpdate has any disadvantages.
- Suggested that more info on how an application protocol is supposed to use KeyUpdate and Exporter together is needed.

```
PRK_out = EDHOC-KeyUpdate( context ) = EDHOC-Exporter( 0, context, hash_length )
```

- The EDHOC internal key derivations (i.e., not using the Exporter) would then be something like below. The exact labels should be discussed. Note that that only some of the derivations actually need a label to avoid collision

```
context_2 = << ID_CRED_R, CRED_R, ? EAD_2 >>
context_3 = << ID_CRED_I, CRED_I, ? EAD_3 >>
```

```
SALT_2e     = EDHOC-KDF( PRK_2e,   TH_2, 0, h'',       hash_length )
KEYSTREAM_2 = EDHOC-KDF( PRK_2e,   TH_2, 1, h'',       plaintext_length )
MAC_2       = EDHOC-KDF( PRK_3e2m, TH_2, 0, context_2, mac_length_2 )
SALT_3e2m   = EDHOC-KDF( PRK_3e2m, TH_3, 0, h'',       hash_length )
K_3         = EDHOC-KDF( PRK_3e2m, TH_3, 1, h'',       key_length )
IV_3        = EDHOC-KDF( PRK_3e2m, TH_3, 2, h'',       iv_length )
MAC_3       = EDHOC-KDF( PRK_3m,   TH_3, 0, context_3, mac_length_3 )
PRK_out     = EDHOC-KDF( PRK_3m,   TH_4, 0, h'',       hash_length )

```

- Including KeyUpdate, the IANA registered exporter labels could be:

```
PRK_out       = EDHOC-KeyUpdate( context )
              = EDHOC-Exporter( 0, context, hash_length )
K_4           = EDHOC-Exporter( 1, h'', key_length )
IV_4          = EDHOC-Exporter( 2, h'', iv_length )
Master Secret = EDHOC-Exporter( 3, h'', oscore_key_length )
Master Salt   = EDHOC-Exporter( 4, h'', oscore_salt_length )
```

**Comment by emanjon** [comment]
```
SALT_2e     = EDHOC-KDF( PRK_2e,   TH_2, 0, h'',       hash_length )
KEYSTREAM_2 = EDHOC-KDF( PRK_2e,   TH_2, 1, h'',       plaintext_length )
MAC_2       = EDHOC-KDF( PRK_3e2m, TH_2, 0, context_2, mac_length )
SALT_3e2m   = EDHOC-KDF( PRK_3e2m, TH_3, 0, h'',       hash_length )
K_3         = EDHOC-KDF( PRK_3e2m, TH_3, 1, h'',       key_length )
IV_3        = EDHOC-KDF( PRK_3e2m, TH_3, 2, h'',       iv_length )
MAC_3       = EDHOC-KDF( PRK_3m,   TH_3, 0, context_3, mac_length )
PRK_out     = EDHOC-KDF( PRK_3m,   TH_4, 0, h'',       hash_length )
```

The labels was just to illustrate the fact that they don't need to be separate. I think it is still better to just use 0-7. That makes it very easy for the reader to see that there are no collisions.

**Comment by gselander** [comment]
@emanjon Was this a comment on my proposed names of salts, or a separate comment?

(I agree labels 0-7 is good.)

**Comment by emanjon** [comment]
> @emanjon Was this a comment on my proposed names of salts, or a separate comment?

It was a separate comments. Your suggestion for salt naming is fine with me. Some other non-technical naming things that a hidden in my summary above

- I think mac_length_2 and mac_length_3 should be replaces with a single mac_length. The current naming gives the idea that they are not the same.
- I think key_length should use different terms in the derivation of K_4 and OSCORE Master Secret. The current naming gives the idea that they are the same.
- I think the contexts in the MAC_2 and MAC_3 derivations should be given names.
- Should consider collection all the EDHOC-KDF derivations in a single place.

**Comment by gselander** [comment]
Editorial; should be:
K_4 = EDHOC-KDF( PRK_3m, TH_4, 1, h'', key_length )
IV_4 = EDHOC-KDF( PRK_3m, TH_4, 2, h'', iv_length )

or, if we want all KDF labels distinct:

K_4 = EDHOC-KDF( PRK_3m, TH_4, 8, h'', key_length )
IV_4 = EDHOC-KDF( PRK_3m, TH_4, 9, h'', iv_length )

Alternatively, application access to Exporter only allows uint with:

K_4 = EDHOC-Exporter( -1, h'', key_length )
IV_4 = EDHOC-Exporter( -2, h'', iv_length )

**Comment by gselander** [comment]
Trying to compile the suggestions. 

These have a PR:

* Suggested to permute the order of element in the TH_2 sequence …
    * #283

* Suggested to use PLAINTEXT instead of CIPHERTEXT in transcript hashes …
   *  #277

* Suggestion to add a final key derivation PRK_out and use that in the exporter
    * #276


The following needs to be addressed:

* Suggested to use a salt derived from PRK in Extract 
    * define salt
    * derive salt

* Suggested to use unsigned integer instead of text string for label to save memory

* suggestion to base Key-Update on Expand 

* consider whether using Exporter for KeyUpdate has any disadvantages.

* more info on how an application protocol is supposed to use KeyUpdate and Exporter together 

* distinguish key_length in K_3/K_4 and OSCORE Master Secret

* define contexts explicitly 
  
* table of KDF derivations

**Comment by gselander** [comment]
Trying to put things together. Let's call this variant A, part 1.

```
SALT_3e2m   = EDHOC-KDF( PRK_2e,   TH_2, 0, h'',       hash_length )
KEYSTREAM_2 = EDHOC-KDF( PRK_2e,   TH_2, 1, h'',       plaintext_length )
MAC_2       = EDHOC-KDF( PRK_3e2m, TH_2, 2, context_2, mac_length_2 )
SALT_4e3m   = EDHOC-KDF( PRK_3e2m, TH_3, 3, h'',       hash_length )
K_3         = EDHOC-KDF( PRK_3e2m, TH_3, 4, h'',       key_length )
IV_3        = EDHOC-KDF( PRK_3e2m, TH_3, 5, h'',       iv_length )
MAC_3       = EDHOC-KDF( PRK_4e3m, TH_3, 6, context_3, mac_length_3 )
PRK_out     = EDHOC-KDF( PRK_4e3m, TH_4, 7, h'',       hash_length )
K_4         = EDHOC-KDF( PRK_4e3m, TH_4, 8, h'',       key_length )
IV_4        = EDHOC-KDF( PRK_4e3m, TH_4, 9, h'',       iv_length )
```

where 
```
context_2  =  << ID_CRED_R, CRED_R, ? EAD_2 >>
context_3  =  << ID_CRED_I, CRED_I, ? EAD_3 >>
```

and

```
PRK_3e2m = Extract( SALT_3e2m, G_RX )
PRK_4e3m = Extract( SALT_4e3m, G_IY )
```

New salts to avoid double use of PRK, named by its use. Same construction for K_4/IV_4 as K_3/IV_3, motivating the renaming of _3m in #276 as _4e3m.

The label in the KDF, third argument, is an uint, all distinct for simplicity.

**Comment by gselander** [comment]
Variant A, part 2:

```
PRK_out     = EDHOC-KeyUpdate( context ) = 
            = EDHOC-KDF( PRK_out, h'00', 10, context, hash_length )

EDHOC-Exporter( label, context, length ) = 
            = EDHOC-KDF( PRK_out, h'01', label, context, length )

Master Secret = EDHOC-Exporter( 0, h'', oscore_key_length )
Master Salt   = EDHOC-Exporter( 1, h'', oscore_salt_length )
```

Distinct "transcript hash" in KeyUpdate and Exporter. Exporter does not give access to EDHOC internal keys. OSCORE key length separate from key_length. 

Comments please.

**Comment by gselander** [comment]
Variant C.2 (C.1 = A.1):

```
PRK_out     = EDHOC-KeyUpdate( context ) = 
            = EDHOC-KDF( PRK_out, h'00', 0, context, hash_length )

EDHOC-Exporter( label, length ) = 
            = EDHOC-KDF( PRK_out, h'01', label, h'', length )

Master Secret = EDHOC-Exporter( 0, oscore_key_length )
Master Salt   = EDHOC-Exporter( 1, oscore_salt_length )
```

Same as B.2 but with different labels. With variant C we have essentially:
* the internal KDF labels 0, ..., 9, and 
* the IANA EDHOC Exporter Registry with current content 0 and 1.

**Comment by gselander** [comment]
@marco-tiloca-sics @malishav @chrysn and all: Any implementation considerations or other comments on variant C above? We'll start with the PR(s) soon.

**Comment by emanjon** [comment]
The last posts here are confusing....  

>  Also, to be strict in labelling we could continue enumeration

I don't agree. These are separate. We should definitly not try to keep them separate. I.e. it should be

Master Secret = EDHOC-Exporter( 0, h'', oscore_key_length )
Master Salt   = EDHOC-Exporter( 1, h'', oscore_salt_length )

**Comment by emanjon** [comment]
```
info          = ( transcript_hash : bstr, label : uint, context : bstr, length : uint )

EDHOC-KDF( PRK, transcript_hash, label, context, length )
              = Expand( PRK, info, length )

TH_2          = H( G_Y, C_R, H(message_1) )
TH_3          = H( TH_2, PLAINTEXT_2 ) 
TH_4          = H( TH_3, PLAINTEXT_3 )

context_2     = << ID_CRED_R, CRED_R, ? EAD_2 >>
context_3     = << ID_CRED_I, CRED_I, ? EAD_3 >>

PRK_3e2m      = Extract( SALT_3e2m, G_RX )
PRK_4e3m      = Extract( SALT_4e3m, G_IY )

SALT_3e2m     = EDHOC-KDF( PRK_2e,   TH_2, 0, h'',       hash_length )
KEYSTREAM_2   = EDHOC-KDF( PRK_2e,   TH_2, 1, h'',       plaintext_length )
MAC_2         = EDHOC-KDF( PRK_3e2m, TH_2, 2, context_2, mac_length_2 )
SALT_4e3m     = EDHOC-KDF( PRK_3e2m, TH_3, 3, h'',       hash_length )
K_3           = EDHOC-KDF( PRK_3e2m, TH_3, 4, h'',       key_length )
IV_3          = EDHOC-KDF( PRK_3e2m, TH_3, 5, h'',       iv_length )
MAC_3         = EDHOC-KDF( PRK_4e3m, TH_3, 6, context_3, mac_length_3 )
PRK_out       = EDHOC-KDF( PRK_4e3m, TH_4, 7, h'',       hash_length )
K_4           = EDHOC-KDF( PRK_4e3m, TH_4, 8, h'',       key_length )
IV_4          = EDHOC-KDF( PRK_4e3m, TH_4, 9, h'',       iv_length )

PRK_out       = EDHOC-KeyUpdate( context ) = 
              = EDHOC-KDF( PRK_out, h'00', 10, context, hash_length )

EDHOC-Exporter( label, context, length )
              = EDHOC-KDF( PRK_out, h'01', label, context, length )

Master Secret = EDHOC-Exporter( 0, h'', oscore_key_length )
Master Salt   = EDHOC-Exporter( 1, h'', oscore_salt_length )
```

The above looks good to me with the following not so interesting options.
- order of the 0-9 labels
- use 10 or 0 label for Key-Update
- order of the h'00' and h'01' "transcripts"

**Comment by emanjon** [comment]
I think we should maybe merge the "context" and "transcript hash" inputs. This simplifies things and avoids using h'00' and h''01' as "transcript hashes.

```
info          = ( label : uint, context : bstr, length : uint )

EDHOC-KDF( PRK, label, context, length )
              = Expand( PRK, info, length )

TH_2          = H( G_Y, C_R, H(message_1) )
TH_3          = H( TH_2, PLAINTEXT_2 ) 
TH_4          = H( TH_3, PLAINTEXT_3 )

context_2     = << TH_2, ID_CRED_R, CRED_R, ? EAD_2 >>
context_3     = << TH_3, ID_CRED_I, CRED_I, ? EAD_3 >>

PRK_3e2m      = Extract( SALT_3e2m, G_RX )
PRK_4e3m      = Extract( SALT_4e3m, G_IY )

SALT_3e2m     = EDHOC-KDF( PRK_2e,   0, TH_2,       hash_length )
KEYSTREAM_2   = EDHOC-KDF( PRK_2e,   1, TH_2,       plaintext_length )
MAC_2         = EDHOC-KDF( PRK_3e2m, 2, context_2, mac_length_2 )
SALT_4e3m     = EDHOC-KDF( PRK_3e2m, 3, TH_3,       hash_length )
K_3           = EDHOC-KDF( PRK_3e2m, 4, TH_3,       key_length )
IV_3          = EDHOC-KDF( PRK_3e2m, 5, TH_3,       iv_length )
MAC_3         = EDHOC-KDF( PRK_4e3m, 6, context_3, mac_length_3 )
PRK_out       = EDHOC-KDF( PRK_4e3m, 7, TH_4,       hash_length )
K_4           = EDHOC-KDF( PRK_4e3m, 8, TH_4,       key_length )
IV_4          = EDHOC-KDF( PRK_4e3m, 9, TH_4,       iv_length )

PRK_out       = EDHOC-KeyUpdate( context ) = 
              = EDHOC-KDF( PRK_out, 10, << 0, context >>, hash_length )

EDHOC-Exporter( label, context, length )
              = EDHOC-KDF( PRK_out, label, << 1, context >>, length )

Master Secret = EDHOC-Exporter( 0, h'', oscore_key_length )
Master Salt   = EDHOC-Exporter( 1, h'', oscore_salt_length )
```

**Comment by emanjon** [comment]
Alternatively

```
info          = ( label : uint, context : bstr, length : uint )

EDHOC-KDF( PRK, label, context, length )
              = Expand( PRK, info, length )

TH_2          = H( G_Y, C_R, H(message_1) )
TH_3          = H( TH_2, PLAINTEXT_2 ) 
TH_4          = H( TH_3, PLAINTEXT_3 )

context_2     = << TH_2, ID_CRED_R, CRED_R, ? EAD_2 >>
context_3     = << TH_3, ID_CRED_I, CRED_I, ? EAD_3 >>

PRK_3e2m      = Extract( SALT_3e2m, G_RX )
PRK_4e3m      = Extract( SALT_4e3m, G_IY )

SALT_3e2m     = EDHOC-KDF( PRK_2e,   0, TH_2,       hash_length )
KEYSTREAM_2   = EDHOC-KDF( PRK_2e,   1, TH_2,       plaintext_length )
MAC_2         = EDHOC-KDF( PRK_3e2m, 2, context_2, mac_length_2 )
SALT_4e3m     = EDHOC-KDF( PRK_3e2m, 3, TH_3,       hash_length )
K_3           = EDHOC-KDF( PRK_3e2m, 4, TH_3,       key_length )
IV_3          = EDHOC-KDF( PRK_3e2m, 5, TH_3,       iv_length )
MAC_3         = EDHOC-KDF( PRK_4e3m, 6, context_3, mac_length_3 )
PRK_out       = EDHOC-KDF( PRK_4e3m, 7, TH_4,       hash_length )
K_4           = EDHOC-KDF( PRK_4e3m, 8, TH_4,       key_length )
IV_4          = EDHOC-KDF( PRK_4e3m, 9, TH_4,       iv_length )

PRK_out       = EDHOC-KeyUpdate( context ) = 
              = EDHOC-KDF( PRK_out, 10, context, hash_length )

PRK_exporter  = EDHOC-KDF( PRK_out, 11, h'', hash_length )

EDHOC-Exporter( label, context, length )
              = EDHOC-KDF( PRK_exporter, label, context, length )

Master Secret = EDHOC-Exporter( 0, h'', oscore_key_length )
Master Salt   = EDHOC-Exporter( 1, h'', oscore_salt_length )
```

**Comment by marco-tiloca-sics** [comment]
The latest version of the summary https://github.com/lake-wg/edhoc/issues/278#issuecomment-1110643708  looks good.

**Comment by gselander** [comment]
Overview of main changes needed:

Merge #276

Rename PRK_3m as PRK_4e3m

Section 4.1
update PRK_  definitions
move section PRK_out to 4.2

Section 4.2
Update EDHOC-KDF and info definition
Update derivations
Include derivations of salts and K_4 / IV_4
List EDHOC-KDF derivations with labels 0-9

Section 4.3
Update EDHOC-Exporter (use label 10 instead of 11)
Remove derivation of K_4 / IV_4

Section 4.4
Update EDHOC-KeyUpdate (use label 11 instead of 10)

Section 5.3.2
Define context_2

Section 5.4.2
Define context_3

Section 9.1
Update EDHOC Exporter labels

Appendix A.1
Update Master Secret/Salt derivation

**Comment by gselander** [comment]
Additional updates: 
* As noted in previous comment, a proposal to interchange labels 10 and 11 to enumerate labels in the order they appear in the specification. (Other proposal for assignment of integer labels is welcome.)

* Should we align / adapt definition of context_x and external_aad? Currently (for message_2 and similar for message_3):
   * external_aad = << TH_2, CRED_I, ? EAD_2 >>
   * context_2 = << TH_2, ID_CRED_R, CRED_R, ? EAD_2 >>

**Comment by gselander** [comment]
PRK_exporter is a key which we only introduce for simple distinction between different KDF applications. Perhaps an overkill? May open up for unnecessary discussion about properties of that key. Here is another variant:

```
PRK_out = EDHOC-KeyUpdate( context ) = 
              = EDHOC-KDF( PRK_out, 10, context, hash_length )

EDHOC-Exporter( label, context, length )
              = EDHOC-KDF( PRK_out, 11, << label, context >>, length )

Master Secret = EDHOC-Exporter( 0, h'', oscore_key_length )
Master Salt   = EDHOC-Exporter( 1, h'', oscore_salt_length )
```

**Comment by gselander** [comment]
Most old comments are now addressed, and there are quite a few changes, so it is a good time to merge PR #286. Remaining points:

* derivation of K_4/ IV_4 and text about key confirmation. Not clear if there is any difference in practice between K_4 /IV_4 being derived from PRK_4e3m or PRK_out, but the current text about explicit key confirmation is not valid in the former case. May alternatively tune down the key confirmation terminology.

* Suggested to make clearer distinction between key derivation for EDHOC processing, resulting in PRK_out, and key derivation for application, i.e. making use of PRK_out in EDHOC-Exporter and EDHOC-KeyUpdate. More guidance on the latter is also proposed.

**Comment by gselander** [comment]
Tried to address the remaining points in the previous comment with the latest two commits: 5d675ac  and  95e35bb.

More guidance on KeyUpdate may still be needed. 

Other points?

**Comment by gselander** [comment]
@emanjon What more guidance is needed on KeyUpdate?

**Comment by emanjon** [comment]
Was a request from someone. Might be hard to understand how to use it. E.g. that you should alternate key update and exporter

Exporter

Key Update
Exporter

Key Update
Exporter

...

**Comment by gselander** [comment]
Another guidance needed is how to manage overwrite of PRK_out pending confirmation of the derived key from the other endpoint. When the Initiator is updating PRK_out it needs both old and new derived keys to be able to communicate securely in lock-step the change to the new key.

**Comment by gselander** [comment]
Perhaps good to remark that the entire application contexts (including e.g. sequence numbers) need to be maintained before a transition is made.

**Comment by emanjon** [comment]
see #313 instead. The current discussion has very little to do with #310
