### ISSUE TITLE
Understanding "selected cipher suite"

### ISSUE THREAD

**Issue by StefanHri** [lake-wg/edhoc#28]
In message 1 a CBOR array containing the supported cipher suites is sent.
The document says "One of the supported cipher suites is selected." 
How is this indicated? Is the selected suite the first in the array? If so it may make sense to write something like:
"One of the supported cipher suites is selected. The selected suite is the first suite in the SUITES_I CBOR array"

**Comment by gselander** [comment]
See commit 1f853ac. 
@StefanHri Please close the issue after checking.

**Comment by StefanHri** [comment]
> See commit [1f853ac](https://github.com/lake-wg/edhoc/commit/1f853ac3dd5590ae1de2132c21812f4ef3807f18).
> @StefanHri Please close the issue after checking.

@gselander: I think that's the wrong commit link?

**Comment by gselander** [comment]
> > See commit [1f853ac](https://github.com/lake-wg/edhoc/commit/1f853ac3dd5590ae1de2132c21812f4ef3807f18).
> > @StefanHri Please close the issue after checking.
> 
> @gselander: I think that's the wrong commit link?

@StefanHri Right, sorry, should be 820fc1d
