### ISSUE TITLE
Clarify confidentiality of message_2

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#294]
> As described in SIGMA, different levels of identity protection are provided to the Initiator and the Responder. EDHOC protects the credential identifier of the Initiator against active attacks and the credential identifier of the Responder against passive attacks. An active attacker can get the credential identifier of the Responder by eavesdropping on the destination address used for transporting message_1 and send its own message_1 to the same address.

* EDHOC protects not only credential identifier against passive attacks
* EDHOC does not protect confidentiality of message_2 against active attacks

**Comment by charlie-j** [comment]
> EDHOC does not protect confidentiality of message_2 against active attacks.

Wait, that is a bit strong (unless there is an attack I am not aware of). The constant fields of message_2 can be obtained by an attacker sending its own DH share to the responder. But for a message_2 corresponding to some non compromised initiator DH share, the content of message_2, like the signature, should be confidential.

**Comment by gselander** [comment]
Maybe I didn't formulate the property well. I'm thinking about this: message_2 is disclosed to the owner of the private key X, and an active attacker can replace G_X in message_1 to read message_2.

**Comment by charlie-j** [comment]
Yeah, ok, the owner of the private key learns everything and also the signature, but only the owner of the private keys X learns  the corresponding message_2 essentially. 

It is just that stated as it was, it made it for me sound like if even for honest private keys X that the attacker does not know, it would be able to break the confidentiality of message_2.

**Comment by gselander** [comment]
Ok, good point, let's try to formulate this better then :-)

**Comment by emanjon** [comment]
Assuming an Alice sends

`message_1 = METHOD, SUITES_I, G_X, C_I, EAD_1
`
and do/would receive 

`message_2 = G_Y, ENC( PAD, ID_CRED_R, Signature_or_MAC_2, EAD_2 ), C_R`

An attacker can do a number of active attacks

1. An attacker can block message_1 and send a similar message_1 with a different source IP and different G_X.
Assuming that the Responder does not chose credentials based on IP, G_X, or randomly, the attacker would get an
almost equal message_2 (different G_Y, KEYSTREAM_2, and Signature_or_MAC_2)

2. An attacker can block message_2 and send a similar message_2 with a different ID_CRED_R. Using the information wether the Initiator sends message_3 the attacker gain info about ID_CRED_R. (note that the attacker might increase the size of ID_CRED_R)

3. An attacker can block message_2 and send a similar message_2 with a different ID_CRED_R. Leaks information about the length.

4. An attacker can block message_2 and send a similar message_2 with a different Signature_or_MAC_2. Using the information wether the Initiator sends message_3 the attacker gain info about Signature_or_MAC_2. This attack might not work for practically used MAC and Signature algortihms, but if S = SIG(PK, M) is a signature algorithm then S2 = (S, PK) = SIG(PK, M) is also a valid signature algorithm that is vulnerable to the attack.

I think **"EDHOC does not protect confidentiality of message_2 against active attacks"** is quite correct on a high level. You could mitigate attacks where the attacker modifies message_2 but that is quite useless given attack 1.

**Comment by emanjon** [comment]
I made a commit with a minor fix for the first bullet.
https://github.com/lake-wg/edhoc/commit/b43bc46555c854532ddc6436f5f7ca816b65f546

**Comment by emanjon** [comment]
Regarding bullet two "EDHOC does not protect confidentiality of message_2 against active attacks" we need some more discussion what to do. Based on the comments and discussions the last two weeks it might be good to do some clarification.

A first observation is that the confidentiality only apply to PLAINTEXT_2 and not the whole message.
`"EDHOC does not protect confidentiality of PLAINTEXT_2 against active attacks"`

Not sure we want to say this. It is a bit too much detail and a bit too high level. In addition to identity protection, the only property the reader might care about is the confidentiality of EAD_2. I suggest that in addition to the commit described above we augment the current text on EAD_2

"EAD_2 is encrypted but the Responder has not yet authenticated the Initiator."

to say that EDHOC only provides confidentiality of EAD_2 against passive attackers.

**Comment by emanjon** [comment]
I made a commit that gives more details on EAD_2 encryption.

NEW
`External authorization data sent in message_1 (EAD_1) or message_2 (EAD_2) should be considered unprotected by EDHOC, see {{unprot-data}}. EAD_2 is encrypted but the Responder has not yet authenticated the Initiator and the encryption does not provide confidentiality against active attacks.`

**Comment by emanjon** [comment]
I think these minor commits are enough and that this can be closed
