### ISSUE TITLE
Clarify authentication guarantees

### ISSUE THREAD

**Issue by charlie-j** [lake-wg/edhoc#296]
Maybe a forgotten change due to transcript computation update. In `Security considerations`, we currently read:
```
Compared to {{SIGMA}}, EDHOC adds an explicit method type and expands the message authentication coverage to additional elements such as algorithms, external authorization data, and previous messages.
```

Since the transcripts now contain the plaintexts and not anymore the messages, this may need to be amended. The authentication of the plaintexts now hold with strong confidence, but the authentication of the messages requires both strong security assumptions over the encryption functions as well as a completely unambiguous parsing/encoding/decoding of everything.

**Comment by emanjon** [comment]
Very clear that authentication does not cover the messages sent on the wire anymore. As this is in the security considerations I think it should be updated to be correct.

**Comment by gselander** [comment]
Is 19911ca good enough? Other proposal?

**Comment by charlie-j** [comment]
Some plural is missing on one of the word in 19911ca (messages?), otherwise LGTM

**Comment by gselander** [comment]
How about this:

NEW
EDHOC adds an explicit method type and expands the message authentication coverage to additional elements such as algorithms, external authorization data, and previous plaintext messages.
