### ISSUE TITLE
Using SHA-256, do we need larger message_2 than 8160 bytes?

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#303]
The current design of encryption of message_2 in EDHOC limits the size of the message to 8160 bytes when SHA-256 is used. Is that a problem?
 
message_2 consists of the fields
 
- G_Y
- ID_CRED_R 
- Signature_or_MAC_2
- C_R

and optional fields:
- ? PAD_2
- ? EAD_2

While these message fields could be very small, depending on use case, some may be arbitrarily large. The field ID_CRED_R would typically be a reference to an authentication credential, but may contain the credential itself, for example a certificate chain. EAD_2 is defined by the application so may a priori be large. One example is revocation information.

John: SHA-384 has the limit 12240  bytes and SHA-512 has the limit 16320 bytes. SHAKE128 and SHAKE256 have much much larger limits (2^2040 − 1 bits)

**Comment by gselander** [comment]
Some of the alternatives:

- Do nothing / this is not a problem
- Replace HKDF with HKDF', which allows larger length of output
- Use HKDF for message_2 size < 8160, HKDF' for larger message_2 
- Replace message_2 encryption with AES-CTR / ChaCha20
- Use KMAC instead of HKDF

**Comment by mcr** [comment]
It seems that this is a concern if/when G_Y or Signature_or_MAC_2 becomes one of the monstrous Post-Quantum algorithms, or a HSS.   I think that we should rule that out of scope,  say that when it happens that we'll do EDHOC2 based upon new constraints at the time.
 I think that 8K is probably enough for the certificate chain.  That's a *lot* (100) of 802.15.4 fragments.
So unless switching to HKDF' is really cheap, don't bother.

**Comment by gselander** [comment]
Thanks Michael. Yes, the assumption so far has been "this is not a problem". 

@All: It would be good to understand the impact on implementation if we would come to a different conclusion. Please comment, on the examples below.

1.  Replace HKDF with HKDF', which allows larger length of output

HKDF is constructed from HMAC using a counter which is 8 bits long. By defining HKDF' with 16 / 32 bits counter would make the output 2 MB / 137 GB (if I did the maths right) before the counter wraps. How is HKDF implemented today? Is it feasible to define your own variant, say with 32 bits counter? 

2.    Use HKDF for message_2 size < 8160, HKDF' for larger message_2

If this solution is applied, and only HKDF was mandatory to implement, then applications which stay below the limit would have minor impact. Yet it still allows support for all practical message_2 sizes at the cost of implementing HKDF' and the use of two KDFs. Is this an interesting option?

3.    Replace message_2 encryption with AES-CTR / ChaCha20

These are of course well known algorithm. Is AES-CTR available in libraries used, or would you need to implement it from AES? This introduces a dependence of ciphersuite, or the need to add another entry to the cipher suite for message_2 encryption algorithm.

4.  Use KMAC instead of HKDF

For KMAC, output length < 2^2040. But then we lost the case when there is no KMAC available.

5. Derive as many keystreams as needed to cover PLAINTEXT_2

Divide PLAINTEXT_2 in fixed size chunks (of 8160 bytes or similar) + last chunk. Introduce dependency on chunk number n = 0, 1, 2, 3, ... in one of the first three arguments of the keystream derivation:

> KEYSTREAM_2   = EDHOC-KDF( PRK_2e,   0, TH_2,      plaintext_length )

For example:
- PRK_2e(n) = Extract ( salt, IKM ) = HMAC-SHA-256( n, G_XY )

or

- replace 0 with negative labels:  -n for chunk n

or

- replace TH_2 with context = <<  n, TH_2 >>

**Comment by gselander** [comment]
PR #304 is included in -16
