### ISSUE TITLE
What message manipulations are detected and when

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#305]
Further security considerations about how message content is protected against manipulation. Perhaps something like this:

"Manipulations of message_1 may not be detected at reception since there is no MAC but, since message_1 is included in TH_2, if I and R disagree on message_1 then subsequent PRKs and MACs will be different.

Manipulations of other messages are detected at reception through the MACs, except for manipulation of the encrypted padding of message_2, since PAD_2 is not integrity protected."

**Comment by emanjon** [comment]
I made a PR for this #308

**Comment by emanjon** [comment]
I merged #308 to prepare for submission on -15. #308 is just a simple clarification.
