### ISSUE TITLE
Small mistakes and clarifications

### ISSUE THREAD

**Issue by StefanHri** [lake-wg/edhoc#31]
By reading the document I notices some small mistakes and a few things which can be explained better:

1) Section 5.1.1
```
...Figures 6 and 7 show
   examples of how the Responder can truncate SUITES_I and how SUITES_R
   is used by the Responder to give the Initiator...
```

I think it should be: 
```
...Figures 6 and 7 show
   examples of how the **Initiator** can truncate SUITES_I and how SUITES_R
   is used by the Responder to give the Initiator...
```
---

2) Section 5.1.1 bellow figure 6
I don't understand what you want to say with:

"...    As the Initiator's list of supported cipher suites and order of
   preference is fixed, and the Responder only accepts message_1 if the
   selected cipher suite is the first cipher suite in SUITES_I that the
   Responder supports, the parties can verify that the selected cipher
   suite is the most preferred (by the Initiator) cipher suite supported
   by both parties.  If the selected cipher suite is not the first
   cipher suite in SUITES_I that the Responder supports, the Responder
   will discontinue the protocol."
   
 It may make sense to paraphrase this part?  

--- 

3) Caption figure 7 and 8 
Now both figures have the same caption. It will be probably  better ->
Figure 7: Transferring EDHOC in CoAP where the initiator is a CoAP client
Figure 8: Transferring EDHOC in CoAP where the initiator is a CoAP server

---

4) Section 4.3 Encoding of bstr_identifier
What is the rationale for using int - 24? A short sentence like: 
"A bstr_identifier is a special encoding for byte strings, used hroughout the protocol. The reason for using bstr_identifier is ..."   
will be very helpful for me.

**Comment by gselander** [comment]
@StefanHri See 1c44106

**Comment by StefanHri** [comment]
I still don't understand:
"A bstr_identifier is a special encoding for byte strings, used throughout the protocol to encode short byte strings as int to save overhead since CBOR ints in the interval -24 to 23 can be encoded as one byte."

Let say we have a single-byte integer (int8_t) 120. 120-24 = 96. 96 is not in the interval -24 to 23 so we cannot encode it as CBOR int?

**Comment by gselander** [comment]
This applies to *byte strings* that can be encoded as CBOR ints of length one byte. I made another attempt, but perhaps it can be improved further, see 6e178c5.

**Comment by StefanHri** [comment]
I still don't understand that completely. Probably this is better:

A bstr_identifier is a special encoding for byte strings, used throughout the protocol to encode those short byte strings that can as CBOR integers. Such integers are in the interval -24 to 23. They are encoded in a single byte.

However, it is still not clear, why we need to calculate int - 24 ?

**Comment by gselander** [comment]
@StefanHri I tried to reformulate. Have a look at 733b590
