### ISSUE TITLE
Identifying a certificate with 'kid' by specified

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#32]
Currently the specification assumes that certificates are identified with x5t or x5u which are bigger than a kid can be. This limits the use of certificates compared to raw-public keys. If a raw public key in EDHOC can be identified with a kid, then a cert can as well. I would suggest to specify identification of cert with kid. This enables certificates to be used with as small messages as RPK. Making them usable in single message lorawan and 5-hop 6tisch

**Comment by gselander** [comment]
The missing component to use this needs to be defined in COSE. Work in progress in draft-mattsson-cose-cbor-cert-compress.
