### ISSUE TITLE
PRK notation

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#326]
With PR #325 the notation of PRKs is not very descriptive anymore. And even if we don't merge it there is room for simplification, for example: 

PRK_2 = PRK_2e
PRK_3 = PRK_3e2m
PRK_4 = PRK_4e3m

and harmonizing changes like

Salt_3 = Salt_3e2m
Salt_4 = Salt_4e3m

**Comment by emanjon** [comment]
I assume that if #325 is not merged, no change should be done, or? I.e., this issue depends on if #325 is approved.

**Comment by gselander** [comment]
No, it can make sense to simplify the names even if we don't do #325. Then again, if we don't merge #325, then the meaning of the names (e= enc, m= mac) still makes sense, but I don't know if anyone thinks about that. No biggie.

**Comment by emanjon** [comment]
The keys used to be named PRK_2, PRK_3, ... The reason for the current naming was that it was easy for a reader to assume that PRK_3 was the key used in message_3, which is not true. Can be discussed what the best naming is.

**Comment by gselander** [comment]
Closing this as agreed in the interim.
