### ISSUE TITLE
Difference betwen Test Vector 1 and Test Vector 2

### ISSUE THREAD

**Issue by manishamalik53** [lake-wg/edhoc#331]
What is the difference between the two test vectors - Vector 1 and Vector 2 in https://github.com/lake-wg/edhoc/blob/master/test-vectors-15/vectors-p256.txt?

Does the value of COSE header vary and thus the sizes of all the EDHOC messages?

**Comment by gselander** [comment]
@manishamalik53 The difference is in the identifier of the credential (ID_CRED_x):

* Test Vector 1 uses the COSE header x5t {34: [-15, ... ]}, i.e. a SHA-256 hash of an X.509 certificate truncated to 64-bits as identifier, so the certificate is just referenced.

* Test Vector 2 uses the COSE header x5bag {32: ... }, i.e. the actual certificate as identifier, so the certificate is transported.

Sorry for extremely slow response!
