### ISSUE TITLE
How to do encryption without integrity in message_2

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#34]
The current specification generates a long encryption key and perform XOR cipher.

As there are no non-AEAD algorithms in COSE, other options are a bit more complex.

- Remove the tag from AEAD ciphertext. Only works when AEAD has a well-defined tag.
- Ascociate a IND-CPA encryption algorithm with each AEAD. Requires a table.

AES-CCM -> AES
AES-GCM -> AES
ChaCha20-Poly1305 -> ChaCha20

**Comment by emanjon** [comment]
As the Responder sends its identity to an unauthenticated part, there is no need to have IND-CCA against active attackers. IND-CPA encryption is enough in this case. See full SIGMA paper for more information.

**Comment by emanjon** [comment]
Should we define the encryption to that it can be performed by removing the tag.

**Comment by emanjon** [comment]
Specifying an specific AES-CTR and ChaCha20 stream cipher mode makes it cumbersome for implementors....

EDHOC need to encrypt more data than DTLS 1.3 and cannot rely on AES-ECB and the ChaCha20 block cipher.

I think the right way to do this in a way easy for developers (which we want) is to just remove the tag....

If there would ever be a future COSE AEAD that does not have a well defined tag, it would be needed to define how encryption without integrity is done.

**Comment by emanjon** [comment]
Commit 6469cb8 changes the Table solution to a remove tag solution.

https://github.com/lake-wg/edhoc/commit/6469cb8dd1865eb19ad049c28b3781688fcb1aef

Looking at the changes give a good overview of the two solutions.

Having implemented both, I have a preference to just removing the tag from the COSE_Encrypt.

Using AES-CTR or ChaCha20 stream cipher requires far more work from the implementor. The developer would have to find the raw AES and ChaCha20 functions and make sure to implement the stream ciphers. This is doable but a bit complicated. We would like to keep implementation simple.

The solution with deriving a long key and XORing was simple but raised a lot of questions as XOR encryption has in the past been used in insecure ways (repeating a short key....). HMAC-SHA-256 on the other hand could very have higher security bounds than AES-128-CTR.

I think just removing the tag is the best overall solution. It works for all current and foreseeable AEAD in COSE. It is very easy to implement for the developer and it does not raise any questions like old HMAC-SHA-256+XOR solution

Would be good with other peoples opinion on this

**Comment by emanjon** [comment]
For -04 we are reverting back to -02. That seems like the easiest solution given that COSE does not support any IND-CPA encrytion algorithms (COSE itself does not need that). We do not want people to change their implementations unless we are sure that there will be a change.

Using HKDF as a binary additive stream cipher is perfectly secure, in fact it is a much better stream cipher than AES-CTR. The reason that AES-CTR is used is that something like HKDF-Expand is overkill security wise for simple encryption and much much slower that AES-CTR.

**Comment by emanjon** [comment]
much much slower is for long messages.... for very short messages is would actually be faster. For the short message_2 speed difference is negligible.

Another reasons HKDF-Expand is not typically used is that most application require both IND-CCA2 confidentiality as well as integrity protection. Both of which are given by an AEAD.

**Comment by gselander** [comment]
Fixed in -04?

**Comment by emanjon** [comment]
No objections or comments to the -04 version. -05 test vectors implement this
