### ISSUE TITLE
Session key terminology?

### ISSUE THREAD

**Issue by charlie-j** [lake-wg/edhoc#344]
Minor comment, but reading through all the security claims, they multiple times refer to the term `session key` (for instance in `compromise of a session key does not compromise past session keys.`), which is not per say completely defined. I am not even sure there is any ambiguity, but is it still worth adding somewhere that this relates to  `PRK_out`?

**Comment by emanjon** [comment]
Yes, I assume session key most often refer to PRK_out. Could maybe refer to the exported application keys in some sentence. Let's go through all instances and make it clear what it refers to.
