### ISSUE TITLE
Register ciphersuites with high security

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#35]
There has been interest to use EDHOC with high level security, i.e. AES-256 and 384 bit ECC.

Should we register a CNSA compliant cipher suite?
(A256GCM, SHA-384, P-384, ES384, P-384, A256GCM, SHA-384)

And/or something alternative?
(A256GCM, SHAKE256, X448, EdDSA, Ed448, A256GCM, SHAKE256)
(ChaCha20/Poly1305, SHAKE256, X448, EdDSA, Ed448, ChaCha20/Poly1305, SHAKE256)

The document should be more clear that it is possible to use EDHOC with any registered COSE algorithms by using a private number for the cipher suite.

**Comment by gselander** [comment]
I'm proxying input on two new proposed cipher suites:

Array: 11, 6, 2, -35, 2, 11, 6
Desc: AES-CCM-16-64-256, SHA-384, P-384, ES384, P-384, AES-CCM-16-64-256, SHA-384
 
Array: 13, 6, 2, -35, 2, 13, 6
Desc: AES-CCM-64-64-256, SHA-384, P-384, ES384, P-384, AES-CCM-64-64-256, SHA-384

**Comment by emanjon** [comment]
AES-CCM-16-64-256 and AES-CCM-64-64-256 are quite odd algorithms. Combining 256 bit keys with 64 bit tags is quite unbalanced. TLS WG has dicussed and decided to not standardize any more such algorithms.

People can already use them as private cipher suites, but I do not see that it is something that can be recommended in general. I think:

(A256GCM, SHA-384, P-384, ES384, P-384, A256GCM, SHA-384)
(ChaCha20/Poly1305, SHAKE256, X448, EdDSA, Ed448, ChaCha20/Poly1305, SHAKE256)

would be the reasonable high security cipher suites to register. The first of these which aligns with CNSA I think should be registered.

**Comment by lemikev** [comment]
Hi Emanjon.

I'm the one who asked for "AES-CCM-64-64-256, SHA-384, P-384, ES384, P-384, AES-CCM-64-64-256, SHA-384".
The goal was effectively to be CNSA aligned.
I agree with your comments and "A256GCM, SHA-384, P-384, ES384, P-384, A256GCM, SHA-384" is perfectly find for my needs.
To cover CNSA, it might be logical to also include "A128GCM, SHA-256, P-256, ES256, P-256, A128GCM, SHA-256".
Just a suggestion, I don't correctly have a need for it.

**Comment by emanjon** [comment]
We had a similar request some weeks ago, so I go ahead and make a commit for "A256GCM, SHA-384, P-384, ES384, P-384, A256GCM, SHA-384".

A128GCM, SHA-256, P-256, ES256, P-256, A128GCM, SHA-256" used to be in Suite B, but is no longer in CNSA. I Agree that it probably makes sense to add something between CNSA and Constrained CCM_8. I will bring up the question in an upcoming LAKE meeting. I think the algorithms used on state of the art web servers today is typically:
A128GCM, SHA-256, Curve25519, ES256, P-256, A128GCM, SHA-256

**Comment by emanjon** [comment]
I made a commit e3dc83b registering two more cipher suites. One aligning with CNSA and one aligning with current best practice for HTTPS (used e.g. by GitHub). I also added more information on the posibility of using private cipher suites.

**Comment by lemikev** [comment]
Thanks for this change. Please send advise if somebody else is implementing "A256GCM, SHA-384, P-384, ES384, P-384, A256GCM, SHA-384". I will be interested to interop with him.

**Comment by gselander** [comment]
Fixed in -03
