### ISSUE TITLE
Add references to various security analyses EDHOC has seen and their insights

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#350]
Given the various security analyses EDHOC has seen and their insights 
being discussed in Section 8, would it make sense to add informative 
references to those (as done, e.g., for TLS 1.3, RFC 8446 Appendix E)?

https://mailarchive.ietf.org/arch/msg/lake/3tVDWBtI-NdciJtq7Re7y8KwYq8/

**Comment by emanjon** [comment]
Seems like a good idea to me

**Comment by emanjon** [comment]
Related to #343

**Comment by gselander** [comment]
This was discussed on the IETF 116 LAKE WG meeting, and in absence of volunteers to draft such an appendix we decided to start with adding references.

We may want to go somewhere in between a whole appendix and a sentence, and expand with a paragraph about each reference. We still need someone to draft that paragraph for the different references and would like to conclude on this fairly soon. 

We start by merging #343 now.

**Comment by gselander** [comment]
Closing since #382 is merged.
