### ISSUE TITLE
Consider chancing sentence on when changes to Changes in message_1 and message_2 are detected.

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#351]
https://mailarchive.ietf.org/arch/msg/lake/Jwiuox0Nu46MhG14Qo-BLKx8ezM/

Hi all,

Following our previous analysis of the draft 12 and 14, we have now 
updated our models w.r.t. draft 17, making a full pass over both the 
protocol changes as well as the security considerations mentioned 
through out the draft.

Overall, there is a last security claim that is slightly wrong from a 
theoretical point of view, but in practice does not bear consequences. 
We detail it bellow. Otherwise, our automated analysis was not able to 
find any other weakness, so we hope that with respect to state of the 
art analysis techniques, the protocol is in a pretty good shape.

It concerns the following point, page 42:
     "Changes in message_1 and message_2 (except PAD_2) are detected 
when verifying Signature_or_MAC_2. "
This claim in fact dependson the security level of the signature scheme 
used. Assume that we have a signature scheme such that given 
"Sign(m,sk)", the signature of message m with secret key sk,  there 
exists a constant "c" such that "Sign(m,sk) XOR c" is also a valid 
signature for the same message m under sk. This is *not*a violation of 
the classical assumption over signatures (EUFCMA), and with such a 
signature scheme, an attacker could then change the content of 
message_2, by xoring the signature part with the constant c, and this 
change would not be detectedafter verifying the signature, and would 
only be caught on a message 4 or key confirmation.

This is only a theoretical attack, relying on the difference between the 
classical cryptographic assumption EUF-CMA, a signature authenticates 
only the underlying message, while underthe stronger SUF-CMAassumption, 
a signature authenticates both the underlying message and the signature 
itself.Noneof the concrete signature scheme currently standardized 
appears to bemalleable under xor. We report it for thoroughness, but are 
uncertain whether the sentence should be changedor not.

Best,
Charlie Jacomme, Elise Klein,Steve KremerandMaïwenn Racouchot.

**Comment by emanjon** [comment]
> and would only be caught on a message 4 or key confirmation.
I think this would be caught when verifying CIPHERTEXT_3

**Comment by charlie-j** [comment]
The PR looks fine to me! 

When mentioning message 4 or key confirmation, I was specifying when the change would be detected on the initiator side, but the responder would indeed detect it when verifying CIPHERTEXT_3.
