### ISSUE TITLE
Shepherd's review of the IANA Considerations section

### ISSUE THREAD

**Issue by malishav** [lake-wg/edhoc#374]
As part of my shepherding write-up, I had a closer look at the IANA considerations section.

- Section 9.5: EDHOC External Authorization Data Registry is not properly initialized and the text in the draft seems inconsistent. Section 9.5 requests the label be registered as a positive integer while section 3.8 mentions non-negative values for non-critical usage, and negative values of label for critical usage. ead_label of 0 for padding is not registered. 

Further, in the text of Section 3.8, the draft states:

> A security application using external authorization data needs to register a positive ead_label and optionally an associated ead_value format, for each EAD item it uses (see [Section 9.5](https://www.ietf.org/archive/id/draft-ietf-lake-edhoc-18.html#iana-ead)).

Please remove the notion of positive ead_label here, as it is expanded further down in the text.

- Just to confirm, the `info_label` for usage with EDHOC-KDF is an internal parameter and therefore does not need its own registry. Correct?

**Comment by gselander** [comment]
One commit intended to clarify.

Yes, info_label is only used within EDHOC.

**Comment by gselander** [comment]
Further update of this text in #378. 

@malishav Please have a look if this is fixed.

**Comment by gselander** [comment]
Closing this as no objection received.
