### ISSUE TITLE
Protected error, EDHOC-exporter, and responder processing of message_3

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#375]
See

After sending message_3 the Initiator can use the exporter. When the responder receives message_3 the message might parse perfectly and the responder can use the exporter. The responder might still not want to talk to the Initiator. In general it makes sense that the Responder can use the derived application keys to protect the EDHOC error message. This corresponds to protected alert messages in e.g., TLS.

As far as I can see -17 does not say anything about this. It propably should say a sentence or two about this.

Releted issues.
https://github.com/core-wg/oscore-edhoc/issues/8
https://github.com/lake-wg/edhoc/issues/372

**Comment by gselander** [comment]
Current processing of message_3:

> Verify Signature_or_MAC_3 using the algorithm in the selected cipher suite. The verification process depends on the method, see [Section 5.4.2]. Make the result of the verification available to the application.

> After verifying message_3, the Responder can compute PRK_out, see Section 4.1.3, derive application keys using the EDHOC-Exporter interface, see Section 4.2.1, persistently store the keying material, and send protected application data.

The application is in charge of using or not using the EDHOC session, this seems out of scope of EDHOC?

**Comment by emanjon** [comment]
```
* Make ID_CRED_R and (if present) EAD_2 available to the application for authentication- and EAD processing.

* Obtain the authentication credential (CRED_R) and the authentication key of R from the application (or by other means).

* Verify Signature_or_MAC_2 using the algorithm in the selected cipher suite. The verification process depends on the method, see [Section 5.3.2](https://datatracker.ietf.org/doc/html/draft-ietf-lake-edhoc#asym-msg2-proc). Make the result of the verification available to the application.

If any processing step fails, then the Initiator MUST send an EDHOC error message back as defined in [Section 6](https://datatracker.ietf.org/doc/html/draft-ietf-lake-edhoc#error), and the protocol MUST be discontinued.
```
Some thought on the processing

Do we want as strong focus on the the authentication credential is coming from the application? Maybe these would be improvements.

* Obtain the authentication credential (CRED_R) and the authentication key of R.
* Obtain the authentication credential (CRED_R) and the authentication key of R (from the application or by other means).

The current text is missing parts of the authentication step. Deciding on if you want to talk with the other party might include doing revocation checking, syncing time to verify the cert, or a human pressing yes or no. These things might happen after "Obtain the authentication credential (CRED_R) and the authentication key of R ". The EDHOC library might also find the key itself and then ask the application if it wants to continue.

The current specification does not fobid anything of this but also does not discuss it. The is more going on than the step `"Obtain the authentication credential (CRED_R) and the authentication key of R." ` Waitnig and answering with an EDHOC error is one alternative. Continuing and then letting the applicaion cancel the OSCORE connection is another alternative. Both should be allowed.

I think this needs some more discussion in the draft. It needs to be clear that  `"Obtain the authentication credential (CRED_R) and the authentication key of R." `is not necesarily the step where the application says ok to talking to the peer.

**Comment by gselander** [comment]
PR #375 is merged. Any remaining comment to address?

**Comment by chrysn** [comment]
You probably meant PR #398; looks done to me.

**Comment by gselander** [comment]
Yes I meant #398 is merged. Closing this now.
