### ISSUE TITLE
Why are RFC 7624 and RFC 8376 listed as normative references?

### ISSUE THREAD

**Issue by malishav** [lake-wg/edhoc#376]
Could these two references be listed as informative?

**Comment by gselander** [comment]
I-D nits additionally lists these:

  ** Downref: Normative reference to an Informational RFC: RFC 5869
  ** Downref: Normative reference to an Informational RFC: RFC 6090
  ** Downref: Normative reference to an Informational RFC: RFC 6979
  ** Downref: Normative reference to an Informational RFC: RFC 7748
  ** Downref: Normative reference to an Informational RFC: RFC 9053

**Comment by malishav** [comment]
From these above, all but RFC 9053 are in the downref registry [1]. I argued in my write-up that 9053 should be included in that registry, as well.

[1] https://datatracker.ietf.org/doc/downref

**Comment by gselander** [comment]
OK. So can we close this?

**Comment by malishav** [comment]
fine by me
