### ISSUE TITLE
Comment from Stephen about COSE headers

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#379]
From #377 

    section 5: As a non-implementer, I didn't understand the
    "MAY contain parameters" sentence there.

Do we need this normative statement?

**Comment by emanjon** [comment]
Let's reformulate that sentence. It is very unclear. It should probably say something about the recipient having to add parameters like alg before sending the singature or ciphertext to COSE.

**Comment by emanjon** [comment]
Missed that there was a change made already. The new text looks good to me.
