### ISSUE TITLE
Stephen's non-nits

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#380]
From #377 

non-nits:

    3.5.2, 2nd para: on what basis is rfc5280 a normative ref
    whilst [I-D.ietf-cose-cbor-encoded-cert] is informative?
    They seem to be equally required for implementation based
    on this text. Given [I-D.ietf-cose-x509] is normative,
    perhaps it wouldn't add delay if both were?

I made RFC 5820 informative.

    3.5.2: I forget if use of the full DER-encoded X.509 cert
    was discussed on the list or not? If not, the alternative
    would have been to use the SPKI which has some slightly
    different properties that can sometimes be beneficial
    (potentially easier use of different CAs on each side). I'm
    not asking for a change here btw, just to check was this
    discussed on the list. (I see appendix D.2 talks a bit
    about this.)

The use of (full DER-encoded) X.509 is described and planned to be used in deployments. I think Marek mentioned that in his presentation at IETF 113. Should be known. I don't think SPKI has been discussed. Any action you propose?

    5.2.3: what happens if the decode of message_1 fails?
    (Say due to an unknown suite.) Does EAD_1 get provided to
    the application? I hope not! Maybe the text after the
    bullets needs to specify this explicitly? Same for other
    sections wrt providing EAD to the application (esp EAD_1
    and EAD_2).

The current text says:
> The Responder SHALL process message_1 as follows:
>
> * Decode message_1 (see [Appendix C.1]
> * Verify that the selected cipher suite is supported and that no prior cipher suite in SUITES_I is supported.
> * If EAD_1 is present then make it available to the application for EAD processing.
>
> If any processing step fails, then the Responder MUST send an EDHOC error message back as defined in [Section 6], and the protocol MUST be discontinued.

The intent here and all other message processing is that you carry out the processing in steps and if any step fail then you don't carry out the subsequent steps. Is that clear enough? Then that would cover the case of unknown suite. But perhaps it doesn't cover other errors occuring at reception of message_1.

Does the state machine #373 make this more clear (though just an example)? Should we move some of that text here?

    9.4: As the method field is how we handle breaking
    changes, do we really want that registry to be
    specification required? The alternative might be standards
    action, if we prefer the IESG to be involved in such
    changes.

This has been discussed. One option is to require standards action for low method numbers. Anyone else has an opinion?

**Comment by sftcd** [comment]
> I made RFC 5820 informative.

Hmm - is that the right plan? If they're all informative references that'd imply that the CRED_I/R handling code (whether x.509, cbor or whatever) wasn't really part of an edhoc implementation. Is/should one of 'em be mandatory to implement (and hence normative)?

**Comment by sftcd** [comment]
> The use of (full DER-encoded) X.509 is described and planned to be used in deployments. I think Marek mentioned that in his presentation at IETF 113. Should be known. I don't think SPKI has been discussed. Any action you propose?

Only action I'm proposing is checking we're ok with that as I don't recall it being discussed on the list. On the basis that it's been in the draft for >1 year and implementers haven't complained and it's been raised on the list (in my recent review), I think we're good as-is (unless someone yells).

**Comment by sftcd** [comment]
> The intent here and all other message processing is that you carry out the processing in steps and if any step fail then you don't carry out the subsequent steps. Is that clear enough?

I'm not sure it's clear enough - esp wrt passing on EAD which can have side-effects that could be bad (e.g. if some identifier were stored even though message processing had failed for some reason). I think the EAD stuff is the only way that kind of thing might happen - if so, then maybe saying that EAD should only be passed to applications after all processing steps have succeeded might be right?

**Comment by sftcd** [comment]
> One option is to require standards action for low method numbers. Anyone else has an opinion?

To be clear - I'm fine with it as-is, but just wanted to check. As it's been raised on the list, people there can express their opinions as they wish so I don't see a need to specifically survey opinions further.

**Comment by gselander** [comment]
>> I made RFC 5820 informative.
>
> Hmm - is that the right plan? If they're all informative references that'd imply that the CRED_I/R handling code (whether x.509, cbor or whatever) wasn't really part of an edhoc implementation. Is/should one of 'em be mandatory to implement (and hence normative)?

Hmm - certs and RPK are quite different cases. It is not clear why mandate one if some only use the other. If something must to be mandated, I would say it is the use of CCS identified with a kid, i.e. RPK, not certs. Should we mandate this?

**Comment by sftcd** [comment]
To be honest, I'd have to re-read the draft to be sure, but I thought raw public keys were in practice mandatory:-) If all the implementations do support those (which I guess is the case), then it'd probably be no harm to explicitly say that's mandatory to implement maybe, if that's not already there somewhere.

**Comment by gselander** [comment]
No credential or identification of credential is mandatory currently.

**Comment by sftcd** [comment]
ok so I guess if they're all optional to implement then yes having them be informative references is defensible - it might come up in later reviews I guess but can be dealt with then if needed. Might be no harm if you can summarise that as the response to that comment on the list (though maybe wait a bit to see if someone else chimes in here)

**Comment by emanjon** [comment]
The use of (full DER-encoded) X.509 has been included since -00. Actually even draft-selander-lake-edhoc-00. I think the use of 'x5t' (which is full DER-encoded X.509) has been discussed quite a lot.

**Comment by emanjon** [comment]
> One option is to require standards action for low method numbers.
I would personally prefer that...

**Comment by gselander** [comment]
PR #383 is merged. Separate issue #385 opened for the remaining comment. Closing this.
