### ISSUE TITLE
Mention that EDHOC is  self-describing

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#404]
We should mention somewhere that EDHOC is self-describing in the meaning that the length and type of all field are described by the messages themselves (and the EDHOC specification). This is different from how cTLS is designed where you need a compresiion template to be able to decode the messages. The application profile in EDHOC is very different.

**Comment by emanjon** [comment]
Some parameters can be negotiated through the
   protocol execution (specifically, cipher suite, see Section 3.6) but
   other parameters are only communicated and may not be negotiated
   (e.g., which authentication method is used, see Section 3.2).  Yet
   other parameters need to be known out-of-band. 
   
   
   @gselander what are "Yet other parameters need to be known out-of-band. " ?

**Comment by gselander** [comment]
The use of message_4 is not conveyed except if it appears.

**Comment by gselander** [comment]
With PR #409 and d2ccf17 this is issue is addressed.
