### ISSUE TITLE
Defining a new IANA Registry for EDHOC application profiles

### ISSUE THREAD

**Issue by rikard-sics** [lake-wg/edhoc#405]
It can be a good idea for the EDHOC draft (or coming documents in LAKE or even elsewhere) to define a new registry for EDHOC application profiles. This can be useful for instance for the web linking that is being defined in the draft [Using EDHOC with CoAP and OSCORE](https://datatracker.ietf.org/doc/html/draft-ietf-core-oscore-edhoc-07) to describe an EDHOC resource together with a new target attribute “ed-prof”.

This was previously raised and discussed in the [CoRE interim meeting on March 1st](https://datatracker.ietf.org/meeting/interim-2023-core-04/session/core), and again in the [CoRE session during IETF 116](https://datatracker.ietf.org/meeting/116/session/core). Originally this topic was triggered by feedback from Christian Amsüss on the CoRE mailing list [here](https://mailarchive.ietf.org/arch/msg/core/Rs9EMsszA-QzRue7QJDIZN280WU/) (see the paragraph starting with "EDHOC treats application profiles").

A proposed format can look as the following:
`(Name | Description | Reference)`

At the same time the EDHOC draft could then also register the first application profile in this new registry. The Appendix F of the EDHOC draft can be used to define an application profile to be registered, instead of a simply being an example. Also this point was triggered by a comment in the review from Christian linked above.

**Comment by emanjon** [comment]
I think this is a good idea but I think it is a bit late in the process to add to the EDHOC document itself. This likely leads to a lot of discussion and do not really need to be done in the EDHOC document. Adding it to the EDHOC specification could delay publication.

As "Using EDHOC with CoAP and OSCORE" is also late in the publication process, maybe a separate draft is best? The new document could be in LAKE or CORE.

**Comment by marco-tiloca-sics** [comment]
I agree with @emanjon - I think the best option is a separate, new documet in LAKE. That can define the registry, the target attribute "ed-prof" for web-linking mentioned in the first comment, and hopefully a well-known application profile to be registered as first entry.

**Comment by rikard-sics** [comment]
Makes sense for me also to do this in separate document.
