### ISSUE TITLE
Nit: Redundant sentence

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#408]
5.4.2. Initiator Processing of Message 3

"Compute the transcript hash TH_4 =  ...
Note that TH_4 can be computed and cached already in the processing of message_3."

Why is the last sentence needed?

Edit: Looks like copy-paste inheritance from the analogue text about TH_3 and message_2, which is needed since  that text is the section about processing of message_3.

**Comment by gselander** [comment]
ce6e38d2

**Comment by emanjon** [comment]
Agree
