### ISSUE TITLE
Compliance with new ERR_CODE 3

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#414]
When we introduced the new error code 3 "Unknown credential referenced" we didn't take an active decision on compliance. Current text says:

"Error codes (ERR_CODE) 1 and 2 MUST be supported."

Any reason why not mandatory to also support 3?

**Comment by gselander** [comment]
Marco pointed out that mandatory support for ERR_CODE 3 may be interpreted as mandatory support for credential identifiers for both reference and value of credential. Which is undesirable in use cases which never transports the credentials. For this reason it may be good to not mandate support for this error code, i.e., leave the compliance requirements as they are and change nothing.

Other thoughts?

**Comment by emanjon** [comment]
>leave the compliance requirements as they are and change nothing.
Sounds good to me
