### ISSUE TITLE
Redundant Responder private key

### ISSUE THREAD

**Issue by TimothyClaeys** [lake-wg/edhoc#43]
The following test vector:

https://github.com/lake-wg/edhoc/blob/c73dc6affe2d7a47fa8eac97be4d4bbd8bd7c667/test-vectors/vectors.txt#L704

Seems to have a redundant Responder private authentication key listed.

https://github.com/lake-wg/edhoc/blob/c73dc6affe2d7a47fa8eac97be4d4bbd8bd7c667/test-vectors/vectors.txt#L766

The test vector computes the correct values using the private key:

https://github.com/lake-wg/edhoc/blob/c73dc6affe2d7a47fa8eac97be4d4bbd8bd7c667/test-vectors/vectors.txt#L770

**Comment by TimothyClaeys** [comment]
The redundant private key does **NOT** seem to match the missing key in issue https://github.com/lake-wg/edhoc/issues/42#issue-766198221.

**Comment by fpalombini** [comment]
This seemed to be a copy-paste typo in the test vectors code (now should be fixed a09570b4fe83c3 ). 
Keeping open because we still need to fix the test vectors (vectors.txt) and in the draft.

**Comment by emanjon** [comment]
Fixed with test vectors -05
