### ISSUE TITLE
Clarify calculation of CIPHERTEXT_2 

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#431]
https://mailarchive.ietf.org/arch/msg/lake/Ojx69lyUx5ZfqE2zFcaKMARBnbM/

Comment by Lei YAN

I am confused about how the  CIPHERTEXT_2 is calculated.
In Section 5.3.2 of draft-ietf-lake-edhoc-20, I found there are 2 sentences that contradict each other.
¡° * CIPHERTEXT_2 is calculated by using the EDHOC_Expand function as a binary additive stream cipher over the following plaintext:
- PLAINTEXT_2 =...
...
- CIPHERTEXT_2 = PLAINTEXT_2 XOR KEYSTREAM_2¡±
Is the calculation of the CIPHERTEXT_2 using the EDHOC_Expand function or just making the XOR operation?

**Comment by gselander** [comment]
I include this in the revised I-D since it is such a minor change.
