### ISSUE TITLE
Traces: Joel Halpern Gen-ART review

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#444]
Summary: This document is technically ready, but has what appears to me to be a
significant procedural error that should be fixed before resolving publication.

Major issues:
    The draft lists [I-D.ietf-lake-edhoc] as an informative reference.  As that
    is the definition of the protocol for which this is providing traces, this
    appears to be meaningless without that, and thus [I-D.ietf-lake-edhoc]
    should be a normative reference.

**Comment by gselander** [comment]
Fixed with #445
