### ISSUE TITLE
INTDIR Review by Donald E. Eastlake 3rd 

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#447]
The following is an issue I found with this document that SHOULD be
corrected before publication:

Section 5, must->MUST

The following are minor issues (typos, misspelling, minor text
improvements) with the document:

CWT should be expanded on first use.

In certificates, the hex values of successive octets are separated by
colon whereas elsewhere, when they are separated, they are separated
by spaces. Seems better to be consistent.

**Comment by gselander** [comment]
I thought the comments were straightforward and just fixed them. If anyone disagrees we can reopen the issue.
