### ISSUE TITLE
Traces: IESG Roman Danyliw comments

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#448]
Thank you for writing this document.  I am confident that it will help future implementers.

I did not personally verify the encodings.

** Section 1.1
   The traces in this draft are valid for version -22 of
   [[I-D.ietf-lake-edhoc](https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/)].  The traces has been verified by two
   independent implementations.

I appreciate the precision of this statement.  In the long term, shouldn’t these traces be valid for whatever RFC this EDHOC becomes.  Recommend providing instructions to the RFC Editor to replace [[I-D.ietf-lake-edhoc](https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/)] with the yet-to-be-assigned RFC number.

**Comment by gselander** [comment]
Close as completed.
