### ISSUE TITLE
Test vectors additions

### ISSUE THREAD

**Issue by fpalombini** [lake-wg/edhoc#47]
as requested from interop:

- [x] obsolete PSK test vectors
- [x] add TH4 output
- [x] add exporter, exporter outputs, keyupdate, to all test vectors
- [x] add KEYSTREAM_2
- [x] print out public keys.
- [x] Add error message
- [x] Add message_4
- [x] Add ead
- [x] Update test vectors to -10
- [x] Add JSON format
- [x] add real certificates to test vectors - 0:CBOR native and DER (and possibly later 1:ASN.1 translated)
- [x] Add ciphersuites 2 and 3 to test vectors, ECDSA keys should print out full y coordinate

**Comment by TimothyClaeys** [comment]
It would also be useful to have a test vector that has additional data attached to the exchange. Depending on the message, this data is also protected so a test vector would allow an implementation to verify if the protection of the additional data is done properly.

**Comment by fpalombini** [comment]
Thanks @TimothyClaeys, good point!

**Comment by emanjon** [comment]
I have updated the list. The new test vectors add ead, error messages, and message_4 and aligns with -10.

I have not added real certificates yet. But I made them a sequence 00 01 02 03 ...  to make it easy to see they are not real. The old one were random strings and several people tried to parse them

**Comment by emanjon** [comment]
I thinking about adding the error message to actual flows where the error message might come after any of normal  EHODC messages.

after message_1 : ERR_CODE 1 or 2
after message_2 : ERR_CODE 1
after message_3 : ERR_CODE 0 or 1
after message_3 : ERR_CODE 0 or 1

**Comment by emanjon** [comment]
I added the two additional test vectors with a SDH key in a x509 and a signature key in a UCCS.

**Comment by emanjon** [comment]
I uploaded preliminary -11 test vectors base on the current master. The two changes that affect test vectors are
-  Changed several of the KDF and Exporter labels  
-  Replaced edhoc_aead_id with selected_suite

**Comment by gselander** [comment]
While there is still a need for documentation of the test vectors (#187), there are now test vectors with cipher suite 2 (no major difference with 3) and test vectors which uses real certificates. Both are included in the -traces draft. Therefore I think we can close this issue.

**Comment by gselander** [comment]
Closing this as there have been no comments.
