### ISSUE TITLE
Add cipher suite with Wei25519

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#50]

**Comment by emanjon** [comment]
Will be done when IANA registrations are done

**Comment by emanjon** [comment]
Should we close this? The draft does not seem to progress. I have made a commit to master with the equations on how to transform curve25519 and edward25519 to Weirstraß format to enable acceleration on exisitng HW, these equiations are very useful.

Part of the interest in Wei25519 seems to have been based on misunderstanding and the actual interest was in the now referenced equations.

A Wei25519 cipher suite can easily be registered later if there is interest.

**Comment by gselander** [comment]
Closing this as agreed in the interim.
