### ISSUE TITLE
Clarify decryption of CIPHERTEXT_2

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#52]
In the latest version -03, Section 5.3.3 says:

"Decrypt CIPHERTEXT_2 by computing an outer COSE_Encrypt0 as defined in see Section 5.3.2 and XORing CIPHERTEXT_2 with the 'ciphertext' of the outer COSE_Encrypt0 with the tag removed."

Could you clarify this process and elaborate on its steps?

Also, is this actually involving a XORing? That seems being left here from the previous process in version -02 based on a keystream.

**Comment by emanjon** [comment]
Note that the operation to encrypt message_2 is not determined yet. We are awaiting developer feedback if the -02 or -03 way of doing things are the best way from a development perspective.

Could you clarify what is missing or unclear in the -03 description? The -03 description seems correct to me. XOR is needed in more or less all modern encryption.

(Feedback that AES-CTR and ChaCha20 stream cipher without Poly1305 is the right way is also ok of course. I found that alternative way to complex to implement).

**Comment by marco-tiloca-sics** [comment]
Trying to rewrite that sentence as steps, I read it as:

1. Fill an Encrypt0 object like the one in Section 5.3.2 and encrypt it.

2. Take the resulting 'ciphertext' of the processed object and remove the tag.

3. Take the output of step 2 and XOR it with CIPHERTEXT_2 from Message_2.

The result of step 3 is the plaintext with ID_CRED_R, Signature_or_MAC_2 and possibly AD_2.


Is this the intended workflow? If so, what is used as plaintext P in step 1?

**Comment by emanjon** [comment]
Yes, that is the intended workflow.

The value of P is clearly missing, P needs to be set to a byte string of zeroes of the same length as the intitial byte string, which the reciever would need to calculate as the length of the ciphertext minus the length of the tag. This is clearly missing from the text. 

Thanks.

**Comment by emanjon** [comment]
Maybe this removing tag is a bit more complex that I first thought. It actually requires two things from the AEAD. That is has a well-defined tag and that the encryption is done with a synchronous xor based stream cipher. Both of these happen to be true for all the currently defined AEAD algs.

Might very well be that we should for the -02 version if that is easier. I think that solution fine if we reformulate it that we are using HMAC-SHA256 as a stream cipher to generate keystream. The reason nobody does that is that HMAC-SHA256 is overkill security wise and are slow.

Another alternative would be to use AES-CTR but then I think that should not be left to the developers and instead registered as an algorithm in COSE.

**Comment by emanjon** [comment]
Or rather we are using HKDF-Expand as a stream cipher to generate key stream

**Comment by gselander** [comment]
Reverted to -02, rephrased as binary stream cipher, see:

e2912c9
cd5fdb5
d5ac597
c95a3d2

**Comment by marco-tiloca-sics** [comment]
Thanks for this. Note that:

* The notation in Figure 3 is still using K_2e for message_2.

* In Section 4, below the CBOR encoding of 'info':

--- K_2e is still mentioned in the first bullet point.

--- The label "K_2e" is still in the list of possible labels, in the third bullet point.

While still making it clear that the plaintext for message_2 is XORed with a keystream, keeping the original name K_2e may help readability (think also of Figure 3).

Also, keeping the label "K_2e" would preserve the current values in the test vectors.

**Comment by gselander** [comment]
Fixed in -04?

**Comment by marco-tiloca-sics** [comment]
Yes, I think it's fixed.
