### ISSUE TITLE
Rename EDHOC-Exporter-FS

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#56]
The name gives the impression that it is exporting something, but the function does not return anything.

**Comment by gselander** [comment]
First attempt: EDHOC-Rekey-Exporter-FS  (see 2f6ecec).

Other proposals: 
* EDHOC-Rekey-FS()
* EDHOC-Rekey()

**Comment by gselander** [comment]
Reopened due to further comments on the name in EDHOC-04: "EDHOC-Rekey-FS()"

John: The term "key update" (also used by TLS 1.3) is more appropriate than "rekey". 
Göran: The notation "FS" as in forward secrecy is an intended property but should not be part of the function name.

New proposal: EDHOC-Key-Update()

**Comment by emanjon** [comment]
Done in 9dcf610

I will make test vectors for EDHOC-Key-Update()

**Comment by emanjon** [comment]
I think we should change to the more simple

EDHOC-KeyUpdate( nonce ):
      PRK_4x3m = Extract( nonce, PRK_4x3m )

This aligns with the other usages of Extract.

**Comment by emanjon** [comment]
No objection to this. This is implemented in -05 specification and test vectors.
