### ISSUE TITLE
Passing information to the application

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#57]
Sections 5.2.3, 5.3.3 and 5.4.3 can explicitly say that nothing should be passed to the application if any verification step fails and the protocol is discontinued.

This applies to Application Data and other information mentioned in the last bullet point of each of those sections.

**Comment by gselander** [comment]
@marco-tiloca-sics When to send EAD is now explicitly stated. What information to send to application is implementation dependent. Is this still an issue?

**Comment by marco-tiloca-sics** [comment]
It looks good. I think the issue can be closed.
