### ISSUE TITLE
Length values when using the Exporter for OSCORE

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#58]
In Section 7.1.1, perhaps the two values specified for the 'length' parameter in the two Exporter invocations can be indicated simply as default values.

The two peers might have been able to agree in advance on different length values, out-of-band or through separate assisted negotiations.

**Comment by gselander** [comment]
@marco-tiloca-sics Please provide an example where you think this is useful.

**Comment by marco-tiloca-sics** [comment]
I was thinking of a possible EDHOC profile of ACE.

Then the Authorization Server can provide not only authentication information to run EDHOC, but also additional information like the intended size for the OSCORE Master Secret and Master Salt to use in the Exporters.

**Comment by mcr** [comment]
> I was thinking of a possible EDHOC profile of ACE.
> 
> Then the Authorization Server can provide not only authentication information to run EDHOC, but also additional information like the intended size for the OSCORE Master Secret and Master Salt to use in the Exporters.

This seems to be merging into the space of https://datatracker.ietf.org/doc/draft-selander-ace-ake-authz/ where we get info from an AS.

**Comment by emanjon** [comment]
I made a commit for -05
