### ISSUE TITLE
Test vectors comments from Peter

### ISSUE THREAD

**Issue by fpalombini** [lake-wg/edhoc#60]
page 51 info for IV_2m, algorithm number 10;
It might be good to remind that the 10 comes from the cose algorithm number specified in item 0 of the suite.

page 52 at the end
K_2e = HKDF-Expand( PRK, info, length) should that not be: K_2e = HKDF-Expand( PRK_3e2m, info, length) .
If not, what should it be?

The number of bytes are sometimes a bit magical; In some cases it can be reminded that ECDH uses 32 bytes and the signature of the ed25519 is 32 bytes as well.

page 51: may be mention that for MAC_2, 8 bytes is length of TAG

page 52: cbor bytes of Signature_or_MAC_2  or h'Signature_or_MAC_2' instead of Signature_or_MAC_2.

page 58 line 6-7: ID_CRED_I, h'Signature_or_MAC_3'

page 59, line 1, HKDF-Expand(PRK_4x3m, info, L))

message_3 = ( h'13', h'CIPHERTEXT_3')

**Comment by gselander** [comment]
@petervanderstok I tried to address what remains of these comments. Let me know I missed something.

**Comment by gselander** [comment]
Closed as discussed during Hackathon.
