### ISSUE TITLE
Change message_1 format

### ISSUE THREAD

**Issue by fpalombini** [lake-wg/edhoc#61]
From @petervanderstok:

Can both message_3 and message_1 be started with C_R that helps the parsing and makes a distinction between the two messages.
In message_1 C_R = h'' means that C_R is to be calcuated by Receiver.
Otherwise C_R serves to determine it is a new connection (messagee_1) or an existing ongoing connection (message_3).

**Comment by marco-tiloca-sics** [comment]
This also relates to https://github.com/lake-wg/edhoc/issues/39

It is possible to distinguish the two message types based on the number of elements that they include.

**Comment by petervanderstok** [comment]
That is true,

I found even other means to do so; But they are indirect, and not
assured to be true in the future.
That is the motivation for asking the change.

It is not a major issue, just makes the code more robust.

greetings,

Peter

marco-tiloca-sics schreef op 2021-01-28 16:56:

> This also relates to #39 [1] 
> 
> It is possible to distinguish the two message types based on the number of elements that they include. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/lake-wg/edhoc/issues/39
[2] https://github.com/lake-wg/edhoc/issues/61#issuecomment-769183292
[3]

**Comment by emanjon** [comment]
Starting message_1 with the fixed h'' sound like it might be a good idea. That only cost one byte and the size in message_1 is not critical.

The change would reduce the number of 1 byte C_R from 49 to 48 or something like that, but we could live with that.

The text would also need to be update to reflect that this would be a dummy C_R and not a value chosen by R.

**Comment by StefanHri** [comment]
I had a very similar issue [here](https://github.com/lake-wg/edhoc/issues/30). At the end, the way to distinguish between messages is through the number and of elements and their CBOR types. However, I agree with 
petervanderstok that this method is indirect. 

The suggested dummy C_R (as far I understand) acts as a message ID. Will it be better to call it message ID? Additionally, also the error message may use a message ID which will make its parsing also easier. 

For me, it is a trade-off between message size and parsing complexity, however, both variants work.

**Comment by emanjon** [comment]
I think a undocumented design philosophy was that first element should be used to distinguish message_1 and message_3. This aspect dissapeared with the bstr_identifier optimization.

I am always hesitant to add bytes, but I think this is a good change. Even if its possible to implement now, there could be future methods that make things more tricky.

The change also needs to make sure that the dummy value h'' cannot be used as a real C_R.

**Comment by petervanderstok** [comment]
Hi John,

"The change also needs to make sure that the dummy value h'' cannot be
used as a real C_R."

At least, h'' can be detected and represented as a byte string with
length 0;
IMO that means: not yet determined.

Peter

John Mattsson schreef op 2021-02-16 14:08:

> I think a undocumented design philosophy was that first element should be used to distinguish message_1 and message_3. This aspect dissapeared with the bstr_identifier optimization. 
> 
> I am always hesitant to add bytes, but I think this is a good change. Even if its possible to implement now, there could be future methods that make things more tricky. 
> 
> The change also needs to make sure that the dummy value h'' cannot be used as a real C_R. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/lake-wg/edhoc/issues/61#issuecomment-779825214
[2]

**Comment by marco-tiloca-sics** [comment]
I also believe this is a good change to do.

**Comment by mcr** [comment]
> I had a very similar issue [here](https://github.com/lake-wg/edhoc/issues/30). At the end, the way to distinguish between messages is through the number of elements and their CBOR types. However, I agree with
> petervanderstok that this method is indirect.

It's not just indirect, it's unstable to future changes in the specification.
It's also hard for an observer to help debug.
So, please let's make this explicit.

**Comment by emanjon** [comment]
I added 
C_1 : bstr .size 0

But this is likely not what we want. This stops the server to negotiate the optimal client ID for OSCORE

**Comment by emanjon** [comment]
Should we reserve one of the 1 byte or one of the 2 byte C_R / Client ID ?

**Comment by emanjon** [comment]
I think we need to discuss and document how the EDHOC processing should be done. This is unfortunatly a bit missing from the document so I understand all the issues regarding this. In the document the processin is written under each message which probably gives the idea that the implementation has to know the message to do processing.

I dont think my previous statement "think a undocumented design philosophy was that first element should be used to distinguish message_1 and message_3. This aspect dissapeared with the bstr_identifier optimization." was true. 

Thinking some more, I think the idea when writing the spec was as follows.

```
- First detemine that is is a EDHOC message.

- Retrieve the security context using the connection identifier and/or other external information such as the CoAP Token and the 5-tuple.

IF security context was found
      - IF messege is error, process as error
      - ELSE process as expected next message in security context
ELSE process as message_1
```
The issue suggesting message_3 several times makes me a bit worried. I cannot see any concrete attacks but it is definitly not intended and might break the security properties.

**Comment by chrysn** [comment]
Coming at this from issue https://github.com/lake-wg/edhoc/issues/39#issuecomment-787965315 (didn't see this one after I posted there), things look already pretty well distinguishable to me as long as the server doesn't pick a value from 0 to 15 for C_R. A server supporting both roles may additionally use distinct sets of C_I and C_R.

**Comment by gselander** [comment]
The ambition is to neither require restriction of C_R, nor policies for C_I and C_R when an endpoint simultaneously acts client and server for multiple connections. As John commented above, the bstr_identifier optimization was one reason for this problem apperaring and we need to fix it, one thing to discuss at March 2 Hackathon. 

Is it feasible to implement according to the procedure John described with the above proposal by @petervanderstok? Other preferred solution?

**Comment by gselander** [comment]
Some comments from Hackathon:

* Need to make expected processing clear 
* Proposal to introduce a mandatory NULL (0xf4) as first field in message_1

**Comment by gselander** [comment]
First draft of new section addressing expected processing: dd3e80f6

**Comment by petervanderstok** [comment]
Sorry. Reference to coap uri is a bit cryptic. Nothing is mentioned in the text?

Otherwise: nice.

Peter

⁣Peter van der Stok
***@***.***

BlueMail voor Android downloaden ​

Op 31 mrt. 2021 12:54, om 12:54, "Göran Selander" ***@***.***> schreef:

**Comment by gselander** [comment]
@petervanderstok The use of CoAP Uri-Path to distinguish messages is mentioned in the Applicability Statmement section. This section is now moved from appendix to the body, see Editor's copy on github: 

https://lake-wg.github.io/edhoc/draft-ietf-lake-edhoc.html#name-applicability-statement

We did not want to bring in CoAP specific options into the generic message processing. Is this still cryptic?

**Comment by petervanderstok** [comment]
HI Goran,

I am still not quite sure what it all means.
In my concept of the world edhoc is used for coap and in a 2nd  instance 
for http.
Anything else may live in the heads of the writers but is not very 
relevant for the current standardization effort.

This is equivalent to what we did for resource directory: in the RD 
anything concerning htpp has been spelled out to remove confusions.
And yet, confusion remains....

Therefore, I recommend strongly to forget about anything beyond coap and 
htpp.
And spell out how you see the use of http by introducing an htpp section 
next to the coap section. (for example discovery of an edhoc path in 
http is quite different )

Cheerio,

peter
Göran Selander schreef op 2021-04-06 09:06:

> @petervanderstok [1] The use of CoAP Uri-Path to distinguish messages 
> is mentioned in the Applicability Statmement section. This section is 
> now moved from appendix to the body, see Editor's copy on github:
> 
> https://lake-wg.github.io/edhoc/draft-ietf-lake-edhoc.html#name-applicability-statement
> 
> We did not want to bring in CoAP specific options into the generic 
> message processing. Is this still cryptic?
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].


Links:
------
[1] https://github.com/petervanderstok
[2] https://github.com/lake-wg/edhoc/issues/61#issuecomment-813880619
[3]

**Comment by gselander** [comment]
Provided by transport. In -08 this is described for CoAP in Appendix A.3.
