### ISSUE TITLE
COSE_Key content constrained according to EDHOC

### ISSUE THREAD

**Issue by fpalombini** [lake-wg/edhoc#62]
From @lemikev:

I have a question about the following sentence on page 13.

Maybe somebody on the call can explain the rational of this sentence.

 

  " For COSE_Keys of type EC2 the CBOR map SHALL only include the parameters 1 (kty), -1 (crv), -2 (x-coordinate), and -3 (y-coordinate). "

 

First, this sentence is incorrect since "subject name" is also allowed.

Why the content of the COSE_Key is constrained?

Why 2 (kid) and 3 (alg) are excluded?

 

Can we replace “SHALL only include” by “SHALL minimally include”?

**Comment by gselander** [comment]
Closing this: The COSE_Key is now replaced with UCCS, and the mandatory terminology is removed (depends on applicability statement).

**Comment by lemikev** [comment]
Thanks for the follow-up Göran.
