### ISSUE TITLE
When key-confirmation is needed latest

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#63]
For applications needing key-confirmation, it may help to formulate it as a requirement for the Initiator along these lines.

"The Initiator must have achieved key-confirmation through WAY_1 or WAY_2 ... before doing THIS_1 and THIS_2, and at the latest before doing THAT."

For instance, the Initiator might be fine to send a protected GET request even without having achieved key-confirmation yet, while the same may not be fine for a PUT request.

**Comment by emanjon** [comment]
The only limitation would be that you should maybe not permanently store the key. There is no relation to GET POST like TLS 0-RTT data without replay. In fact it is not so much a security problem at all, its more like a normal transport problem. I has not gotten any confirmation that R received the message.

**Comment by gselander** [comment]
@marco-tiloca-sics can we close this?

**Comment by marco-tiloca-sics** [comment]
I think so, the text in Section 8.1 builds on John's point.

I just wonder if the recommendation about "not permanently storing" extends also to the possible application key material already derived from PRK_4x3m and TH_4.

**Comment by gselander** [comment]
@marco-tiloca-sics While this is strictly up to the application, I think it makes sense to extend this recommendation to the derived application keys, see recent commit 592c6fe.

**Comment by marco-tiloca-sics** [comment]
Looks good, thanks!

**Comment by gselander** [comment]
@marco-tiloca-sics John made an update: 52b7490. 
Still good/ready to close the issue?
