### ISSUE TITLE
Loss of Message_4

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#65]
Thinking of CoAP for transport, let's say that the Responder sends Message_4 as a Non-Confirmable message, and this never reaches the Initiator.

One can expect the Initiator to eventually resend Message_3. When the Responder receives this Message_3, it has to resend the same Message_4 as above. However, it can come to understand what to do in two possible ways:

1. It stores a full copy of Message_3 upon first receiving it, to check for a perfect match against the retransmitted one. This copy has to be stored until the first protected application-message is received from the Initiator.

2. After having processed the first Message_3 for the first time, it keeps storing PRK_3e2m and TH_3 until the first protected application-message is received from the Initiator. Then, when receiving the retransmitted Message_3, the Responder can just process it again as it did when receiving it the first time.

Which is preferable? The first one costs more in terms of storage, but it still allows the Responder to delete the temporary PRK_3e2m and TH_3 as soon as possible, i.e. when it has completed the processing of the first received Message_3.

**Comment by emanjon** [comment]
Good questions and points.

From an pure EDHOC perspective, the lower layers does not really matter. After message_3 has been received and processed, the Responder should never process message_3 again and PRK_3e2m and TH_3 will have been deleted.

I think 2. violated the EDHOC protocol.

I think 1. is not needed. I dont think the responder needs to check message_3 again. The Initiator must not change message_3. If message_3 is changed things break, which is fine.

**Comment by gselander** [comment]
@marco-tiloca-sics Can we close this?

**Comment by marco-tiloca-sics** [comment]
I think so, thanks to the last paragraph in Section 5.2. For the case in question:

i) the resent message_3 would not match the protocol state on the responder;
ii) in general and also thanks to (i), message_3 is not reprocessed;
iii) also because of (i), message_4 would not be resent either (the state on the responder has moved on).

Side note, though. The text in Section 5.2 also says that if (i) happens (like in this case), the protocol fails, which means it is discontinued and an Error Message is sent. Isn't this excessive for this case and perhaps other ones? This is more related to discontinuing and sending an Error Message for every possible deviation or instead admitting justified exceptions.

**Comment by gselander** [comment]
Per the last paragraph in the previous comment, we keep this open pending the resolution of #101

**Comment by emanjon** [comment]
#101 has been closed. Closing this as well
