### ISSUE TITLE
Information in test vectors

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#66]
It would help to have also the following information explicitly specified in the test vectors.

1) When authentication with signatures is used, please include also the public authentication keys. They are not strictly needed to reproduce the test vectors as stand-alone test units, since they focus on producing outgoing messages. However, they are needed to reproduce the results in full-fledged EDHOC peers, that will have to do signature verification of incoming messages.

2) When using a ciphersuite with ECDSA, please include also the Y coordinate of authentication public keys.

**Comment by emanjon** [comment]
1. I have added public authentication keys to my test vector code, which will used for -05
2. We currently do not have any ECDSA test vectors. Maybe for -06

**Comment by emanjon** [comment]
Updated #47 with this info. Will close this
