### ISSUE TITLE
REST code for EDHOC Error Message as CoAP response

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#67]
The following is a possible exchange that might happen, if using the "EDHOC-in-OSCORE" optimization proposed in [1].

1. The Initiator (as CoAP client) sends an OSCORE-protected request, embedding both EDHOC Message 3 and the actual request payload protected with the just-established Security Context, as per the proposed approach.

2. The Responder (as CoAP server) processes EDHOC Message 3. If this processing fails, the Responder replies with an unprotected EDHOC error message. As of today, this would be a 2.04 response, hence a successful response for CoAP.

However, as per [2], "A successful response to a request with the OSCORE option SHALL contain the OSCORE option." Thus, when receiving the unprotected 2.04 response above, the Initiator would experience an OSCORE failure, which is fine and consistent per se.

However, if the OSCORE processing happens before the EDHOC processing on the Initiator, it might become impossible to access and process the actual response content, i.e. the EDHOC Error Message. Whether which of the two processing comes first is implementation specific.

An easy way out would be to rather have the EDHOC Error Message sent as a CoAP error response. On the Initiator, the response would then be not discarded by OSCORE, and would ensure a correct processing of the EDHOC Error Message.

[1] https://datatracker.ietf.org/doc/draft-palombini-core-oscore-edhoc/
[2] https://tools.ietf.org/html/rfc8613#section-2

**Comment by gselander** [comment]
First update of text on transport of error message, see 75d8dd7.
@marco-tiloca-sics Please comment.

**Comment by marco-tiloca-sics** [comment]
In general, it would be good to better understand what issues are avoided when cross-protocol proxies are used.

Otherwise, the new content can be split and rephrased as follows, i.e. part as general and part as specific to CoAP.

[Section 6.1 - "EDHOC Error Message]

An EDHOC error message can be sent by either endpoint as a reply to any non-error EDHOC message. How errors at the EDHOC layer are transported depends on lower layers, which need to enable error messages to be sent and processed as intended.

EDHOC errors sent as transport-successful messages can avoid issues created by usage of cross protocol proxies (e.g. UDP to TCP).

[Section 7.2 "Transferring EDHOC in CoAP"]

EDHOC errors SHOULD be sent as POST requests and 2.04 (Changed) responses. An exception is the combined EDHOC-in-OSCORE case {{I-D.palombini-core-oscore-edhoc}}, where an error message response following a combined EDHOC message_3/OSCORE request needs to be sent with a CoAP error code.

**Comment by marco-tiloca-sics** [comment]
Following on the original comment and building on more recent discussions, another advantage of having EDHOC Error Messages as CoAP error responses is that they would become cacheable.

**Comment by gselander** [comment]
I think we have addressed this issue. We have removed the statement about avoiding cross protocol proxies (92d9a98d) which wasn't clear, tuned down the requirement on transport (41cf0e9fe) and moved OSCORE processing to the CoRE draft. 

I close this issue now, we can always reopen if there is something we missed.
