### ISSUE TITLE
More information about certificate transport

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#68]
Peter is requesting the specification to provide more information about transporting a certificate in ID_CRED_x, to support a BRSKI use case and to improve interoperability.

**Comment by emanjon** [comment]
Are you sure the "more infroamtion" should be in EDHOC and not in COSE?

**Comment by gselander** [comment]
@petervanderstok Does this address your comment?

**Comment by petervanderstok** [comment]
I thought the issue was solved,
by additionally specifying for ID_CREDx:  {5chain: DER} wher DER is a bstr containing a certificate in DER
5chain to be defined in COSE registry

**Comment by emanjon** [comment]
Both the commit and Peter's comment seem restricted to a single certificate, not a general chain.

**Comment by gselander** [comment]
@petervanderstok x5chain is already defined to be exactly this. See the last sentence of https://tools.ietf.org/html/draft-ietf-cose-x509-08#section-2
There is already a temporary label assigned, namely 33, see https://www.iana.org/assignments/cose/cose.xhtml#header-parameters

**Comment by gselander** [comment]
@emanjon Yes, this was just an example intended to clarify how to transport a credential. As you previously commented, it is not clear if this information should be in EDHOC or in some COSE draft, but since transport of credential was not sufficiently clear, at least one example like this was needed. This does not exclude that we add more information about credential transport, perhaps as a separate section?

**Comment by gselander** [comment]
@emanjon It was only a minor change to the text to also cover certificate chains, see aeaadb8

**Comment by emanjon** [comment]
The latest text is also strange technically. Can be several values in ID_CRED_ID and Cred_X does not have to be one the values. I think this "explanation" makes things worse.

**Comment by gselander** [comment]
Fixed with b5346fb1
