### ISSUE TITLE
Different properties of different methods

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#7]
Freely extracted from https://arxiv.org/abs/2007.11427
https://www.ietf.org/proceedings/108/slides/slides-108-lake-tamarin-study-of-edhoc-00

Do we need
"homogeneity among the EDHOC methods when it comes to what security properties they provide"?

Example 1. All methods support (implicit) mutual authentication. Methods 0 and 1 support injective agreement (i.e. additional key confirmation of the responder). 

Example 2. Not all methods support non-repudation

**Comment by gselander** [comment]
Assuming we allow that different methods to have different properties, how do we handle the differences?

* Is it sufficient to state that all methods has at least certain properties?

* Describe additional properties in security considerations?

* Require or recommend different applications of different methods?

**Comment by gselander** [comment]
The draft should state when key confirmation is achieved and that the parties can save the session state for future use.

**Comment by emanjon** [comment]
Note that as described in the security considerations, none of the methods provide non-repudiation in a useful way. As the singature is over a MAC, non-repudiation requires that long-term storage of the ephemeral key which would remove PFS.

**Comment by emanjon** [comment]
Recent commits add information on the implicit key authentication and explicit key confirmation, giving advise on when the parties get explicit key confirmation which should be assured before the session key is stored long-term.
