### ISSUE TITLE
Message_4 

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#70]
Making key confirmation or introducing signaling to indicate that message_4 should be seem to both introduce comlexity. I suggest that message_4 is moved to things that "parameters to be agreed upon between Initiator and Responder". This works well for example EAP-EDHOC (if message_4 would be included there).

Any text on key confirmation should just be guidance.

The AEAD calculation in message_4 is not needed. We are taking the output from one PRF to generate output from a second (probablypu worse) PRF. I suggest that we just put the output from the exporter in message_4.

"Applicability Statement Template"  -   Is it only me that do not understand at all what this appendix is about by reading the heading in the toc?

**Comment by emanjon** [comment]
I think a lot of the text in the message_4 section can be removed and replaced with

MAC_4 is  EDHOC-Exporter( "EDHOC_message_4_MAC", length )

**Comment by gselander** [comment]
"Applicability Statement Template" - I think it should be understood in the following way. This appendix lists the different protocol parameters and settings that the application needs to ensure are configured/agreed between the endpoints. An "applicability statement" corresponds to a configuration with certain settings. An applicability statement template is a template for what are the parameters and settings that needs to be specified and guidance for how to set them.

Other proposals for title are welcome.

**Comment by gselander** [comment]
Agree that how the Initiator gets key confirmation needs to be left application dependent. But I would like to avoid to leave this completely open. Can we keep a statement that maintains this intent:

"In deployments where no protected application message is sent from the Responder to the Initiator, the Responder MUST send message_4."

* One comment was that this is not possible to verify.
* What if the applicability statement specifies R to send an OSCORE response, but R cannot enforce that, e.g. in case there is an error with the request?

**Comment by emanjon** [comment]
"In deployments where no protected application message is sent from the Responder to the Initiator, the Responder MUST send message_4."

That sounds very good to me. I don't see any need for any more text.

**Comment by gselander** [comment]
The text is included in section 7.1
