### ISSUE TITLE
Classes of Error messages.

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#74]
At the last interim there was a suggestion to standardize classes of error messages and to ask the IoT groups in IETF about what classes of error messages that should be standardized.

- The error message should then be augmented with a error message class. int? array of int?
- Shoudl the optional text string remain. That cannot be used for any automation. But might be useful for loggging for later reading by a human. The initial classes or error message might not provide much info, e.g. "authentication error"

**Comment by gselander** [comment]
Mailthread in iotops:
https://mailarchive.ietf.org/arch/msg/iotops/KcWcK19kACOYnimRqFNJDBu_MAk/

**Comment by gselander** [comment]
Proposal after discussion in Hackathon:

error = (
  ? C_x : bstr_identifier,
    DIAG_MSG : tstr,
    ERR_CODE : int / 2* int,
  ? SUITES_R : [ supported : 2* suite ] / suite,
)

Top-level ERR_CODEs:

(0. Success)
1. Message field error (syntax error or incorrect protocol field of expected message)
2. Selected cipher suite not supported (include SUITES_R in message)
3. Credential/context error (error related to establish certificate/raw public key context for processing message, including certificate expired, revoked, unsupported, corrupt, unknown CA, or other issue in processing the credential)
4. Decrypt error (a cryptographic operation failed, including being unable to correctly verify a signature or a MAC in the protocol message)
5. Auxiliary data error (unsupported or missing auxiliary data)
6. Access denied (credential valid but peer not allowed access)
7. Internal error (error not related to the protocol or the peer)

Selected comments during Hackathon:
- Relation to errors on other layer, e.g. CoAP errors or error in application. 
- - EDHOC does not require CoAP so could have use for specified own errors.
- - Does "5. AD error" belong to EDHOC?  Perhaps, auxiliary data provides means for security applications to reuse EDHOC and this would be a channel to send errors in those applications. [Not sure if this helps but, alternatively, errors could be encoded as auxiliary data, which may require an AD-field in the error message]
- - Does "6. Access denied" belong to EDHOC? Perhaps, it provides a suitable error to the requirement "Verify that the identity of the Responder is an allowed identity for this connection"


Further comments are welcome. Happy to make the list shorter if possible.

**Comment by gselander** [comment]
Other thoughts:

* We can put some of these error classes into an "x. unspecified error" bucket if we don't think they are not meaningful to act upon individually. 

* We can define a class of errors "y. general error" and allow implementations to use class y for any error, including those properly belonging to some class above. This would allow implementations to only support some of the specified errors above, potentially listed in the applicability statement. (That would render the list of classes above just a RECOMMENDATION.)

**Comment by emanjon** [comment]
Many OSs, shells, and programming languages (e.g. C) use 0 for success and everthing non-zero (negative or positive) is considered an error. HTTP and Coap use postive numbers only where 2. or 2xx is considered success.

I think we should probably follow one of these convensions instead of making a new one.

The specification should also probably define that everything else than whatever we decide for success is considered an error.

**Comment by emanjon** [comment]
I made a PR #113 addressing all known issues regarding this.

**Comment by gselander** [comment]
This is ready to merge unless there are any objections.

**Comment by emanjon** [comment]
The PR has been discussed and merged. Closing
