### ISSUE TITLE
Move 7.2.  Transferring EDHOC in CoAP to draft-palombini?

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#75]
7.2 was written before draft-palombini existed. Would it make sense to move all OSCORE specific informaiton to draft-palombini and make that draft more general. Right now you probably have to read both. A lot of the new issues and discussion are concerning the OSCORE EDHOC interaction.

**Comment by gselander** [comment]
As there has been no comment on this issue, we now plan for moving out section 7.2.1 and second half of 7.2.2 to draft-ietf-core-oscore-edhoc (former draft-palombini- ...)

**Comment by StefanHri** [comment]
This makes sense for me.

**Comment by marco-tiloca-sics** [comment]
Yes, that makes sense.

**Comment by rikard-sics** [comment]
Sounds good to me also.

**Comment by malishav** [comment]
As discussed during the last interim, I do not believe removing the link of draft-ietf-lake-edhoc with OSCORE is a good idea from the charter point of view of the LAKE WG.

I just went through the editor's version of draft-ietf-core-oscore-edhoc and here is my proposal forward:

* Create a new appendix in draft-ietf-lake-edhoc named "Use with OSCORE", say Appendix A.
* Move the content of Section 4 of draft-ietf-core-oscore-edhoc back to draft-ietf-lake-edhoc, to Appendix A.1.
* Merge the content of Section 3 of draft-ietf-core-oscore-edhoc with the content in Section 7.2 of draft-ietf-lake-edhoc. Move the result to Appendix A.2.

With that, draft-ietf-lake-edhoc contains all the information to implement EDHOC and use it to key OSCORE. draft-ietf-core-oscore-edhoc becomes streamlined and focuses on optimizing the specific use case when message_3 and OSCORE request are sent in the same CoAP message for performance reasons.

**Comment by gselander** [comment]
@malishav @mcr I believe -08 does exactly what you requested. Can we close this?

**Comment by malishav** [comment]
WFM, closing
