### ISSUE TITLE
appendix b.1.1

### ISSUE THREAD

**Issue by petervanderstok** [lake-wg/edhoc#76]
Some typos in appendix B.1
page 51,
 G_X (Initiator’s ephemeral public key) (32 bytes)
 89 8f f7 9a 02 06 7a 16 ea 1e cc b9 0f a5 22 46 f5 aa 4d d6 ec 07 6b ba
 02 59 d9 04 b7 ec 8b 0c
probably a typo in the key value because not accepted by mbedtls 

GS: Seems identical to test-vector.txt. Perhaps someone else can confirm this?

page 57,
MAC_2 (8 bytes) mention that this is the length of the tag.

GS: Using "CBOR unencoded". See new text in appendix.

page 58
K_2e = HKDF-Expand( PRK, info, length )
PRK relaced by prk_3e2m

-> GS: Replaced with PRK_2e. (As of -04 formulated in terms of KEYSTREAM_2)

page 62,
MAC_3 (8 bytes) mention that this is tag length

-> GS: Using "CBOR unencoded".

page 63
The Plaintext is the following CBOR Sequence: plaintext = ( ID_CRED_I
 , Signature_or_MAC_3 )
should this not be h'Signature_or_MAC_3'

-> GS: Using "CBOR unencoded".

page 64,
Nonce IV_3ae is the output of HKDF-Expand(PRK_3e2m, info, L).
I had understood that PRK_4x3m should be used.

-> No this is actually correct. See section 4.0: "K_3ae and IV_3ae are derived using the transcript hash TH_3 and the pseudorandom key PRK_3e2m. "

page 65
message_3 =
 (
 h’13’,
 h’’
 )
should be :

message_3 =
 (
 h’13’,
 h'CIPHERTEXT_3’
 )

-> GS: Using "CBOR unencoded".

**Comment by gselander** [comment]
@petervanderstok Edited previous comment. Please let me know if there are further comments.

**Comment by petervanderstok** [comment]
the mbedtls library only support a basic curve25519 set.
For that reason many ecdh ephemeral keys are refused in my impementation.

Is it posible to only support the basic set in edhoc?

**Comment by gselander** [comment]
Closed as discussed during Hackathon.
