### ISSUE TITLE
use of 5chain

### ISSUE THREAD

**Issue by petervanderstok** [lake-wg/edhoc#77]
on page 14 would it not be suitable to add that
ID_CRED_x = { x5chain : certificate in DER }, for x = I or R,

**Comment by gselander** [comment]
Very timely comment. I just made an update to this effect, see b5346fb. I didn't want to include this kind of notation as it requires explanation. Is it good enough?

**Comment by petervanderstok** [comment]
Suggest to give it a bullet as well.
Göran Selander schreef op 2021-02-22 11:26:

> Very timely comment. I just made an update to this effect, see b5346fb [1]. I didn't want to include this kind of notation as it requires explanation. Is it good enough? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1]
https://github.com/lake-wg/edhoc/commit/b5346fb15acba5116b97808415e77bf91d044e74
[2] https://github.com/lake-wg/edhoc/issues/77#issuecomment-783268938
[3]
