### ISSUE TITLE
Coding density for bstr_identifier

### ISSUE THREAD

**Issue by chrysn** [lake-wg/edhoc#79]
We could increase (by a factor of about 3) the number of identifier values encodable in 2-byte bstr_identifier -- if rather than treating them as a byte string toward the application, we treat them as distinct integer and bytes values.

As before, the same 1-byte values could be encoded (-24 to 23). Of the 2-byte long encodings, there there would be ~3x256 inhabited ones (unlike now, ~256): We could use the 256 `18 xx` (for xx > 24 as those would be encoded in a single byte), `38 xx` (again, xx < 24 staying uninhabited) and the `41 xx` (1-long byte strings) values.

Whether this makes implementation harder or easier is IMO dependent on the programming style; for me it'd make things easier. (Implementers can't store the value as a length-delimited bytestring with a custom encoder any more, but can still store the CBOR encoded item in an opaque string).

This would also allow applications that find it easier to work with small numbers to just use numeric identifiers for everything they mint themselves, and use these in lookup. (These then lose some of the benefits of identifier compression.)

**Comment by chrysn** [comment]
Considering how the OSCORE extractor uses C_I and C_R, this would be problematic.

Options are:
1. Leave it as is -- with only ~256 2-byte C_x available
2. Allow arbitrary int / bstr as bstr_identifier, but move the text over to the OSCORE extraction to say that this mapping is applied between C_x and `kid`. That would leave the general applications with the wide possibilities, while OSCORE would have the 0-length KID in a 1-byte bstd_identifier, a few selected KIDs (00 to 18) also in the 1-byte bstr_identifier, and all the others in len+1 bstr_identifier slots.
3. Go for even more efficiency (but that has minimal returns at great complexity so is almost certainly not worth it)

I have a soft preference for 2, but 1 is probably fine as well -- given that OSCORE will be a main user of EDHOC and couldn't use the optimization.

**Comment by emanjon** [comment]
I think 2 is the right way to go. I think we should do that. I think the current specification of bstr_identifier is a bit complex. We have gotten several comment and questions regarding this. I think 2 make things simpler.

**Comment by emanjon** [comment]
I made a pull request for this issue. @chrysn check that the transformation between C_x and OSCORE ID is what you wanted. I did not see any point in making it more complex.

I just realized that we could expand the number of 1 byte excodings with almost 50 % by also allowing major type seven I.e.

C_x : bstr / int / #7 

(null is reserved for used by C_1)

**Comment by emanjon** [comment]
Even with this change the bstr_identifier stays for its use in compressing ID_CRED_x when kid is used i.e. { 4 : kid_R }.

**Comment by emanjon** [comment]
Or maybe we can not use #7 as the values 0..19 are unassigned

**Comment by emanjon** [comment]
This issue needs to wait until we have decided what to do with correlation. Suggestions on the table are diverse
- to leave it to lower layers
- make all C_x mandatory

**Comment by chrysn** [comment]
Next step (from current discussion): provide PR, and describe (explicitly and locally) how an integer can encode for a `{4: x}` value. Then we can discuss further based on that.

**Comment by emanjon** [comment]
>Other alternative: just let a bstr encode for {4: x} -- that allows having a single one-byte value still (rather than ~48), >and 256 two-byte values. Good enough for the cases where there is one distinct to-be-optimized-for peer, and in how >many cases is 48 enough?

That is a good observation. Might be useful with two values when the distinct to-be-optimized-for peer updates its key.


If bstr_identifier is not used for connection id, maybe the bstr_identifier section could be removed and replaced by:

* plaintext = ( ID_CRED_R / bstr / int, Signature_or_MAC_2, ? AD_2 )

* If ID_CRED_R contains a single 'kid' parameter, i.e., ID_CRED_R = { 4 : kid_R }, only the kid_R is conveyed in the plaintext. If ‘kid’ is in the interval h'00' to h'2f’, it is encoded as the corresponding integer minus 24, instead. I.e. { 4 : h’2a’ } is encoded as the integer 18, while { 4 : h'' } is encoded as h’’.

**Comment by gselander** [comment]
Specifically for the 'kid' use of bstr_identifier, how about registering a new CBOR Header Parameter  (https://www.iana.org/assignments/cose/cose.xhtml) called, say, 'kid-int' with same function as 'kid' but where the value is a CBOR int instead of a CBOR bstr.

~~~~~~~~~~
   +-----------+-------+----------------+-------------+----------------+-------------------+
   | Name      | Label | Value Type     | Value       | Description    | Reference         |
   |           |       |                | Reference   |                |                   |
   +-----------+-------+----------------+-------------+----------------+-------------------+
   | kid-int   | TBD   | int            |             | Key identifier | [[This document]] |
   +-----------+-------+----------------+-------------+----------------+-------------------+
~~~~~~~~~~~

**Comment by emanjon** [comment]
That is an interesting idea. Another alternative would be to expand the existing 'kid' in COSE to be bstr / int.

**Comment by chrysn** [comment]
Both sound practical, and would make the WIP PR more readable. In an
ecosystem where thins are passed around as COSE objects, having
identifiers bstr/int does make sense. (Among other things, it allows
configuration storages to save their values in their pre-encoded compact
form).

**Comment by gselander** [comment]
I agree a single key identifier with value bstr / int is a better idea. In practice, how would we redefine 'kid' to be bstr / int? I assume it is too late to make the change in draft-ietf-cose-rfc8152bis-struct, so this would be a draft updating that RFC. Any compatibility issues with old and new implementations of 'kid'? 

Would it be an alternative to define a new key identifier:

~~~~~~~~~~
   +-----------+-------+----------------+-------------+----------------+-------------------+
   | Name      | Label | Value Type     | Value       | Description    | Reference         |
   |           |       |                | Reference   |                |                   |
   +-----------+-------+----------------+-------------+----------------+-------------------+
   | kid2      | TBD   | bstr / int     |             | Key identifier | [[This document]] |
   +-----------+-------+----------------+-------------+----------------+-------------------+
~~~~~~~~~~~

**Comment by chrysn** [comment]
> Any compatibility issues with old and new implementations of 'kid'? 

Either way (kid2 or kid redefinition), a peer needs to know in advance
what the other can accept; KIDs are (AFAICT) currently not exchanged
in-band. Whoever knows enough of their peer to use a kid2 could use the
same knowledge to know that they support int-valued KIDs.

Trouble is where implementers come in anew and use numeric KIDs without
knowing that some peers may not support them -- that's a bit more
obvious with a kid2, but in the end I think in both cases it should fail
clearly at the KID distribution step (and if that's only "Sorry, I can't
enter that into my system, it expects a byte string and you gave me an
integer").

With an eye on code point usage (of 1..23, 10 are already assigned), I'd
prefer opening up kid, but ultimately that's something that ultimately
will need to be decided in COSE.

**Comment by emanjon** [comment]
kid2 or kid redefinition seems cleaner than kid_int, at least for EDHOC. It must be specified that the int is encoded with deterministic CBOR.

In EDHOC we could mandate support of of  numeric kids.

It would have been easier if there was only deterministic CBOR, then you could do kid = any

**Comment by chrysn** [comment]
kid = any would be hard on parsers (any could be tags the receiver does not support), and it'd switch disambiguation between raw kid and actual COSE object (now it's "bstr or int are special", then it'd be "it's a kid to pack in {4:x} unless it's a map in which case treat it's the map itself).

**Comment by gselander** [comment]
How about we introduce kid2 in the draft, with the assumption of deterministic CBOR, and an editorial note that it may be changed to kid later.  Then we can carry out the changes in the PRs to be able to better evaluate them. In parallel we bring up the discussion in COSE. If COSE accepts the redefinition of kid then we simply replace kid2 with kid, otherwise we keep it.

**Comment by gselander** [comment]
bstr_identifier is now removed and replaced with bstr / int. The mapping to OSCORE Sender/Recipient ID is described in A.1. kid2 is defined as above pending discussion in COSE.

@chrysn Can we close this?

**Comment by chrysn** [comment]
Yes. From the quick glance I had so far I think that still some enhancements can be made to the conversion described now, but I'll need some time to propose anything concrete there, and at any rate, the original concern is addressed. Thanks, closing.
