### ISSUE TITLE
Verification of intended peer

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#8]
Extracted from https://arxiv.org/abs/2007.11427
https://www.ietf.org/proceedings/108/slides/slides-108-lake-tamarin-study-of-edhoc-00

"Section 3.2 of the specification states that a parties are required to be configured with a policy restricting the set of peers an they are allowed to run EDHOC with."

"the initiator is not required to verify that the ID CRED R received in message 2 is the same as the one the application intended when initiating the EDHOC run"

"the initiator [need] to match ID CRED R to the intended identity provided by the application"

"the application must be able to instruct EDHOC to not accept the same identity in the next attempt"

**Comment by gselander** [comment]
When raw public keys are used in EDHOC, EDHOC allows the parties to agree on an optional “subject name” that are included in the MAC/Signature (i.e. not sent on the wire). We would like more input from  people deploying contrained IoT devices and what their operational requirements on identity are. Do they see the public key itself as the identity? Is a subject name available in many or all cases?

Should the “subject name” in raw public keys be recommended or even mandatory?

**Comment by chrysn** [comment]
At least for [rd.link](https://tools.ietf.org/html/draft-amsuess-t2trg-rdlink-01) purposes (which is admittedly just an independent draft right now), an RPK can be a standalone thing to verify, and adding any further identifier (like an EUI-64 picked by the identifying party) that'd needed to be known would just weigh down discovery needlessly. Sure, a subject identifier can be derived from the known RPK, but then what's the value of it. (That is saying nothing against having an agreed-on subject, of course.)

**Comment by gselander** [comment]
Agree. This issue has been considered in more than one way:

In 3.5.3: 
"The EDHOC implementation or the application must enforce information
   about the intended endpoint, and in particular whether it is a
   specific identity or a set of identities."

In 3.5.2:
"To prevent misbinding attacks in systems where an attacker can
   register public keys without proving knowledge of the private key,
   SIGMA [SIGMA] enforces a MAC to be calculated over the "identity".
   EDHOC follows SIGMA by calculating a MAC over the whole credential,
   which in case of a X.509 or C509 certificate includes the "subject"
   and "subjectAltName" fields, and in the case of CWT or UCCS includes
   the "sub" claim, see Section 3.5.3. "

If there are other aspects where verification of intended peer is missing we can open a new issue.

I close this now.
