### ISSUE TITLE
Applicability statement can depend on conditions during EDHOC execution

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#80]
The applicability statement is agreed out of band, but the policy can depend on information gained during the protocol run, e.g. ~~the identity of the peer,~~ the RESTful resource being called, CoAP options being used or other transport parameters.

**Comment by gselander** [comment]
One step back: The applicability statement needs to be understood already at reception of message_1 to be able to verify supported method/corr etc. so cannot depend on identity of the peer.

**Comment by emanjon** [comment]
The type of ID_CRED_I can definitly depend on message_2.

Not sure I like the suggestion to make the applicability statement normative text in the body.....
