### ISSUE TITLE
COSE header map for public key

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#82]
This issue needs to be resolved in COSE, but I didn't find this listed anywhere so I put a placeholder here. There is no COSE header map defined for transport of public key in ID_CRED_x. Needed for opportunistic settings, also required by draft-selander-ace-ake-authz.

**Comment by gselander** [comment]
Also, the type of public key needs to be specified. It could be different COSE header maps for different COSE key types:
https://www.iana.org/assignments/cose/cose.xhtml#key-type

EC types OKP and EC2 could have the same COSE header map label (TBD) but differ in content, like CRED_x as in EDHOC Section 3.3.3.

{ TBD :  CRED_x }

* For type OKP the CBOR map SHALL, except for subject name, only include the parameters 1 (kty), -1 (crv), and -2 (x-coordinate).

* For type EC2 the CBOR map SHALL, except for subject name, only include the parameters 1 (kty), -1 (crv), -2 (x-coordinate), and -3 (y-coordinate).

For example, for OKP

CRED_x = {
  1:  1,
 -1:  4,
 -2:  h'b1a3e89460e88d3a8d54211dc95f0b90
        3ff205eb71912d6db8f4af980d2db83a',
 "subject name" : "42-50-31-FF-EF-37-32-39"
}

The corresponding text in 3.3.3 could be moved to a COSE draft which is normatively referenced from EDHOC.

**Comment by emanjon** [comment]
COSE should probably specify how to transfer a COSE_KEY without any further restrictions. Alternatively the c5c header could be used without much overhead. It might be better to do a new type of C509 without signature that is a RPK. COSE_KEYs are not efficiently encoded at all.

**Comment by emanjon** [comment]
The 

CRED_x = {
1: 1,
-1: 4,
-2: h'b1a3e89460e88d3a8d54211dc95f0b90
3ff205eb71912d6db8f4af980d2db83a',
"subject name" : "42-50-31-FF-EF-37-32-39"
}

Should probably  be replaced by CWT or C509

**Comment by gselander** [comment]
Closing this: COSE header map for CWT/UCCS is now defined, and the example of CRED_X is replaced.
