### ISSUE TITLE
Make .well-known/edhoc specific to OSCORE

### ISSUE THREAD

**Issue by chrysn** [lake-wg/edhoc#84]
Given we're now moving towards that EDHOC needs to know the application (with its applicability statement), it would make sense to move the definition of the .well-known/edhoc resource over to @fpalombini's draft on EDHOC/OSCORE.

The general mechanisms of EDHOC-over-CoAP could stay here (which eg. say which corr to use, and which content format), but using it for OSCORE key extraction could be the exclusive user of .well-known/edhoc (which may get a different name in the course of this). Other applications would then be indicated with different paths.

**Comment by chrysn** [comment]
I put this badly: it should be about "getting OSCORE contexts from EDHOC" and not generic for "EDHOC over CoAP" -- but not necessarily limited to the particular way in Francesca's draft.

**Comment by emanjon** [comment]
I think moving everything OSCORE related to Francesca's draft is a good idea.

**Comment by gselander** [comment]
@chrysn @marco-tiloca-sics Given how the content is now distrbuted in lake-edhoc-08 and core-oscore-edhoc-01, is this still relevant. Should we replace this issue with a draft-core-oscore-edhoc github issue? Anything that remains to do here?

**Comment by chrysn** [comment]
If I understand the current distribution right (applying-to-coap-oscore is described here, oscore-edhoc is only about msg3 in an option), I think it should stay here (both tracker- and document-wise).

@marco-tiloca-sics, if it were really just an example for use in the figures, it wouldn't need to be well-known (when would there be the justification for even registering it), and as a reader I'd be missing a way to discover the path. I'd expect applications (either defined by downstream standards or just application behavior) to say no more than "EDHOC and OSCORE are used all the time with keys exchanged through X", so this is an actual default and not an example. (And frankly the only reason I'd see for any application to not use .well-known/edhoc is if they use any of the AD, don't know if that can be multiplexed onto .wk/e or not).

**Comment by marco-tiloca-sics** [comment]
Yes, that's the current distribution and I see your points. Ok to keep it here then

**Comment by chrysn** [comment]
Yeah, the current placement within the EDHOC-for-OSCORE section provides the requested clarification.
