### ISSUE TITLE
State idempotency

### ISSUE THREAD

**Issue by chrysn** [lake-wg/edhoc#85]
When setting EDHOC up on a constrained CoAP library, it'd help a lot if there'd be a statement that the EDHOC operations must be idempotent, ie. tolerate that retransmissions of a request are passed on to EDHOC multiple times (ie. the CoAP library may forego request deduplication). Ideally, all these requests should lead to identical responses.

I think that these properties are already there (possibly necessitating that messages 2 and 4 are distinguishable by a server in initiator mode, if message 4 ever happens there); having a statement would make it possible to justify using EDHOC on a library like, say, RIOT's gcoap, in the first place.

**Comment by chrysn** [comment]
Tying this to the draft: "The transport is responsible to handle message loss, *reordering, message duplication*, fragmentation, and denial of service protection, where necessary". I think that EDHOC can do without the highlighted ones already.

**Comment by chrysn** [comment]
(Summarizing otherwise not-yet-written-down developments for chronology): It looks like it won't be "idempotency", but more something "the CoAP stack may forego message deduplication, because the EDHOC implementation needs to report back the last message when requested again".

**Comment by chrysn** [comment]
Looking at [I-D.ietf-ace-wg-coap-eap](https://tools.ietf.org/html/draft-ietf-ace-wg-coap-eap-00), they face a similar situation -- but EAP expresses as a requirement for the lower layer that it must have ordered message transmission. I disagree with the mechanism they use (introducing a sequence number option; discussion ongoing), but maybe something comes out of the discussions there that'd help here as well; will keep this updated.

**Comment by gselander** [comment]
@chrysn Could you please comment on the new text?

**Comment by chrysn** [comment]
Sounds good, and well implementable. Two notes:

* Why does this need to be part of the applicability statement? Whether deduplication happens on CoAP level or on EDHOC level should be transparent to a well-behaved peer. (Plus, in the presence of proxies, even if one party does EDHOC level deduplication, there may actually happen CoAP level deduplication on the path -- but no well-behaved party would see the difference).

* On wording, it took me a bit to parse the "Note that if a different instance" sentence; suggested alternative to mix and match (with an addition of when this happens):

> Note that if two different versions of EDHOC message_x are received (message_x1 and message_x2, in that sequence), then the "processing" described above of message_x2 will produce the response to message_x1. That will correctly result in a failure in integrity verification due to difference in transcript hashes between the message_x instances. The situation can only arise when the peer violates the requirements of not processing a message twice, or when the messages are tampered with.

**Comment by gselander** [comment]
About applicability statement: I believe you are right. I was thinking that if only one endpoint supports EDHOC message deduplication, the other endpoint would fail in case duplicate message appears. But actually, the other endpoint do need to support **some kind** of deduplication, it just doesn't matter which kind. So I'll remove that part.

On wording: I'll make another attempt.

**Comment by emanjon** [comment]
Not sure that this should be an appendix. If it is an appendix it should not be hidden behind the test vectors.

The suggested text states "duplication due to re-transmissions". What about other duplications? Duplication can happen anywhere in the network path. Or by an attacker.

"but the received message must not be processed more than once by the EDHOCimplementation. "

This is true for 2,3,4, not true for 1 and error. Needs to make clear that this is per instance.

**Comment by emanjon** [comment]
The PR has been discussed and merged. Closing
