### ISSUE TITLE
Compressing ".well-known/edhoc"

### ISSUE THREAD

**Issue by chrysn** [lake-wg/edhoc#87]
If the 18 bytes of the ".well-known" "edhoc" get in the way anywhere, there is always the possibility to register an option that expands to that. For example, Someone (probably not in this document; it'd be a short CoRE draft) could ask for an option in the <269 range that is uint valued, and whose uints expand to a TBD IANA registry where 0 is mapped to Uri-Paths ".well-known" "core" and 1 is mapped to ".well-known" "edhoc".

That'd save 15 bytes in messages 1 and 3, provided the .well-known/edhoc resource is really used. (Is it at all, with the most critical applications?)

**Comment by gselander** [comment]
This proposal has been brought up in CoRE and is not really in the scope of LAKE. Can we close it?

@marco-tiloca-sics Perhaps better to have a placeholder as a github issue related to draft-ietf-core-oscore-edhoc?

**Comment by marco-tiloca-sics** [comment]
Yes, it makes sense, let's take is as a first step and see where it leads to.

**Comment by chrysn** [comment]
Yes, can close; I have a note to start a short document on draft-amsuess-core-common-option-compression based on the 2021-05-12 interim presentation.
