### ISSUE TITLE
editorial / usability: corr and C_x omission

### ISSUE THREAD

**Issue by chrysn** [lake-wg/edhoc#89]
Both while trying to understand an implementation and in discussions of transport considerations, I was repeatedly had by the correlation numbers. It's convenient in the serialization to look into bits of a 2-bit number, but for talking about it, I always had to look things up.

Concrete proposal:

In the Message Correlation subsection, state after each bullet the respective one of "There is a C_x in the first message position", "In the first message position, C_I is sent and C_R is omitted", ..., "In the first message position, no C_x is sent". If phrased more concisely ("C_I is sent, C_R is omitted"), it'd need a paragraph that states that "The above statements about sending or omitting C_x only refer to the first positions in the messages; the C_I in Message 1 and C_R in Message 2 are always sent". Ideally, this could be put in a table.

Then, in the descriptions of Responder Processing of Message 2 and following, it can just say "C_x is sent depending on the correlation from {{}}".

IMO having these in one place and not baking the bit extraction in every step would make it easier to read.

**Comment by emanjon** [comment]
I am not understanding exactly what you sugest, but it is probably a good idea. Could you make a pull request?

**Comment by gselander** [comment]
As @chrysn noted in #105, a solution to that issue (which is included in -08) solves this issue.
