### ISSUE TITLE
Implementation guidance for CoAP

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#91]
A request for more implementation guidance for CoAP. E.g. in section 7.2.2, add

"Since CoAP Token correlates responses to requests, connection identifiers can be left out of responses (if specified in the applicability template). In this case can the error messages ({{error}}) be identified in the following way:

* if it is a request with 3 elements and the second is an int
* if it is a response with 2 elements and the first is an int"

Is this the right place for such text?

**Comment by emanjon** [comment]
The bullets has nothing to do with CoAP. Might be good to have an appendix on how to differentiate between different messages. But I don't think the CoAP section is the right place for the bullet. The first suggested sentence could be added to the CoAP section.

**Comment by marco-tiloca-sics** [comment]
The above bullet points hold if `corr` is `1` or `2`. This may not apply to CoAP only, but it comes from having assumed so far that using CoAP implies `corr` `1` or `2` (relates to #95).

It would be *very good* to have an Appendix with a sequence of steps describing how a recipient can determine the message type when receiving a message, in the most general case.

If CoAP cannot imply `corr` `1` or `2` anymore (relates to #95), it may become pretty challenging to distinguish message types and especially identify Error Messages.

**Comment by gselander** [comment]
This is not an issue anymore;  corr is now removed, the CoAP section describes how to correlate messages.
