### ISSUE TITLE
Selected hash alg. vs hash alg in x5t

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#93]
x5t is parametrized with the hash function it uses. (x5t mandates support for SHA-256, but not its use.)

The spec doesn't state that the hash function in x5t (when used) needs to be the same as the hash alg in the selected cipher suite.

* If it doesn't, then the endpoint may not be able to verify the hash of the certificate because it does not support the hash algorithm used in x5t.

* If it does, then there are redundant bytes in x5t, since the hash alg is known from the selected cipher suite. Is it worth doing anything about that?

**Comment by emanjon** [comment]
This is covered by the applicability statement of ID_CRED_x. I don't see any need for change.

**Comment by emanjon** [comment]
Clossing this as there was no further comments
