### ISSUE TITLE
Action in case of early error

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#94]
Current specification mandates sending error messages upon certain failures. But in cases when message processing fails when no state has been allocated or when no connection identifier has been found or then a more appropriate action would be to just silently drop the message.

**Comment by emanjon** [comment]
I think the MUST (if possible) is good. Debugging without any error messages is not nice. We now other protocols that it is good to mandate error messages. It is kind of obvious that can not send an error if you don't now where/how to send it. Don't know if that has to be pointed out....

**Comment by emanjon** [comment]
Migth be good to not sent error if you are under a DoS attack.

**Comment by emanjon** [comment]
This issue is addressed by pull request #109 that also address availability

**Comment by emanjon** [comment]
The PR has been discussed and merged. Closing
