### ISSUE TITLE
Dependency between corr and transport

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#95]
There has been an off-list/off-git discussion about correlation and transport. The specification does not normatively specify that a certain transport is associated to a certain corr.

Section 3.2.4: 

"If the transport provides a mechanism for correlating messages received with messages previously sent, then some of the connection identifiers **may** be omitted."

"For example, if the key exchange is transported over CoAP, the CoAP Token **can** be used to correlate messages, see Section 7.2."

In the case of CoAP, two examples are shown and corr factors stated in those cases.

Section 7.2:

"An example of a successful EDHOC exchange using CoAP is shown in Figure 9. In this case the CoAP Token enables the Initiator to correlate message_1 and message_2 so the correlation parameter corr = 1."

"An alternative exchange that protects the server identity against active attackers and the client identity against passive attackers is shown in Figure 10. In this case the CoAP Token enables the Responder to correlate message_2 and message_3 so the correlation parameter corr = 2. "

A question raised is if this dependency between CoAP transport and corr is in fact mandatory, and that corr is redundant to send since it is determined by transport.

On the other hand, if EDHOC is used over interchanging transports between the endpoint and not all transports support the same correlation, then it is not possible to deduce corr from transport. Just because that last hop is over CoAP, the Initiator may still not be able to correlate a received message_2 to a sent message_1. With this in mind, it must be allowed to set corr = 0 also for CoAP transport.

Does it make sense? Is this an issue? 

in any case we need to clarify this.

**Comment by emanjon** [comment]
I don't see what the problem is.

**Comment by emanjon** [comment]
Corr is included in message_1 so that it is covered by the integrity protection. This was a comment from the CFRG review. So I do not think Corr is redundant.

**Comment by malishav** [comment]
@emanjon My understanding is that a mere reception of `message_1` over a given transport determines the `corr` value. E.g. if the responder receives `message_1` over CoAP and the responder plays a CoAP server, the Responder knows that the value of `corr` is `1`. If the CoAP server receives a POST trigger as in Fig. 8 in EDHOC-05, and then sends `message_1` in the 2.04 response, the EDHOC Responder-CoAP client knows that the value of `corr` is `2`. That said, my question is why do you need to transport `corr` on the wire? Is there any counter example where `corr` is not uniquely determined from the transport itself? Could you not integrity-protect `corr` without transporting it on the wire?

**Comment by marco-tiloca-sics** [comment]
Maybe the following case can be the counter example. Think of this setup:

* An initiator talking only a protocol PROT that requires `corr` `0`.
* An intermediary acting as PROT-to-CoAP forward proxy.
* A responder talking CoAP.

The initiator has to use `corr` `0`. The responder will receive CoAP messages but cannot imply `corr` `1` or `2` from that; rather, it has to follow `corr` as indicated in `message_1`, and talk CoAP with the proxy while using `corr` `0` in the EDHOC session.

From then on, this should work just fine from an EDHOC and transport point of view, but CoAP itself would not be taken by the responder as an indication of `corr` `1` or `2`.

As a consequence, especially for the responder it may become pretty challenging to distinguish message types of received messages and identify Error Messages (relates to #91). That is, the responder has to consider the "union" of possible message formats putting together the alternatives from `corr` `0`, `1` and `2`, which would yield interpretation ambiguities.

Possibly considering this too, it would help anyway to have an Appendix with a sequence of steps describing how a recipient can determine the message type when receiving a message (relates to #91).

**Comment by marco-tiloca-sics** [comment]
More generally, when receiving an EDHOC message, a correlation cannot be implied from the message itself. This can make the message parsing difficult and ambiguous (see previous comment), while it may still be needed to be done --- and in a certain way --- also to retrieve the right session in question.

A safe way to address this kind of situation can work as follows.

1. Associate the received EDHOC message with the pertinent applicability statement. As discussed in the document, this can be done, e.g., through a specific URI, port number, etc.

2. If the applicability statement does not indicate a correlation to use, assume `corr` is `0` by default. Otherwise, consider the indicated correlation(s).

3. Parse the message according to what determined at the previous step.

For an applicability statement to prevent the original problem to come back, it is fine that it indicates correlation = 0, or correlation = (1, 2) coexisting, or correlation = 3, but not e.g. correlation = (0, 1, 2) coexisting.

**Comment by malishav** [comment]
Just reading `-06` so I would like to take a step back: the point of `corr` is to allow us to omit `C_I` in `message_2`, which is typically 1 byte, and to omit `C_R` in `message_3`, again typically 1 byte. Do we have consensus that the complexity introduced by `corr` is worth saving that byte?

**Comment by gselander** [comment]
@malishav Yes, that is the question. And that goes back to the requirements on message sizes, in particular 45 bytes of message_2  coming from the 6tisch estimate. Are we making the right trade-off here?

This also depends on other potential optimizations, see #103, which also adds complexity but reduces overhead.

**Comment by gselander** [comment]
There is also the option that we say that corr = 0 by default, say, mandatory unless the Initiator and Responder agrees beforehand what corr value is used. 

(We still need to decide what other optimizations to make.)

**Comment by gselander** [comment]
Closing this since corr is now removed.
