### ISSUE TITLE
Computation of transcript hashes

### ISSUE THREAD

**Issue by malishav** [lake-wg/edhoc#96]
While working on the EDHOC hacspec with @karthikbhargavan and @TimothyClaeys, a following issue was discussed:

`TH_2` in `edhoc-05` is computed as:

`TH_2 = H(message_1, data_2 )`

This requires the Initiator to preserve the entire `message_1` in memory in order to calculate `TH_2` once `message_2` is received.  In order to simplify the implementations, wouldn't it make more sense to compute `TH_2` as `H(TH_1, data_2)`, where `TH_1 = H(message_1)`?

Similarly, `TH_3` is computed as:

`TH_3 = H(TH_2 , CIPHERTEXT_2, data_3)`,

which requires the Responder to preserve `CIPHERTEXT_2` in memory while waiting for `message_3` to arrive, in order to compute `TH_3`. `CIPHERTEXT_2` has a dynamic and potentially significant length: removing the need to preserve `CIPHERTEXT_2` in memory would simplify the embedded implementations.

A proposal is to define:

`TH_2' = H(TH_2, CIPHERTEXT_2)`, computed at the end of the creation process of message_2, and to finally calculate `TH_3` as:

`TH_3 = H(TH_2', data_3)`.

**Comment by emanjon** [comment]
Great to get some feedback and discussion on these things:


-- I am not sure that the first suggestion always simplifies or use less memory.

TH_2 = H(message_1, data_2 )
vs
TH_1 = H(message_1), TH_2 = H(TH_1, data_2)

The example size of message_1 is 37 bytes so a 32 byte TH_1 would not be much smaller. With a larger message_1 (AD_1 could be arbitrary large) is saves memory. But would not the implementation need to store a lot of the information in message_1 anyway to be able to process message_2? 


-- The second suggestion make a lot of sense to me, it seems to strictly improve memory use.

TH_3 = H(TH_2 , CIPHERTEXT_2, data_3),
vs
TH_2' = H(TH_2, CIPHERTEXT_2)
TH_3 = H(TH_2', data_3)

Would be good with some more detailed calculation as well as feedback from more implementors.

**Comment by malishav** [comment]
My take on the proposed `TH_1` is that it does simplify the implementation as you are dealing with a fixed size and do not need to worry how large `message_1` may grow. I see the value in doing this for embedded implementations. While I understand that the implementation needs to remember certain elements from message_1 after sending it, I do not see why it would need to save the serialized version of it after sending. Implementers feedback very welcome! @TimothyClaeys @marco-tiloca-sics @StefanHri

**Comment by StefanHri** [comment]
For me to use the approach proposed by malishav is a good idea. Fixed-length fields are easier to handle on constrained devices without dynamic memory allocation where only stack memory can be used.

**Comment by emanjon** [comment]
Good and quick input. Semms like we should do both of these changes then.

(If I remember correctly having a running transcript hash like TLS 1.3 is not optimal for some IoT devices)

**Comment by marco-tiloca-sics** [comment]
Looks good to me.

**Comment by TimothyClaeys** [comment]
+1 

Currently I'm saving intermediate hashing contexts in between different message processing methods so I don't have to store the individual parts that go into the transcript hash. My current way of implementing this is kind of hacky so I would be nice to see this properly defined in the specification.

https://github.com/openwsn-berkeley/EDHOC-C/blob/7da0b54d85dabaa1100d3404193014630e7f9123/src/process.c#L118
