### ISSUE TITLE
Forbidding multiple calls to EDHOC-Exporter with the same label

### ISSUE THREAD

**Issue by malishav** [lake-wg/edhoc#97]
The spec should likely forbid multiple calls to the EDHOC-Exporter interface with the same label, in order to prevent the same key being reused.

Discussed with @karthikbhargavan and @TimothyClaeys.

**Comment by emanjon** [comment]
Good catch. Yes, we should have some text about that, but it should probably more be a requirement on the application using EDHOC that on EDHOC itself. Two different application should defintly not use the same label. The same application might rederive the same key several times as long as it keep track of its AEAD nonces and replay window.

- I thought that we had already IANA registry proposed for this, but that is not the case. We should probably have one.
- If we have a IANA registry the labels get more fixed and it might be that we need a context input parameter as well.

**Comment by emanjon** [comment]
If we make a IANA registrer for labels, I think we need to let the application add additional information in some way. Two alternatives:

1. We make an IANA register for label prefixes, and let the application append information to the label prefix. This was recently planned for EAP-TLS (and methods built on EAP-TLS) but was changes because the TLS export labels are not really ment to be labels. This would not change the current exporter interface.

2. We expand the interface with a context parameter. This is similar to the TLS exporter. A problem with the TLS exporter is that some implementations decided to not even support context.

**Comment by malishav** [comment]
@emanjon how is the context parameter intended to be used? Could you give an example? Would this be some sort of "salt" when deriving the key?

**Comment by cabo** [comment]
Don't register labels, register label prefixes.

**Comment by emanjon** [comment]
The motivation for "context" or "label postfixes" is to increase the flexibility for the application. Restricting the application to IANA registered labels is very limiting. An application might want to use the EDHOC exporter to derive a number of keys and we should encourage that. The alternative is that the application needs to implement its own key derivation, which might be less secure and might be outside of the TEE. I called it "context" just because TLS calls the paramater in its exporter context.

**Comment by cabo** [comment]
"Be like TLS" is of course a good motivation.
Technically, a label prefix is not different from a context, it just saves the need to separate prefix and suffix.

**Comment by cabo** [comment]
(And of course there is nothing wrong with multiple calls with the same label; the application has a "right to forget" :-)

**Comment by emanjon** [comment]
The solutions should be equal when it comes to security. The choice should be made based on what is easiest for implementators and apllications using EDHOC.

Alt 1.
--------------------------

We make an IANA register for label prefixes:

  "OSCORE Master Secret"
  "OSCORE Master Salt"

The Export function stays the same:

      EDHOC-Exporter(label, length)
        = EDHOC-KDF(PRK_4x3m, TH_4, label, length)

An application is allowed to append things to the label prefix:

  "OSCORE Master Secret"
  "OSCORE Master Secret PickleRick"

Alt 2.
--------------------------

We make an IANA register for labels:

  label = "OSCORE Master Secret"
  label = "OSCORE Master Salt"

The Export function needs to change:

      EDHOC-Exporter(label, ctx, length)
        = EDHOC-KDF(PRK_4x3m, TH_4, [label, ctx] , length)

An application is not allowed to append things to the label and uses the ctx instead:

  label = "OSCORE Master Secret"
  ctx = ""

  label = "OSCORE Master Secret"
  ctx = "PickleRick"

**Comment by gselander** [comment]
No major opinion. Alt 2 breaks the test vector for the OSCORE security context.
It would be good to get more input.

**Comment by gselander** [comment]
Any preference @mcr, @pbtgit, @chrysn ?

**Comment by pbt-lab** [comment]
If desired the CTX is more convenient it can always be added in a wrapper on top of EDHOC-Exporter().
(I assume re-use of label+ctx in Alt 2 is equivalent to  re-use of label in Alt 1?)

**Comment by malishav** [comment]
I prefer to have `ctx` explicitly specified. We can pass to `EDHOC-KDF` the concatenation of `label` and `ctx`. When `ctx` is undefined/empty, test vectors are not affected. I guess this is what @pbt-lab is referring to?

**Comment by emanjon** [comment]
> I assume re-use of label+ctx in Alt 2 is equivalent to re-use of label in Alt 1?)

label is a CBOR byte string. While alt 2 use an CBOR array. Definging alt2 as a wrapper seems more complication in my view.

**Comment by emanjon** [comment]
Would be good if people stated alt 1. or alt 2. or made a concrete suggestion for alt 3.

**Comment by malishav** [comment]
Alt 3 (CBOR sequence)
--------------------------

We make an IANA register for labels:

  label = "OSCORE Master Secret"
  label = "OSCORE Master Salt"

The Export function needs to change:

      EDHOC-Exporter(label, ctx, length)
        = EDHOC-KDF(PRK_4x3m, TH_4, label_context, length)
        
where `label_context` is a CBOR sequence:

```
label_context = (
      label : tstr,
      ctx : tstr,
)
```

If you want to keep the test vectors intact, then you could make `ctx` optional in the CDDL, but not sure how to specify an optional parameter in the `EDHOC-Exporter` interface definition.

**Comment by emanjon** [comment]
Thanks. That is a valid alt 3. but ctx should probably be a bstr

**Comment by emanjon** [comment]
I don't think keeping the test vectors intact is an important goal at all. Let's decide on what is simplest for a user of the exporter interface.

**Comment by pbt-lab** [comment]
> I prefer to have `ctx` explicitly specified. We can pass to `EDHOC-KDF` the concatenation of `label` and `ctx`. When `ctx` is undefined/empty, test vectors are not affected. I guess this is what @pbt-lab is referring to?
Something like that, yes. Later post do differentiate the type of "label" and "ctx" and in light of that and changing test vectors Alt3 seems clean.

**Comment by emanjon** [comment]
I am fine with alt 3. I can start making PR for that unless somebody has different ideas.

I don't alt 1 is a good alternative anymore as is restricts context to being a unicode string. Which would require some base64 encoding or similar for a general context.

**Comment by gselander** [comment]
Please review alt. 3 as specified in #114. Unless there are any comments we would like to merge this.

**Comment by gselander** [comment]
This is included in -07 so I close the issue.
